# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Work\tafor\tafor\widgets\ui\settings.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(622, 475)
        Settings.setAcceptDrops(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Settings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main = QtWidgets.QHBoxLayout()
        self.main.setObjectName("main")
        self.left_side = QtWidgets.QWidget(Settings)
        self.left_side.setMaximumSize(QtCore.QSize(120, 16777215))
        self.left_side.setObjectName("left_side")
        self.leftbox = QtWidgets.QVBoxLayout(self.left_side)
        self.leftbox.setContentsMargins(0, 0, 0, 0)
        self.leftbox.setObjectName("leftbox")
        self.menu = QtWidgets.QListWidget(self.left_side)
        self.menu.setObjectName("menu")
        item = QtWidgets.QListWidgetItem()
        self.menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menu.addItem(item)
        self.leftbox.addWidget(self.menu)
        self.main.addWidget(self.left_side)
        self.stacked = QtWidgets.QStackedWidget(Settings)
        self.stacked.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stacked.setObjectName("stacked")
        self.convention_page = QtWidgets.QWidget()
        self.convention_page.setObjectName("convention_page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.convention_page)
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.convention_group = QtWidgets.QGroupBox(self.convention_page)
        self.convention_group.setObjectName("convention_group")
        self.formLayout_8 = QtWidgets.QFormLayout(self.convention_group)
        self.formLayout_8.setObjectName("formLayout_8")
        self.run_on_start = QtWidgets.QCheckBox(self.convention_group)
        self.run_on_start.setObjectName("run_on_start")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.run_on_start)
        self.close_to_minimize = QtWidgets.QCheckBox(self.convention_group)
        self.close_to_minimize.setObjectName("close_to_minimize")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.close_to_minimize)
        self.debug_mode = QtWidgets.QCheckBox(self.convention_group)
        self.debug_mode.setObjectName("debug_mode")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.debug_mode)
        self.verticalLayout_6.addWidget(self.convention_group)
        self.backup_group = QtWidgets.QGroupBox(self.convention_page)
        self.backup_group.setObjectName("backup_group")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.backup_group)
        self.gridLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.import_path = QtWidgets.QLineEdit(self.backup_group)
        self.import_path.setObjectName("import_path")
        self.gridLayout_5.addWidget(self.import_path, 0, 0, 1, 1)
        self.export_button = QtWidgets.QPushButton(self.backup_group)
        self.export_button.setObjectName("export_button")
        self.gridLayout_5.addWidget(self.export_button, 1, 2, 1, 1)
        self.import_button = QtWidgets.QPushButton(self.backup_group)
        self.import_button.setObjectName("import_button")
        self.gridLayout_5.addWidget(self.import_button, 0, 2, 1, 1)
        self.import_explore = QtWidgets.QPushButton(self.backup_group)
        self.import_explore.setObjectName("import_explore")
        self.gridLayout_5.addWidget(self.import_explore, 0, 1, 1, 1)
        self.export_explore = QtWidgets.QPushButton(self.backup_group)
        self.export_explore.setObjectName("export_explore")
        self.gridLayout_5.addWidget(self.export_explore, 1, 1, 1, 1)
        self.export_path = QtWidgets.QLineEdit(self.backup_group)
        self.export_path.setObjectName("export_path")
        self.gridLayout_5.addWidget(self.export_path, 1, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.backup_group)
        self.stacked.addWidget(self.convention_page)
        self.message_page = QtWidgets.QWidget()
        self.message_page.setObjectName("message_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.message_page)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.prefix_group = QtWidgets.QGroupBox(self.message_page)
        self.prefix_group.setObjectName("prefix_group")
        self.formLayout = QtWidgets.QFormLayout(self.prefix_group)
        self.formLayout.setObjectName("formLayout")
        self.icao_label = QtWidgets.QLabel(self.prefix_group)
        self.icao_label.setObjectName("icao_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.icao_label)
        self.icao = QtWidgets.QLineEdit(self.prefix_group)
        self.icao.setObjectName("icao")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.icao)
        self.intelligence_label = QtWidgets.QLabel(self.prefix_group)
        self.intelligence_label.setObjectName("intelligence_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.intelligence_label)
        self.intelligence = QtWidgets.QLineEdit(self.prefix_group)
        self.intelligence.setObjectName("intelligence")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.intelligence)
        self.fir_label = QtWidgets.QLabel(self.prefix_group)
        self.fir_label.setObjectName("fir_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.fir_label)
        self.fir = QtWidgets.QLineEdit(self.prefix_group)
        self.fir.setObjectName("fir")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fir)
        self.trend_sign_label = QtWidgets.QLabel(self.prefix_group)
        self.trend_sign_label.setObjectName("trend_sign_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.trend_sign_label)
        self.trend_sign = QtWidgets.QLineEdit(self.prefix_group)
        self.trend_sign.setObjectName("trend_sign")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.trend_sign)
        self.verticalLayout_2.addWidget(self.prefix_group)
        self.weather_group = QtWidgets.QGroupBox(self.message_page)
        self.weather_group.setObjectName("weather_group")
        self.gridLayout = QtWidgets.QGridLayout(self.weather_group)
        self.gridLayout.setObjectName("gridLayout")
        self.add_wx1_layout = QtWidgets.QHBoxLayout()
        self.add_wx1_layout.setObjectName("add_wx1_layout")
        self.weather1 = QtWidgets.QLineEdit(self.weather_group)
        self.weather1.setText("")
        self.weather1.setObjectName("weather1")
        self.add_wx1_layout.addWidget(self.weather1)
        self.add_weather1_button = QtWidgets.QPushButton(self.weather_group)
        self.add_weather1_button.setMaximumSize(QtCore.QSize(25, 16777215))
        self.add_weather1_button.setObjectName("add_weather1_button")
        self.add_wx1_layout.addWidget(self.add_weather1_button)
        self.del_weather1_button = QtWidgets.QPushButton(self.weather_group)
        self.del_weather1_button.setMaximumSize(QtCore.QSize(25, 16777215))
        self.del_weather1_button.setObjectName("del_weather1_button")
        self.add_wx1_layout.addWidget(self.del_weather1_button)
        self.gridLayout.addLayout(self.add_wx1_layout, 0, 0, 1, 1)
        self.add_wx2_layout = QtWidgets.QHBoxLayout()
        self.add_wx2_layout.setObjectName("add_wx2_layout")
        self.weather2 = QtWidgets.QLineEdit(self.weather_group)
        self.weather2.setObjectName("weather2")
        self.add_wx2_layout.addWidget(self.weather2)
        self.add_weather2_button = QtWidgets.QPushButton(self.weather_group)
        self.add_weather2_button.setMaximumSize(QtCore.QSize(25, 16777215))
        self.add_weather2_button.setObjectName("add_weather2_button")
        self.add_wx2_layout.addWidget(self.add_weather2_button)
        self.del_weather2_button = QtWidgets.QPushButton(self.weather_group)
        self.del_weather2_button.setMaximumSize(QtCore.QSize(25, 16777215))
        self.del_weather2_button.setObjectName("del_weather2_button")
        self.add_wx2_layout.addWidget(self.del_weather2_button)
        self.gridLayout.addLayout(self.add_wx2_layout, 0, 1, 1, 1)
        self.weather1_list = QtWidgets.QListWidget(self.weather_group)
        self.weather1_list.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.weather1_list.setObjectName("weather1_list")
        self.gridLayout.addWidget(self.weather1_list, 1, 0, 1, 1)
        self.weather2_list = QtWidgets.QListWidget(self.weather_group)
        self.weather2_list.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.weather2_list.setObjectName("weather2_list")
        self.gridLayout.addWidget(self.weather2_list, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.weather_group)
        self.stacked.addWidget(self.message_page)
        self.communication_page = QtWidgets.QWidget()
        self.communication_page.setObjectName("communication_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.communication_page)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.top_layout = QtWidgets.QHBoxLayout()
        self.top_layout.setObjectName("top_layout")
        self.serial_group = QtWidgets.QGroupBox(self.communication_page)
        self.serial_group.setObjectName("serial_group")
        self.formLayout_3 = QtWidgets.QFormLayout(self.serial_group)
        self.formLayout_3.setObjectName("formLayout_3")
        self.port_label = QtWidgets.QLabel(self.serial_group)
        self.port_label.setObjectName("port_label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.port_label)
        self.port = QtWidgets.QLineEdit(self.serial_group)
        self.port.setObjectName("port")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.port)
        self.baudrate_label = QtWidgets.QLabel(self.serial_group)
        self.baudrate_label.setObjectName("baudrate_label")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.baudrate_label)
        self.baudrate = QtWidgets.QLineEdit(self.serial_group)
        self.baudrate.setObjectName("baudrate")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.baudrate)
        self.parity_label = QtWidgets.QLabel(self.serial_group)
        self.parity_label.setObjectName("parity_label")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.parity_label)
        self.parity = QtWidgets.QComboBox(self.serial_group)
        self.parity.setObjectName("parity")
        self.parity.addItem("")
        self.parity.addItem("")
        self.parity.addItem("")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.parity)
        self.bytesize_label = QtWidgets.QLabel(self.serial_group)
        self.bytesize_label.setObjectName("bytesize_label")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.bytesize_label)
        self.bytesize = QtWidgets.QComboBox(self.serial_group)
        self.bytesize.setObjectName("bytesize")
        self.bytesize.addItem("")
        self.bytesize.addItem("")
        self.bytesize.addItem("")
        self.bytesize.addItem("")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.bytesize)
        self.stopbits_label = QtWidgets.QLabel(self.serial_group)
        self.stopbits_label.setObjectName("stopbits_label")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.stopbits_label)
        self.stopbits = QtWidgets.QComboBox(self.serial_group)
        self.stopbits.setObjectName("stopbits")
        self.stopbits.addItem("")
        self.stopbits.addItem("")
        self.stopbits.addItem("")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.stopbits)
        self.top_layout.addWidget(self.serial_group)
        self.other_group = QtWidgets.QGroupBox(self.communication_page)
        self.other_group.setObjectName("other_group")
        self.formLayout_7 = QtWidgets.QFormLayout(self.other_group)
        self.formLayout_7.setObjectName("formLayout_7")
        self.channel_label = QtWidgets.QLabel(self.other_group)
        self.channel_label.setObjectName("channel_label")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.channel_label)
        self.channel = QtWidgets.QLineEdit(self.other_group)
        self.channel.setObjectName("channel")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.channel)
        self.number_label = QtWidgets.QLabel(self.other_group)
        self.number_label.setObjectName("number_label")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.number_label)
        self.number = QtWidgets.QLineEdit(self.other_group)
        self.number.setObjectName("number")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.number)
        self.reset_number_button = QtWidgets.QPushButton(self.other_group)
        self.reset_number_button.setObjectName("reset_number_button")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.reset_number_button)
        self.request_addr_label = QtWidgets.QLabel(self.other_group)
        self.request_addr_label.setObjectName("request_addr_label")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.request_addr_label)
        self.request_addr = QtWidgets.QLineEdit(self.other_group)
        self.request_addr.setObjectName("request_addr")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.request_addr)
        self.user_addr_label = QtWidgets.QLabel(self.other_group)
        self.user_addr_label.setObjectName("user_addr_label")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.user_addr_label)
        self.user_addr = QtWidgets.QLineEdit(self.other_group)
        self.user_addr.setObjectName("user_addr")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.user_addr)
        self.top_layout.addWidget(self.other_group)
        self.verticalLayout_4.addLayout(self.top_layout)
        self.address_group = QtWidgets.QGroupBox(self.communication_page)
        self.address_group.setObjectName("address_group")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.address_group)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tabWidget = QtWidgets.QTabWidget(self.address_group)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_taf = QtWidgets.QWidget()
        self.tab_taf.setObjectName("tab_taf")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_taf)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.taf = QtWidgets.QTextEdit(self.tab_taf)
        self.taf.setObjectName("taf")
        self.verticalLayout_3.addWidget(self.taf)
        self.tabWidget.addTab(self.tab_taf, "")
        self.tab_sigmet = QtWidgets.QWidget()
        self.tab_sigmet.setObjectName("tab_sigmet")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_sigmet)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.sigmet = QtWidgets.QTextEdit(self.tab_sigmet)
        self.sigmet.setObjectName("sigmet")
        self.verticalLayout_7.addWidget(self.sigmet)
        self.tabWidget.addTab(self.tab_sigmet, "")
        self.tab_airmet = QtWidgets.QWidget()
        self.tab_airmet.setObjectName("tab_airmet")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_airmet)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.airmet = QtWidgets.QTextEdit(self.tab_airmet)
        self.airmet.setObjectName("airmet")
        self.verticalLayout_8.addWidget(self.airmet)
        self.tabWidget.addTab(self.tab_airmet, "")
        self.tab_trend = QtWidgets.QWidget()
        self.tab_trend.setObjectName("tab_trend")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_trend)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.trend = QtWidgets.QTextEdit(self.tab_trend)
        self.trend.setObjectName("trend")
        self.verticalLayout_9.addWidget(self.trend)
        self.tabWidget.addTab(self.tab_trend, "")
        self.verticalLayout_10.addWidget(self.tabWidget)
        self.verticalLayout_4.addWidget(self.address_group)
        self.stacked.addWidget(self.communication_page)
        self.monitor_page = QtWidgets.QWidget()
        self.monitor_page.setObjectName("monitor_page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.monitor_page)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.db_source_group = QtWidgets.QGroupBox(self.monitor_page)
        self.db_source_group.setObjectName("db_source_group")
        self.formLayout_6 = QtWidgets.QFormLayout(self.db_source_group)
        self.formLayout_6.setObjectName("formLayout_6")
        self.web_api = QtWidgets.QCheckBox(self.db_source_group)
        self.web_api.setObjectName("web_api")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.web_api)
        self.web_api_label = QtWidgets.QLabel(self.db_source_group)
        self.web_api_label.setObjectName("web_api_label")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.web_api_label)
        self.web_api_url = QtWidgets.QLineEdit(self.db_source_group)
        self.web_api_url.setObjectName("web_api_url")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.web_api_url)
        self.verticalLayout_5.addWidget(self.db_source_group)
        self.clock_group = QtWidgets.QGroupBox(self.monitor_page)
        self.clock_group.setObjectName("clock_group")
        self.formLayout_5 = QtWidgets.QFormLayout(self.clock_group)
        self.formLayout_5.setObjectName("formLayout_5")
        self.clock = QtWidgets.QCheckBox(self.clock_group)
        self.clock.setObjectName("clock")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.clock)
        self.clock_time_label = QtWidgets.QLabel(self.clock_group)
        self.clock_time_label.setObjectName("clock_time_label")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.clock_time_label)
        self.clock_time = QtWidgets.QLineEdit(self.clock_group)
        self.clock_time.setMaximumSize(QtCore.QSize(120, 16777215))
        self.clock_time.setObjectName("clock_time")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.clock_time)
        self.clock_volume_label = QtWidgets.QLabel(self.clock_group)
        self.clock_volume_label.setObjectName("clock_volume_label")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.clock_volume_label)
        self.clock_volume = QtWidgets.QSlider(self.clock_group)
        self.clock_volume.setOrientation(QtCore.Qt.Horizontal)
        self.clock_volume.setObjectName("clock_volume")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.clock_volume)
        self.verticalLayout_5.addWidget(self.clock_group)
        self.sound_group = QtWidgets.QGroupBox(self.monitor_page)
        self.sound_group.setObjectName("sound_group")
        self.formLayout_2 = QtWidgets.QFormLayout(self.sound_group)
        self.formLayout_2.setObjectName("formLayout_2")
        self.warn_taf = QtWidgets.QCheckBox(self.sound_group)
        self.warn_taf.setObjectName("warn_taf")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.warn_taf)
        self.warn_taf_volume = QtWidgets.QSlider(self.sound_group)
        self.warn_taf_volume.setOrientation(QtCore.Qt.Horizontal)
        self.warn_taf_volume.setObjectName("warn_taf_volume")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.warn_taf_volume)
        self.remind_trend = QtWidgets.QCheckBox(self.sound_group)
        self.remind_trend.setObjectName("remind_trend")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.remind_trend)
        self.remind_trend_volume = QtWidgets.QSlider(self.sound_group)
        self.remind_trend_volume.setOrientation(QtCore.Qt.Horizontal)
        self.remind_trend_volume.setObjectName("remind_trend_volume")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.remind_trend_volume)
        self.remind_sigmet = QtWidgets.QCheckBox(self.sound_group)
        self.remind_sigmet.setObjectName("remind_sigmet")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.remind_sigmet)
        self.remind_sigmet_volume = QtWidgets.QSlider(self.sound_group)
        self.remind_sigmet_volume.setOrientation(QtCore.Qt.Horizontal)
        self.remind_sigmet_volume.setObjectName("remind_sigmet_volume")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.remind_sigmet_volume)
        self.verticalLayout_5.addWidget(self.sound_group)
        self.call_service_group = QtWidgets.QGroupBox(self.monitor_page)
        self.call_service_group.setObjectName("call_service_group")
        self.formLayout_4 = QtWidgets.QFormLayout(self.call_service_group)
        self.formLayout_4.setObjectName("formLayout_4")
        self.warn_taf_time_label = QtWidgets.QLabel(self.call_service_group)
        self.warn_taf_time_label.setObjectName("warn_taf_time_label")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.warn_taf_time_label)
        self.warn_taf_time = QtWidgets.QLineEdit(self.call_service_group)
        self.warn_taf_time.setMaximumSize(QtCore.QSize(120, 16777215))
        self.warn_taf_time.setObjectName("warn_taf_time")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.warn_taf_time)
        self.call_service_url_label = QtWidgets.QLabel(self.call_service_group)
        self.call_service_url_label.setObjectName("call_service_url_label")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.call_service_url_label)
        self.call_service_url = QtWidgets.QLineEdit(self.call_service_group)
        self.call_service_url.setObjectName("call_service_url")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.call_service_url)
        self.call_service_token_label = QtWidgets.QLabel(self.call_service_group)
        self.call_service_token_label.setObjectName("call_service_token_label")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.call_service_token_label)
        self.call_service_token = QtWidgets.QLineEdit(self.call_service_group)
        self.call_service_token.setObjectName("call_service_token")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.call_service_token)
        self.verticalLayout_5.addWidget(self.call_service_group)
        self.stacked.addWidget(self.monitor_page)
        self.contract_page = QtWidgets.QWidget()
        self.contract_page.setObjectName("contract_page")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.contract_page)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.contract_group = QtWidgets.QGroupBox(self.contract_page)
        self.contract_group.setObjectName("contract_group")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.contract_group)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.add_person_layout = QtWidgets.QHBoxLayout()
        self.add_person_layout.setObjectName("add_person_layout")
        self.person_name = QtWidgets.QLineEdit(self.contract_group)
        self.person_name.setText("")
        self.person_name.setObjectName("person_name")
        self.add_person_layout.addWidget(self.person_name)
        self.person_mobile = QtWidgets.QLineEdit(self.contract_group)
        self.person_mobile.setObjectName("person_mobile")
        self.add_person_layout.addWidget(self.person_mobile)
        self.add_person_button = QtWidgets.QPushButton(self.contract_group)
        self.add_person_button.setMaximumSize(QtCore.QSize(25, 16777215))
        self.add_person_button.setObjectName("add_person_button")
        self.add_person_layout.addWidget(self.add_person_button)
        self.del_person_button = QtWidgets.QPushButton(self.contract_group)
        self.del_person_button.setMaximumSize(QtCore.QSize(25, 16777215))
        self.del_person_button.setObjectName("del_person_button")
        self.add_person_layout.addWidget(self.del_person_button)
        self.verticalLayout_12.addLayout(self.add_person_layout)
        self.contract_table = QtWidgets.QTableWidget(self.contract_group)
        self.contract_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.contract_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.contract_table.setObjectName("contract_table")
        self.contract_table.setColumnCount(2)
        self.contract_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.contract_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.contract_table.setHorizontalHeaderItem(1, item)
        self.contract_table.horizontalHeader().setStretchLastSection(True)
        self.contract_table.verticalHeader().setVisible(False)
        self.verticalLayout_12.addWidget(self.contract_table)
        self.select_contract_layout = QtWidgets.QHBoxLayout()
        self.select_contract_layout.setObjectName("select_contract_layout")
        self.select_contract_label = QtWidgets.QLabel(self.contract_group)
        self.select_contract_label.setObjectName("select_contract_label")
        self.select_contract_layout.addWidget(self.select_contract_label)
        self.select_contract = QtWidgets.QComboBox(self.contract_group)
        self.select_contract.setObjectName("select_contract")
        self.select_contract_layout.addWidget(self.select_contract)
        self.verticalLayout_12.addLayout(self.select_contract_layout)
        self.verticalLayout_11.addWidget(self.contract_group)
        self.stacked.addWidget(self.contract_page)
        self.main.addWidget(self.stacked)
        self.verticalLayout.addLayout(self.main)
        self.button_box = QtWidgets.QDialogButtonBox(Settings)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Reset)
        self.button_box.setObjectName("button_box")
        self.verticalLayout.addWidget(self.button_box)

        self.retranslateUi(Settings)
        self.stacked.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(3)
        self.button_box.accepted.connect(Settings.accept)
        self.button_box.rejected.connect(Settings.reject)
        self.menu.currentRowChanged['int'].connect(self.stacked.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(Settings)
        Settings.setTabOrder(self.menu, self.icao)
        Settings.setTabOrder(self.icao, self.intelligence)
        Settings.setTabOrder(self.intelligence, self.fir)
        Settings.setTabOrder(self.fir, self.trend_sign)
        Settings.setTabOrder(self.trend_sign, self.weather1)
        Settings.setTabOrder(self.weather1, self.add_weather1_button)
        Settings.setTabOrder(self.add_weather1_button, self.del_weather1_button)
        Settings.setTabOrder(self.del_weather1_button, self.weather1_list)
        Settings.setTabOrder(self.weather1_list, self.weather2)
        Settings.setTabOrder(self.weather2, self.add_weather2_button)
        Settings.setTabOrder(self.add_weather2_button, self.del_weather2_button)
        Settings.setTabOrder(self.del_weather2_button, self.weather2_list)
        Settings.setTabOrder(self.weather2_list, self.port)
        Settings.setTabOrder(self.port, self.baudrate)
        Settings.setTabOrder(self.baudrate, self.parity)
        Settings.setTabOrder(self.parity, self.bytesize)
        Settings.setTabOrder(self.bytesize, self.stopbits)
        Settings.setTabOrder(self.stopbits, self.channel)
        Settings.setTabOrder(self.channel, self.number)
        Settings.setTabOrder(self.number, self.request_addr)
        Settings.setTabOrder(self.request_addr, self.user_addr)
        Settings.setTabOrder(self.user_addr, self.tabWidget)
        Settings.setTabOrder(self.tabWidget, self.taf)
        Settings.setTabOrder(self.taf, self.sigmet)
        Settings.setTabOrder(self.sigmet, self.airmet)
        Settings.setTabOrder(self.airmet, self.trend)
        Settings.setTabOrder(self.trend, self.clock)
        Settings.setTabOrder(self.clock, self.clock_time)
        Settings.setTabOrder(self.clock_time, self.clock_volume)
        Settings.setTabOrder(self.clock_volume, self.warn_taf)
        Settings.setTabOrder(self.warn_taf, self.warn_taf_volume)
        Settings.setTabOrder(self.warn_taf_volume, self.remind_trend)
        Settings.setTabOrder(self.remind_trend, self.remind_trend_volume)
        Settings.setTabOrder(self.remind_trend_volume, self.remind_sigmet)
        Settings.setTabOrder(self.remind_sigmet, self.remind_sigmet_volume)
        Settings.setTabOrder(self.remind_sigmet_volume, self.warn_taf_time)
        Settings.setTabOrder(self.warn_taf_time, self.run_on_start)
        Settings.setTabOrder(self.run_on_start, self.close_to_minimize)
        Settings.setTabOrder(self.close_to_minimize, self.import_path)
        Settings.setTabOrder(self.import_path, self.import_explore)
        Settings.setTabOrder(self.import_explore, self.import_button)
        Settings.setTabOrder(self.import_button, self.export_path)
        Settings.setTabOrder(self.export_path, self.export_explore)
        Settings.setTabOrder(self.export_explore, self.export_button)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "设置"))
        __sortingEnabled = self.menu.isSortingEnabled()
        self.menu.setSortingEnabled(False)
        item = self.menu.item(0)
        item.setText(_translate("Settings", "常规"))
        item = self.menu.item(1)
        item.setText(_translate("Settings", "编报"))
        item = self.menu.item(2)
        item.setText(_translate("Settings", "通信"))
        item = self.menu.item(3)
        item.setText(_translate("Settings", "监控"))
        item = self.menu.item(4)
        item.setText(_translate("Settings", "联系人"))
        self.menu.setSortingEnabled(__sortingEnabled)
        self.convention_group.setTitle(_translate("Settings", "常规"))
        self.run_on_start.setText(_translate("Settings", "开机自动启动"))
        self.close_to_minimize.setText(_translate("Settings", "关闭时最小化到系统托盘"))
        self.debug_mode.setText(_translate("Settings", "启用调试模式"))
        self.backup_group.setTitle(_translate("Settings", "备份"))
        self.import_path.setPlaceholderText(_translate("Settings", "PATH"))
        self.export_button.setText(_translate("Settings", "导出"))
        self.import_button.setText(_translate("Settings", "导入"))
        self.import_explore.setText(_translate("Settings", "浏览"))
        self.export_explore.setText(_translate("Settings", "浏览"))
        self.export_path.setPlaceholderText(_translate("Settings", "PATH"))
        self.prefix_group.setTitle(_translate("Settings", "前缀"))
        self.icao_label.setText(_translate("Settings", "机场代码    "))
        self.icao.setPlaceholderText(_translate("Settings", "ZJHK"))
        self.intelligence_label.setText(_translate("Settings", "气象情报    "))
        self.intelligence.setPlaceholderText(_translate("Settings", "CI35"))
        self.fir_label.setText(_translate("Settings", "监视台责任区"))
        self.fir.setPlaceholderText(_translate("Settings", "ZJSA SANYA FIR"))
        self.trend_sign_label.setText(_translate("Settings", "趋势识别码  "))
        self.trend_sign.setPlaceholderText(_translate("Settings", "TREND"))
        self.weather_group.setTitle(_translate("Settings", "天气现象备案"))
        self.weather1.setPlaceholderText(_translate("Settings", "无强度变化的天气现象"))
        self.add_weather1_button.setText(_translate("Settings", "+"))
        self.del_weather1_button.setText(_translate("Settings", "—"))
        self.weather2.setPlaceholderText(_translate("Settings", "有强度变化的天气现象"))
        self.add_weather2_button.setText(_translate("Settings", "+"))
        self.del_weather2_button.setText(_translate("Settings", "—"))
        self.serial_group.setTitle(_translate("Settings", "串口参数"))
        self.port_label.setText(_translate("Settings", "端口  "))
        self.port.setPlaceholderText(_translate("Settings", "COM1"))
        self.baudrate_label.setText(_translate("Settings", "波特率"))
        self.baudrate.setPlaceholderText(_translate("Settings", "9600"))
        self.parity_label.setText(_translate("Settings", "校验位"))
        self.parity.setItemText(0, _translate("Settings", "NONE"))
        self.parity.setItemText(1, _translate("Settings", "EVEN"))
        self.parity.setItemText(2, _translate("Settings", "ODD"))
        self.bytesize_label.setText(_translate("Settings", "数据位"))
        self.bytesize.setItemText(0, _translate("Settings", "5"))
        self.bytesize.setItemText(1, _translate("Settings", "6"))
        self.bytesize.setItemText(2, _translate("Settings", "7"))
        self.bytesize.setItemText(3, _translate("Settings", "8"))
        self.stopbits_label.setText(_translate("Settings", "停止位"))
        self.stopbits.setItemText(0, _translate("Settings", "1"))
        self.stopbits.setItemText(1, _translate("Settings", "1.5"))
        self.stopbits.setItemText(2, _translate("Settings", "2"))
        self.other_group.setTitle(_translate("Settings", "其他"))
        self.channel_label.setText(_translate("Settings", "线路冠字"))
        self.channel.setPlaceholderText(_translate("Settings", "YMA"))
        self.number_label.setText(_translate("Settings", "流水号  "))
        self.number.setPlaceholderText(_translate("Settings", "1"))
        self.reset_number_button.setText(_translate("Settings", "复位"))
        self.request_addr_label.setText(_translate("Settings", "请求地址"))
        self.request_addr.setPlaceholderText(_translate("Settings", "ZGGGYZYX"))
        self.user_addr_label.setText(_translate("Settings", "用户单位"))
        self.user_addr.setPlaceholderText(_translate("Settings", "ZJHKYMYX"))
        self.address_group.setTitle(_translate("Settings", "发报地址"))
        self.taf.setPlaceholderText(_translate("Settings", "发报地址请以空格分隔"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_taf), _translate("Settings", "TAF"))
        self.sigmet.setPlaceholderText(_translate("Settings", "发报地址请以空格分隔"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_sigmet), _translate("Settings", "SIGMET"))
        self.airmet.setPlaceholderText(_translate("Settings", "发报地址请以空格分隔"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_airmet), _translate("Settings", "AIRMET"))
        self.trend.setPlaceholderText(_translate("Settings", "发报地址请以空格分隔"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_trend), _translate("Settings", "TREND"))
        self.db_source_group.setTitle(_translate("Settings", "监控数据源"))
        self.web_api.setText(_translate("Settings", "启用"))
        self.web_api_label.setText(_translate("Settings", "请求地址       "))
        self.web_api_url.setPlaceholderText(_translate("Settings", "URL"))
        self.clock_group.setTitle(_translate("Settings", "闹钟和音量"))
        self.clock.setText(_translate("Settings", "启用    "))
        self.clock_time_label.setText(_translate("Settings", "闹铃时间        "))
        self.clock_time.setPlaceholderText(_translate("Settings", "单位分钟"))
        self.clock_volume_label.setText(_translate("Settings", "音量            "))
        self.sound_group.setTitle(_translate("Settings", "声音提醒和音量"))
        self.warn_taf.setText(_translate("Settings", "报文迟发    "))
        self.remind_trend.setText(_translate("Settings", "趋势预报    "))
        self.remind_sigmet.setText(_translate("Settings", "重要气象情报"))
        self.call_service_group.setTitle(_translate("Settings", "电话服务"))
        self.warn_taf_time_label.setText(_translate("Settings", "提醒时间        "))
        self.warn_taf_time.setPlaceholderText(_translate("Settings", "单位分钟"))
        self.call_service_url_label.setText(_translate("Settings", "请求地址        "))
        self.call_service_url.setPlaceholderText(_translate("Settings", "URL"))
        self.call_service_token_label.setText(_translate("Settings", "认证            "))
        self.call_service_token.setPlaceholderText(_translate("Settings", "TOKEN"))
        self.contract_group.setTitle(_translate("Settings", "联系人"))
        self.person_name.setPlaceholderText(_translate("Settings", "姓名"))
        self.person_mobile.setPlaceholderText(_translate("Settings", "电话"))
        self.add_person_button.setText(_translate("Settings", "+"))
        self.del_person_button.setText(_translate("Settings", "—"))
        item = self.contract_table.horizontalHeaderItem(0)
        item.setText(_translate("Settings", "姓名"))
        item = self.contract_table.horizontalHeaderItem(1)
        item.setText(_translate("Settings", "电话"))
        self.select_contract_label.setText(_translate("Settings", "当前设置告警号码"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Settings = QtWidgets.QDialog()
    ui = Ui_Settings()
    ui.setupUi(Settings)
    Settings.show()
    sys.exit(app.exec_())

