# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Work\tafor\tafor\widgets\ui\widget_trend.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(865, 144)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_layout = QtWidgets.QGridLayout()
        self.main_layout.setObjectName("main_layout")
        self.cloud2_label = QtWidgets.QLabel(Form)
        self.cloud2_label.setObjectName("cloud2_label")
        self.main_layout.addWidget(self.cloud2_label, 2, 8, 1, 1)
        self.gust = QtWidgets.QLineEdit(Form)
        self.gust.setObjectName("gust")
        self.main_layout.addWidget(self.gust, 3, 3, 1, 1)
        self.weather1_label = QtWidgets.QLabel(Form)
        self.weather1_label.setObjectName("weather1_label")
        self.main_layout.addWidget(self.weather1_label, 2, 5, 1, 1)
        self.skc = QtWidgets.QCheckBox(Form)
        self.skc.setObjectName("skc")
        self.cavok_group = QtWidgets.QButtonGroup(Form)
        self.cavok_group.setObjectName("cavok_group")
        self.cavok_group.setExclusive(False)
        self.cavok_group.addButton(self.skc)
        self.main_layout.addWidget(self.skc, 4, 7, 1, 1)
        self.cloud1_label = QtWidgets.QLabel(Form)
        self.cloud1_label.setObjectName("cloud1_label")
        self.main_layout.addWidget(self.cloud1_label, 2, 7, 1, 1)
        self.cloud3_label = QtWidgets.QLabel(Form)
        self.cloud3_label.setObjectName("cloud3_label")
        self.main_layout.addWidget(self.cloud3_label, 2, 9, 1, 1)
        self.gust_label = QtWidgets.QLabel(Form)
        self.gust_label.setObjectName("gust_label")
        self.main_layout.addWidget(self.gust_label, 2, 3, 1, 1)
        self.weather2 = QtWidgets.QComboBox(Form)
        self.weather2.setObjectName("weather2")
        self.main_layout.addWidget(self.weather2, 3, 6, 1, 1)
        self.cloud2 = QtWidgets.QLineEdit(Form)
        self.cloud2.setObjectName("cloud2")
        self.main_layout.addWidget(self.cloud2, 3, 8, 1, 1)
        self.nsc = QtWidgets.QCheckBox(Form)
        self.nsc.setObjectName("nsc")
        self.cavok_group.addButton(self.nsc)
        self.main_layout.addWidget(self.nsc, 4, 8, 1, 1)
        self.vis_label = QtWidgets.QLabel(Form)
        self.vis_label.setObjectName("vis_label")
        self.main_layout.addWidget(self.vis_label, 2, 4, 1, 1)
        self.cloud1 = QtWidgets.QLineEdit(Form)
        self.cloud1.setObjectName("cloud1")
        self.main_layout.addWidget(self.cloud1, 3, 7, 1, 1)
        self.vis = QtWidgets.QLineEdit(Form)
        self.vis.setObjectName("vis")
        self.main_layout.addWidget(self.vis, 3, 4, 1, 1)
        self.weather1 = QtWidgets.QComboBox(Form)
        self.weather1.setObjectName("weather1")
        self.main_layout.addWidget(self.weather1, 3, 5, 1, 1)
        self.wind = QtWidgets.QLineEdit(Form)
        self.wind.setObjectName("wind")
        self.main_layout.addWidget(self.wind, 3, 2, 1, 1)
        self.cb_label = QtWidgets.QLabel(Form)
        self.cb_label.setObjectName("cb_label")
        self.main_layout.addWidget(self.cb_label, 2, 10, 1, 1)
        self.cb = QtWidgets.QLineEdit(Form)
        self.cb.setObjectName("cb")
        self.main_layout.addWidget(self.cb, 3, 10, 1, 1)
        self.cloud3 = QtWidgets.QLineEdit(Form)
        self.cloud3.setObjectName("cloud3")
        self.main_layout.addWidget(self.cloud3, 3, 9, 1, 1)
        self.weather2_label = QtWidgets.QLabel(Form)
        self.weather2_label.setObjectName("weather2_label")
        self.main_layout.addWidget(self.weather2_label, 2, 6, 1, 1)
        self.period_label = QtWidgets.QLabel(Form)
        self.period_label.setObjectName("period_label")
        self.main_layout.addWidget(self.period_label, 2, 1, 1, 1)
        self.period = QtWidgets.QLineEdit(Form)
        self.period.setObjectName("period")
        self.main_layout.addWidget(self.period, 3, 1, 1, 1)
        self.wind_label = QtWidgets.QLabel(Form)
        self.wind_label.setObjectName("wind_label")
        self.main_layout.addWidget(self.wind_label, 2, 2, 1, 1)
        self.group_prefix = QtWidgets.QGroupBox(Form)
        self.group_prefix.setTitle("")
        self.group_prefix.setObjectName("group_prefix")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.group_prefix)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.fm = QtWidgets.QRadioButton(self.group_prefix)
        self.fm.setChecked(True)
        self.fm.setObjectName("fm")
        self.gridLayout_5.addWidget(self.fm, 0, 0, 1, 1)
        self.tl = QtWidgets.QRadioButton(self.group_prefix)
        self.tl.setObjectName("tl")
        self.gridLayout_5.addWidget(self.tl, 0, 1, 1, 1)
        self.at = QtWidgets.QRadioButton(self.group_prefix)
        self.at.setObjectName("at")
        self.gridLayout_5.addWidget(self.at, 0, 2, 1, 1)
        self.main_layout.addWidget(self.group_prefix, 0, 3, 1, 2)
        self.group_type = QtWidgets.QGroupBox(Form)
        self.group_type.setTitle("")
        self.group_type.setObjectName("group_type")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.group_type)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.becmg = QtWidgets.QRadioButton(self.group_type)
        self.becmg.setChecked(True)
        self.becmg.setObjectName("becmg")
        self.gridLayout_6.addWidget(self.becmg, 0, 0, 1, 1)
        self.tempo = QtWidgets.QRadioButton(self.group_type)
        self.tempo.setObjectName("tempo")
        self.gridLayout_6.addWidget(self.tempo, 0, 1, 1, 1)
        self.main_layout.addWidget(self.group_type, 0, 0, 1, 3)
        self.cavok = QtWidgets.QCheckBox(Form)
        self.cavok.setCheckable(True)
        self.cavok.setObjectName("cavok")
        self.cavok_group.addButton(self.cavok)
        self.main_layout.addWidget(self.cavok, 4, 4, 1, 1)
        self.nosig = QtWidgets.QCheckBox(Form)
        self.nosig.setObjectName("nosig")
        self.main_layout.addWidget(self.nosig, 5, 1, 1, 1)
        self.verticalLayout.addLayout(self.main_layout)
        self.cloud2_label.setBuddy(self.cloud2)
        self.weather1_label.setBuddy(self.weather1)
        self.cloud1_label.setBuddy(self.cloud1)
        self.cloud3_label.setBuddy(self.cloud3)
        self.gust_label.setBuddy(self.gust)
        self.vis_label.setBuddy(self.vis)
        self.cb_label.setBuddy(self.cb)
        self.weather2_label.setBuddy(self.weather2)
        self.period_label.setBuddy(self.period)
        self.wind_label.setBuddy(self.wind)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.becmg, self.tempo)
        Form.setTabOrder(self.tempo, self.fm)
        Form.setTabOrder(self.fm, self.tl)
        Form.setTabOrder(self.tl, self.at)
        Form.setTabOrder(self.at, self.period)
        Form.setTabOrder(self.period, self.wind)
        Form.setTabOrder(self.wind, self.gust)
        Form.setTabOrder(self.gust, self.vis)
        Form.setTabOrder(self.vis, self.weather1)
        Form.setTabOrder(self.weather1, self.weather2)
        Form.setTabOrder(self.weather2, self.cloud1)
        Form.setTabOrder(self.cloud1, self.cloud2)
        Form.setTabOrder(self.cloud2, self.cloud3)
        Form.setTabOrder(self.cloud3, self.cb)
        Form.setTabOrder(self.cb, self.skc)
        Form.setTabOrder(self.skc, self.nsc)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.cloud2_label.setText(_translate("Form", "云组2"))
        self.weather1_label.setText(_translate("Form", "天气现象1"))
        self.skc.setText(_translate("Form", "SKC"))
        self.cloud1_label.setText(_translate("Form", "云组1"))
        self.cloud3_label.setText(_translate("Form", "云组3"))
        self.gust_label.setText(_translate("Form", "阵风"))
        self.nsc.setText(_translate("Form", "NSC"))
        self.vis_label.setText(_translate("Form", "能见度"))
        self.cb_label.setText(_translate("Form", "积雨云"))
        self.weather2_label.setText(_translate("Form", "天气现象2"))
        self.period_label.setText(_translate("Form", "时段"))
        self.wind_label.setText(_translate("Form", "风向风速"))
        self.fm.setText(_translate("Form", "FM"))
        self.tl.setText(_translate("Form", "TL"))
        self.at.setText(_translate("Form", "AT"))
        self.becmg.setText(_translate("Form", "BECMG"))
        self.tempo.setText(_translate("Form", "TEMPO"))
        self.cavok.setText(_translate("Form", "CAVOK"))
        self.nosig.setText(_translate("Form", "NOSIG"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

