# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Work\tafor\tafor\widgets\ui\widget_tempo.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 80)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layout = QtWidgets.QGridLayout()
        self.layout.setObjectName("layout")
        self.wind_label = QtWidgets.QLabel(Form)
        self.wind_label.setObjectName("wind_label")
        self.layout.addWidget(self.wind_label, 0, 5, 1, 1)
        self.cloud3_label = QtWidgets.QLabel(Form)
        self.cloud3_label.setObjectName("cloud3_label")
        self.layout.addWidget(self.cloud3_label, 0, 12, 1, 1)
        self.interval_label = QtWidgets.QLabel(Form)
        self.interval_label.setObjectName("interval_label")
        self.layout.addWidget(self.interval_label, 0, 4, 1, 1)
        self.interval = QtWidgets.QLineEdit(Form)
        self.interval.setObjectName("interval")
        self.layout.addWidget(self.interval, 2, 4, 1, 1)
        self.gust_label = QtWidgets.QLabel(Form)
        self.gust_label.setObjectName("gust_label")
        self.layout.addWidget(self.gust_label, 0, 6, 1, 1)
        self.cloud1 = QtWidgets.QLineEdit(Form)
        self.cloud1.setObjectName("cloud1")
        self.layout.addWidget(self.cloud1, 2, 10, 1, 1)
        self.weather2 = QtWidgets.QComboBox(Form)
        self.weather2.setObjectName("weather2")
        self.layout.addWidget(self.weather2, 2, 9, 1, 1)
        self.vis = QtWidgets.QLineEdit(Form)
        self.vis.setObjectName("vis")
        self.layout.addWidget(self.vis, 2, 7, 1, 1)
        self.cb = QtWidgets.QLineEdit(Form)
        self.cb.setObjectName("cb")
        self.layout.addWidget(self.cb, 2, 13, 1, 1)
        self.cloud2_label = QtWidgets.QLabel(Form)
        self.cloud2_label.setObjectName("cloud2_label")
        self.layout.addWidget(self.cloud2_label, 0, 11, 1, 1)
        self.vis_label = QtWidgets.QLabel(Form)
        self.vis_label.setObjectName("vis_label")
        self.layout.addWidget(self.vis_label, 0, 7, 1, 1)
        self.wind = QtWidgets.QLineEdit(Form)
        self.wind.setObjectName("wind")
        self.layout.addWidget(self.wind, 2, 5, 1, 1)
        self.weather2_label = QtWidgets.QLabel(Form)
        self.weather2_label.setObjectName("weather2_label")
        self.layout.addWidget(self.weather2_label, 0, 9, 1, 1)
        self.cloud2 = QtWidgets.QLineEdit(Form)
        self.cloud2.setObjectName("cloud2")
        self.layout.addWidget(self.cloud2, 2, 11, 1, 1)
        self.prob40 = QtWidgets.QCheckBox(Form)
        self.prob40.setEnabled(True)
        self.prob40.setAutoExclusive(True)
        self.prob40.setTristate(False)
        self.prob40.setObjectName("prob40")
        self.prob_group = QtWidgets.QButtonGroup(Form)
        self.prob_group.setObjectName("prob_group")
        self.prob_group.setExclusive(False)
        self.prob_group.addButton(self.prob40)
        self.layout.addWidget(self.prob40, 3, 5, 1, 1)
        self.gust = QtWidgets.QLineEdit(Form)
        self.gust.setObjectName("gust")
        self.layout.addWidget(self.gust, 2, 6, 1, 1)
        self.cloud1_label = QtWidgets.QLabel(Form)
        self.cloud1_label.setObjectName("cloud1_label")
        self.layout.addWidget(self.cloud1_label, 0, 10, 1, 1)
        self.cloud3 = QtWidgets.QLineEdit(Form)
        self.cloud3.setObjectName("cloud3")
        self.layout.addWidget(self.cloud3, 2, 12, 1, 1)
        self.prob30 = QtWidgets.QCheckBox(Form)
        self.prob30.setAutoExclusive(True)
        self.prob30.setObjectName("prob30")
        self.prob_group.addButton(self.prob30)
        self.layout.addWidget(self.prob30, 3, 4, 1, 1)
        self.weather1 = QtWidgets.QComboBox(Form)
        self.weather1.setObjectName("weather1")
        self.layout.addWidget(self.weather1, 2, 8, 1, 1)
        self.cb_label = QtWidgets.QLabel(Form)
        self.cb_label.setObjectName("cb_label")
        self.layout.addWidget(self.cb_label, 0, 13, 1, 1)
        self.weather1_label = QtWidgets.QLabel(Form)
        self.weather1_label.setObjectName("weather1_label")
        self.layout.addWidget(self.weather1_label, 0, 8, 1, 1)
        self.name = QtWidgets.QLabel(Form)
        self.name.setMinimumSize(QtCore.QSize(76, 0))
        self.name.setStyleSheet("color: rgb(120, 120, 120);")
        self.name.setObjectName("name")
        self.layout.addWidget(self.name, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.layout)
        self.wind_label.setBuddy(self.wind)
        self.cloud3_label.setBuddy(self.cloud3)
        self.interval_label.setBuddy(self.interval)
        self.gust_label.setBuddy(self.gust)
        self.cloud2_label.setBuddy(self.cloud2)
        self.vis_label.setBuddy(self.vis)
        self.weather2_label.setBuddy(self.weather2)
        self.cloud1_label.setBuddy(self.cloud1)
        self.cb_label.setBuddy(self.cb)
        self.weather1_label.setBuddy(self.weather1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.interval, self.wind)
        Form.setTabOrder(self.wind, self.gust)
        Form.setTabOrder(self.gust, self.vis)
        Form.setTabOrder(self.vis, self.weather1)
        Form.setTabOrder(self.weather1, self.weather2)
        Form.setTabOrder(self.weather2, self.cloud1)
        Form.setTabOrder(self.cloud1, self.cloud2)
        Form.setTabOrder(self.cloud2, self.cloud3)
        Form.setTabOrder(self.cloud3, self.cb)
        Form.setTabOrder(self.cb, self.prob30)
        Form.setTabOrder(self.prob30, self.prob40)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.wind_label.setText(_translate("Form", "风向风速"))
        self.cloud3_label.setText(_translate("Form", "云组3"))
        self.interval_label.setText(_translate("Form", "时段"))
        self.gust_label.setText(_translate("Form", "阵风"))
        self.cloud2_label.setText(_translate("Form", "云组2"))
        self.vis_label.setText(_translate("Form", "能见度"))
        self.weather2_label.setText(_translate("Form", "天气现象2"))
        self.prob40.setText(_translate("Form", "PROB40"))
        self.cloud1_label.setText(_translate("Form", "云组1"))
        self.prob30.setText(_translate("Form", "PROB30"))
        self.cb_label.setText(_translate("Form", "积雨云"))
        self.weather1_label.setText(_translate("Form", "天气现象1"))
        self.name.setText(_translate("Form", "TEMPO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

