language: python

python:
  - "3.6"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

install:
  - sudo apt-get update
  - sudo apt-get install libpulse-mainloop-glib0
  - sudo apt-get install pulseaudio
  - pip install --upgrade pytest
  - pip install -r requirements-dev.txt

script:
  - python setup.py test

after_success:
  - codecov

notifications:
    email: false
