[project]
name = "tafor"
version = "3.0.dev"
description = "A Terminal Aerodrome Forecast Encoding Software"
authors = [
    {name = "up1and", email = "piratecb@gmail.com"},
]
dependencies = [
    "falcon",
    "pyserial",
    "python-dateutil",
    "pyjwt",
    "pyjwt[crypto]",
    "pyshp",
    "pyproj",
    "waitress",
    "requests",
    "SQLAlchemy",
    "Shapely==1.8.5.post1",
    "PyQt5==5.15.11",
    "PyQtChart==5.15.7",
]

requires-python = ">=3.10, <3.12"

readme = "README.md"

license = {text = "GPL-3.0-or-later"}

keywords = ["aviation", "taf", "sigmet"]

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Other Audience",
    "License :: OSI Approved :: GNU General Public License v3 or Later (GPLv3+)",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering",
]

[project.urls]
Homepage = "https://github.com/up1and/tafor"

[dependency-groups]
dev = [
    "sphinx",
    "pytest",
    "pytest-qt",
    "pytest-cov",
    "pytest-env",
    "pyinstaller",
    "alembic",
    "colorama",
]

[tool.uv]
constraint-dependencies = [
    "greenlet<3.2",
    "PyQt5-Qt5==5.15.2",
    "PyQtChart-Qt5==5.15.2",
]

[tool.ruff.format]
quote-style = "single"
