# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Work\tafor\tafor\components\ui\main_recent.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Recent(object):
    def setupUi(self, Recent):
        Recent.setObjectName("Recent")
        Recent.resize(800, 116)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Recent.sizePolicy().hasHeightForWidth())
        Recent.setSizePolicy(sizePolicy)
        Recent.setWindowTitle("Recent")
        self.verticalLayout = QtWidgets.QVBoxLayout(Recent)
        self.verticalLayout.setObjectName("verticalLayout")
        self.group = QtWidgets.QGroupBox(Recent)
        self.group.setTitle("Type")
        self.group.setObjectName("group")
        self.groupLayout = QtWidgets.QVBoxLayout(self.group)
        self.groupLayout.setObjectName("groupLayout")
        self.toolsWidget = QtWidgets.QWidget(self.group)
        self.toolsWidget.setMinimumSize(QtCore.QSize(0, 30))
        self.toolsWidget.setObjectName("toolsWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.toolsWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.signLabel = QtWidgets.QLabel(self.toolsWidget)
        self.signLabel.setText("Sign")
        self.signLabel.setObjectName("signLabel")
        self.horizontalLayout.addWidget(self.signLabel)
        self.timeLabel = QtWidgets.QLabel(self.toolsWidget)
        self.timeLabel.setText("Time")
        self.timeLabel.setObjectName("timeLabel")
        self.horizontalLayout.addWidget(self.timeLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.reminderButton = QtWidgets.QToolButton(self.toolsWidget)
        self.reminderButton.setText("Reminder")
        self.reminderButton.setIconSize(QtCore.QSize(20, 20))
        self.reminderButton.setAutoRaise(True)
        self.reminderButton.setObjectName("reminderButton")
        self.horizontalLayout.addWidget(self.reminderButton)
        self.replyButton = QtWidgets.QToolButton(self.toolsWidget)
        self.replyButton.setEnabled(True)
        self.replyButton.setText("Reply")
        self.replyButton.setIconSize(QtCore.QSize(20, 20))
        self.replyButton.setAutoRaise(True)
        self.replyButton.setObjectName("replyButton")
        self.horizontalLayout.addWidget(self.replyButton)
        self.markButton = QtWidgets.QToolButton(self.toolsWidget)
        self.markButton.setText("Mark")
        self.markButton.setIconSize(QtCore.QSize(20, 20))
        self.markButton.setAutoRaise(True)
        self.markButton.setObjectName("markButton")
        self.horizontalLayout.addWidget(self.markButton)
        self.groupLayout.addWidget(self.toolsWidget)
        self.text = QtWidgets.QLabel(self.group)
        self.text.setText("Text Content")
        self.text.setWordWrap(True)
        self.text.setObjectName("text")
        self.groupLayout.addWidget(self.text)
        self.tip = QtWidgets.QLabel(self.group)
        self.tip.setText("Tip Content")
        self.tip.setObjectName("tip")
        self.groupLayout.addWidget(self.tip)
        self.verticalLayout.addWidget(self.group)

        self.retranslateUi(Recent)
        QtCore.QMetaObject.connectSlotsByName(Recent)

    def retranslateUi(self, Recent):
        pass


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Recent = QtWidgets.QWidget()
    ui = Ui_Recent()
    ui.setupUi(Recent)
    Recent.show()
    sys.exit(app.exec_())
