# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tafor/ui/qt/main_license.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Editor(object):
    def setupUi(self, Editor):
        Editor.setObjectName("Editor")
        Editor.resize(520, 360)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Editor.sizePolicy().hasHeightForWidth())
        Editor.setSizePolicy(sizePolicy)
        Editor.setMinimumSize(QtCore.QSize(520, 360))
        Editor.setMaximumSize(QtCore.QSize(520, 360))
        self.verticalLayout = QtWidgets.QVBoxLayout(Editor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Editor)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textarea = QtWidgets.QPlainTextEdit(Editor)
        self.textarea.setObjectName("textarea")
        self.verticalLayout.addWidget(self.textarea)
        self.buttonBox = QtWidgets.QDialogButtonBox(Editor)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Editor)
        self.buttonBox.accepted.connect(Editor.accept) # type: ignore
        self.buttonBox.rejected.connect(Editor.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Editor)

    def retranslateUi(self, Editor):
        _translate = QtCore.QCoreApplication.translate
        Editor.setWindowTitle(_translate("Editor", "Enter License"))
        self.label.setText(_translate("Editor", "Enter your license key below"))
