# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Work\tafor\tafor\components\ui\send.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Sender(object):
    def setupUi(self, Sender):
        Sender.setObjectName("Sender")
        Sender.resize(900, 526)
        self.verticalLayout = QtWidgets.QVBoxLayout(Sender)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textGroup = QtWidgets.QGroupBox(Sender)
        self.textGroup.setObjectName("textGroup")
        self.textLayout = QtWidgets.QVBoxLayout(self.textGroup)
        self.textLayout.setObjectName("textLayout")
        self.text = QtWidgets.QTextEdit(self.textGroup)
        self.text.setMinimumSize(QtCore.QSize(812, 0))
        self.text.setCursorWidth(0)
        self.text.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.text.setObjectName("text")
        self.textLayout.addWidget(self.text)
        self.verticalLayout.addWidget(self.textGroup)
        self.canvasGroup = QtWidgets.QGroupBox(Sender)
        self.canvasGroup.setObjectName("canvasGroup")
        self.canvasLayout = QtWidgets.QVBoxLayout(self.canvasGroup)
        self.canvasLayout.setObjectName("canvasLayout")
        self.verticalLayout.addWidget(self.canvasGroup)
        self.rawGroup = QtWidgets.QGroupBox(Sender)
        self.rawGroup.setObjectName("rawGroup")
        self.rawLayout = QtWidgets.QVBoxLayout(self.rawGroup)
        self.rawLayout.setObjectName("rawLayout")
        self.raw = QtWidgets.QTextEdit(self.rawGroup)
        self.raw.setMinimumSize(QtCore.QSize(812, 300))
        self.raw.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.raw.setCursorWidth(0)
        self.raw.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.raw.setObjectName("raw")
        self.rawLayout.addWidget(self.raw)
        self.verticalLayout.addWidget(self.rawGroup)
        self.buttonBox = QtWidgets.QDialogButtonBox(Sender)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Reset|QtWidgets.QDialogButtonBox.Retry)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Sender)
        self.buttonBox.rejected.connect(Sender.reject)
        QtCore.QMetaObject.connectSlotsByName(Sender)

    def retranslateUi(self, Sender):
        _translate = QtCore.QCoreApplication.translate
        Sender.setWindowTitle(_translate("Sender", "Send Message"))
        self.textGroup.setTitle(_translate("Sender", "Message"))
        self.canvasGroup.setTitle(_translate("Sender", "Canvas"))
        self.rawGroup.setTitle(_translate("Sender", "Data has been sent to the serial port"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Sender = QtWidgets.QDialog()
    ui = Ui_Sender()
    ui.setupUi(Sender)
    Sender.show()
    sys.exit(app.exec_())
