"""Initialize database

Revision ID: 336df6ecd4bc
Revises: 
Create Date: 2021-11-28 16:37:41.091138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '336df6ecd4bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
