"""Standardized table structure

Revision ID: 5d79cb3d6019
Revises: 336df6ecd4bc
Create Date: 2021-11-28 19:12:07.191338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d79cb3d6019'
down_revision = '336df6ecd4bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('metars', 'tt', new_column_name='type')
    op.alter_column('metars', 'rpt', new_column_name='text')

    op.alter_column('others', 'rpt', new_column_name='text')
    op.alter_column('others', 'sent', new_column_name='created')
    with op.batch_alter_table('others', schema=None) as batch_op:
        batch_op.alter_column('file', new_column_name='protocol', 
            existing_type=sa.TEXT(), type_=sa.String(length=16))

    op.alter_column('sigmets', 'rpt', new_column_name='text')
    op.alter_column('sigmets', 'sign', new_column_name='heading')
    op.alter_column('sigmets', 'tt', new_column_name='type')
    op.alter_column('sigmets', 'sent', new_column_name='created')
    with op.batch_alter_table('sigmets', schema=None) as batch_op:
        batch_op.alter_column('file', new_column_name='protocol', 
            existing_type=sa.TEXT(), type_=sa.String(length=16))

    op.alter_column('tafs', 'rpt', new_column_name='text')
    op.alter_column('tafs', 'sign', new_column_name='heading')
    op.alter_column('tafs', 'tt', new_column_name='type')
    op.alter_column('tafs', 'sent', new_column_name='created')
    with op.batch_alter_table('tafs', schema=None) as batch_op:
        batch_op.alter_column('file', new_column_name='protocol', 
            existing_type=sa.TEXT(), type_=sa.String(length=16))

    op.alter_column('trends', 'sign', new_column_name='heading')
    op.alter_column('trends', 'rpt', new_column_name='text')
    op.alter_column('trends', 'sent', new_column_name='created')
    op.add_column('trends', sa.Column('protocol', sa.String(length=16), nullable=True))

    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('metars', 'type', new_column_name='tt')
    op.alter_column('metars', 'text', new_column_name='rpt')

    op.alter_column('others', 'text', new_column_name='rpt')
    op.alter_column('others', 'created', new_column_name='sent')
    with op.batch_alter_table('others', schema=None) as batch_op:
        batch_op.alter_column('protocol', new_column_name='file', 
            existing_type=sa.String(length=16), type_=sa.TEXT())

    op.alter_column('sigmets', 'text', new_column_name='rpt')
    op.alter_column('sigmets', 'heading', new_column_name='sign')
    op.alter_column('sigmets', 'type', new_column_name='tt')
    op.alter_column('sigmets', 'created', new_column_name='sent')
    with op.batch_alter_table('sigmets', schema=None) as batch_op:
        batch_op.alter_column('protocol', new_column_name='file', 
            existing_type=sa.String(length=16), type_=sa.TEXT())

    op.alter_column('tafs', 'text', new_column_name='rpt')
    op.alter_column('tafs', 'heading', new_column_name='sign')
    op.alter_column('tafs', 'type', new_column_name='tt')
    op.alter_column('tafs', 'created', new_column_name='sent')
    with op.batch_alter_table('tafs', schema=None) as batch_op:
        batch_op.alter_column('protocol', new_column_name='file', 
            existing_type=sa.String(length=16), type_=sa.TEXT())

    op.alter_column('trends', 'heading', new_column_name='sign')
    op.alter_column('trends', 'text', new_column_name='rpt')
    op.alter_column('trends', 'created', new_column_name='sent')
    with op.batch_alter_table('trends', schema=None) as batch_op:
            batch_op.drop_column('protocol')

    op.create_table(
        'users',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('name', sa.String(8)),
        sa.Column('mobile', sa.String(20)),
    )
    # ### end Alembic commands ###
