"""Standardized table structure

Revision ID: 5d79cb3d6019
Revises: 336df6ecd4bc
Create Date: 2021-11-28 19:12:07.191338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d79cb3d6019'
down_revision = '336df6ecd4bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metars', schema=None) as batch_op:
        batch_op.alter_column('tt', new_column_name='type')
        batch_op.alter_column('rpt', new_column_name='text')

    with op.batch_alter_table('others', schema=None) as batch_op:
        batch_op.alter_column('rpt', new_column_name='text')
        batch_op.alter_column('sent', new_column_name='created')
        batch_op.alter_column('file', new_column_name='protocol', 
            existing_type=sa.TEXT(), type_=sa.String(length=16))

        batch_op.drop_column('tt')
        batch_op.drop_column('sign')

    with op.batch_alter_table('sigmets', schema=None) as batch_op:
        batch_op.alter_column('rpt', new_column_name='text')
        batch_op.alter_column('sign', new_column_name='heading')
        batch_op.alter_column('tt', new_column_name='type')
        batch_op.alter_column('sent', new_column_name='created')
        batch_op.alter_column('file', new_column_name='protocol', 
            existing_type=sa.TEXT(), type_=sa.String(length=16))

    with op.batch_alter_table('tafs', schema=None) as batch_op:
        batch_op.alter_column('rpt', new_column_name='text')
        batch_op.alter_column('sign', new_column_name='heading')
        batch_op.alter_column('tt', new_column_name='type')
        batch_op.alter_column('sent', new_column_name='created')
        batch_op.alter_column('file', new_column_name='protocol', 
            existing_type=sa.TEXT(), type_=sa.String(length=16))

    with op.batch_alter_table('trends', schema=None) as batch_op:
        batch_op.alter_column('sign', new_column_name='heading')
        batch_op.alter_column('rpt', new_column_name='text')
        batch_op.alter_column('sent', new_column_name='created')

    op.add_column('trends', sa.Column('protocol', sa.String(length=16), nullable=True))

    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metars', schema=None) as batch_op:
        batch_op.alter_column('type', new_column_name='tt')
        batch_op.alter_column('text', new_column_name='rpt')

    with op.batch_alter_table('others', schema=None) as batch_op:
        batch_op.alter_column('text', new_column_name='rpt')
        batch_op.alter_column('created', new_column_name='sent')
        batch_op.alter_column('protocol', new_column_name='file', 
            existing_type=sa.String(length=16), type_=sa.TEXT())

    op.add_column('others', sa.Column('tt', sa.String(length=2)))
    op.add_column('others', sa.Column('sign', sa.String(length=36)))

    with op.batch_alter_table('sigmets', schema=None) as batch_op:
        batch_op.alter_column('text', new_column_name='rpt')
        batch_op.alter_column('heading', new_column_name='sign')
        batch_op.alter_column('type', new_column_name='tt')
        batch_op.alter_column('created', new_column_name='sent')
        batch_op.alter_column('protocol', new_column_name='file', 
            existing_type=sa.String(length=16), type_=sa.TEXT())

    with op.batch_alter_table('tafs', schema=None) as batch_op:
        batch_op.alter_column('text', new_column_name='rpt')
        batch_op.alter_column('heading', new_column_name='sign')
        batch_op.alter_column('type', new_column_name='tt')
        batch_op.alter_column('created', new_column_name='sent')
        batch_op.alter_column('protocol', new_column_name='file', 
            existing_type=sa.String(length=16), type_=sa.TEXT())

    with op.batch_alter_table('trends', schema=None) as batch_op:
        batch_op.alter_column('heading', new_column_name='sign')
        batch_op.alter_column('text', new_column_name='rpt')
        batch_op.alter_column('created', new_column_name='sent')
        batch_op.drop_column('protocol')

    op.create_table(
        'users',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('name', sa.String(8)),
        sa.Column('mobile', sa.String(20)),
    )
    # ### end Alembic commands ###
