# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Chen\Work\tafor\tafor\components\ui\main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(870, 650)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainTab = QtWidgets.QTabWidget(self.centralWidget)
        self.mainTab.setMinimumSize(QtCore.QSize(850, 0))
        self.mainTab.setMovable(True)
        self.mainTab.setObjectName("mainTab")
        self.recentTab = QtWidgets.QWidget()
        self.recentTab.setObjectName("recentTab")
        self.recentLayout = QtWidgets.QVBoxLayout(self.recentTab)
        self.recentLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.recentLayout.setContentsMargins(0, 0, 0, 0)
        self.recentLayout.setObjectName("recentLayout")
        self.tips = QtWidgets.QWidget(self.recentTab)
        self.tips.setMinimumSize(QtCore.QSize(845, 0))
        self.tips.setObjectName("tips")
        self.tipsLayout = QtWidgets.QHBoxLayout(self.tips)
        self.tipsLayout.setContentsMargins(10, 20, 10, 20)
        self.tipsLayout.setObjectName("tipsLayout")
        self.recentLayout.addWidget(self.tips)
        self.mainTab.addTab(self.recentTab, "")
        self.tafTab = QtWidgets.QWidget()
        self.tafTab.setObjectName("tafTab")
        self.tafLayout = QtWidgets.QVBoxLayout(self.tafTab)
        self.tafLayout.setContentsMargins(0, 0, 0, 0)
        self.tafLayout.setObjectName("tafLayout")
        self.mainTab.addTab(self.tafTab, "")
        self.metarTab = QtWidgets.QWidget()
        self.metarTab.setObjectName("metarTab")
        self.metarLayout = QtWidgets.QVBoxLayout(self.metarTab)
        self.metarLayout.setContentsMargins(0, 0, 0, 0)
        self.metarLayout.setObjectName("metarLayout")
        self.mainTab.addTab(self.metarTab, "")
        self.sigmetTab = QtWidgets.QWidget()
        self.sigmetTab.setObjectName("sigmetTab")
        self.sigmetLayout = QtWidgets.QVBoxLayout(self.sigmetTab)
        self.sigmetLayout.setContentsMargins(0, 0, 0, 0)
        self.sigmetLayout.setObjectName("sigmetLayout")
        self.mainTab.addTab(self.sigmetTab, "SIGMET")
        self.verticalLayout.addWidget(self.mainTab)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 870, 23))
        self.menuBar.setObjectName("menuBar")
        self.postMenu = QtWidgets.QMenu(self.menuBar)
        self.postMenu.setObjectName("postMenu")
        self.settingMenu = QtWidgets.QMenu(self.menuBar)
        self.settingMenu.setObjectName("settingMenu")
        self.contractsMenu = QtWidgets.QMenu(self.settingMenu)
        self.contractsMenu.setObjectName("contractsMenu")
        self.helpMenu = QtWidgets.QMenu(self.menuBar)
        self.helpMenu.setObjectName("helpMenu")
        self.viewMenu = QtWidgets.QMenu(self.menuBar)
        self.viewMenu.setObjectName("viewMenu")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.tafAction = QtWidgets.QAction(MainWindow)
        self.tafAction.setObjectName("tafAction")
        self.trendAction = QtWidgets.QAction(MainWindow)
        self.trendAction.setObjectName("trendAction")
        self.sigmetAction = QtWidgets.QAction(MainWindow)
        self.sigmetAction.setObjectName("sigmetAction")
        self.settingAction = QtWidgets.QAction(MainWindow)
        self.settingAction.setObjectName("settingAction")
        self.aboutAction = QtWidgets.QAction(MainWindow)
        self.aboutAction.setObjectName("aboutAction")
        self.quitAction = QtWidgets.QAction(MainWindow)
        self.quitAction.setObjectName("quitAction")
        self.contractNo = QtWidgets.QAction(MainWindow)
        self.contractNo.setCheckable(True)
        self.contractNo.setObjectName("contractNo")
        self.reportIssueAction = QtWidgets.QAction(MainWindow)
        self.reportIssueAction.setObjectName("reportIssueAction")
        self.openDocsAction = QtWidgets.QAction(MainWindow)
        self.openDocsAction.setObjectName("openDocsAction")
        self.warnTAFAction = QtWidgets.QAction(MainWindow)
        self.warnTAFAction.setCheckable(True)
        self.warnTAFAction.setChecked(True)
        self.warnTAFAction.setObjectName("warnTAFAction")
        self.checkUpgradeAction = QtWidgets.QAction(MainWindow)
        self.checkUpgradeAction.setObjectName("checkUpgradeAction")
        self.previousPageAction = QtWidgets.QAction(MainWindow)
        self.previousPageAction.setObjectName("previousPageAction")
        self.nextPageAction = QtWidgets.QAction(MainWindow)
        self.nextPageAction.setObjectName("nextPageAction")
        self.postMenu.addAction(self.tafAction)
        self.postMenu.addAction(self.trendAction)
        self.postMenu.addAction(self.sigmetAction)
        self.postMenu.addSeparator()
        self.postMenu.addAction(self.quitAction)
        self.contractsMenu.addAction(self.contractNo)
        self.contractsMenu.addSeparator()
        self.settingMenu.addAction(self.warnTAFAction)
        self.settingMenu.addAction(self.contractsMenu.menuAction())
        self.settingMenu.addSeparator()
        self.settingMenu.addAction(self.settingAction)
        self.helpMenu.addAction(self.openDocsAction)
        self.helpMenu.addAction(self.reportIssueAction)
        self.helpMenu.addAction(self.checkUpgradeAction)
        self.helpMenu.addSeparator()
        self.helpMenu.addAction(self.aboutAction)
        self.viewMenu.addAction(self.previousPageAction)
        self.viewMenu.addAction(self.nextPageAction)
        self.menuBar.addAction(self.postMenu.menuAction())
        self.menuBar.addAction(self.settingMenu.menuAction())
        self.menuBar.addAction(self.viewMenu.menuAction())
        self.menuBar.addAction(self.helpMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.mainTab.setCurrentIndex(0)
        self.quitAction.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Terminal Aerodrome Forecast Encoding Software"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.recentTab), _translate("MainWindow", "RECENT"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.tafTab), _translate("MainWindow", "TAF"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.metarTab), _translate("MainWindow", "METAR"))
        self.postMenu.setTitle(_translate("MainWindow", "Post"))
        self.settingMenu.setTitle(_translate("MainWindow", "Options"))
        self.contractsMenu.setTitle(_translate("MainWindow", "Contacts"))
        self.helpMenu.setTitle(_translate("MainWindow", "Help"))
        self.viewMenu.setTitle(_translate("MainWindow", "View"))
        self.tafAction.setText(_translate("MainWindow", "Terminal Aerodrome Forecast"))
        self.trendAction.setText(_translate("MainWindow", "Trend Forecast"))
        self.sigmetAction.setText(_translate("MainWindow", "Significant Meteorological Information"))
        self.settingAction.setText(_translate("MainWindow", "Settings"))
        self.aboutAction.setText(_translate("MainWindow", "About"))
        self.quitAction.setText(_translate("MainWindow", "Exit"))
        self.contractNo.setText(_translate("MainWindow", "None"))
        self.reportIssueAction.setText(_translate("MainWindow", "Report Issue"))
        self.openDocsAction.setText(_translate("MainWindow", "Documents"))
        self.warnTAFAction.setText(_translate("MainWindow", "Alarm Sound"))
        self.checkUpgradeAction.setText(_translate("MainWindow", "Check for Updates"))
        self.previousPageAction.setText(_translate("MainWindow", "Previous Page"))
        self.nextPageAction.setText(_translate("MainWindow", "Next Page"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

