# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Work\tafor\tafor\components\ui\main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(870, 650)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainTab = QtWidgets.QTabWidget(self.centralWidget)
        self.mainTab.setMinimumSize(QtCore.QSize(850, 0))
        self.mainTab.setMovable(True)
        self.mainTab.setObjectName("mainTab")
        self.recentTab = QtWidgets.QWidget()
        self.recentTab.setObjectName("recentTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.recentTab)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.recentArea = QtWidgets.QScrollArea(self.recentTab)
        self.recentArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.recentArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.recentArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.recentArea.setWidgetResizable(True)
        self.recentArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.recentArea.setObjectName("recentArea")
        self.scrollContents = QtWidgets.QWidget()
        self.scrollContents.setGeometry(QtCore.QRect(0, 0, 828, 544))
        self.scrollContents.setStyleSheet("background:#FFF")
        self.scrollContents.setObjectName("scrollContents")
        self.recentLayout = QtWidgets.QVBoxLayout(self.scrollContents)
        self.recentLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.recentLayout.setContentsMargins(0, 0, 0, 0)
        self.recentLayout.setSpacing(0)
        self.recentLayout.setObjectName("recentLayout")
        self.tips = QtWidgets.QWidget(self.scrollContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tips.sizePolicy().hasHeightForWidth())
        self.tips.setSizePolicy(sizePolicy)
        self.tips.setObjectName("tips")
        self.tipsLayout = QtWidgets.QHBoxLayout(self.tips)
        self.tipsLayout.setContentsMargins(10, 20, 10, 20)
        self.tipsLayout.setObjectName("tipsLayout")
        self.recentLayout.addWidget(self.tips)
        self.recentArea.setWidget(self.scrollContents)
        self.verticalLayout_3.addWidget(self.recentArea)
        self.mainTab.addTab(self.recentTab, "")
        self.tafTab = QtWidgets.QWidget()
        self.tafTab.setObjectName("tafTab")
        self.tafLayout = QtWidgets.QVBoxLayout(self.tafTab)
        self.tafLayout.setContentsMargins(0, 0, 0, 0)
        self.tafLayout.setObjectName("tafLayout")
        self.mainTab.addTab(self.tafTab, "")
        self.metarTab = QtWidgets.QWidget()
        self.metarTab.setObjectName("metarTab")
        self.metarLayout = QtWidgets.QVBoxLayout(self.metarTab)
        self.metarLayout.setContentsMargins(0, 0, 0, 0)
        self.metarLayout.setObjectName("metarLayout")
        self.mainTab.addTab(self.metarTab, "")
        self.sigmetTab = QtWidgets.QWidget()
        self.sigmetTab.setObjectName("sigmetTab")
        self.sigmetLayout = QtWidgets.QVBoxLayout(self.sigmetTab)
        self.sigmetLayout.setContentsMargins(0, 0, 0, 0)
        self.sigmetLayout.setObjectName("sigmetLayout")
        self.mainTab.addTab(self.sigmetTab, "SIGMET")
        self.verticalLayout.addWidget(self.mainTab)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 870, 23))
        self.menuBar.setObjectName("menuBar")
        self.issueMenu = QtWidgets.QMenu(self.menuBar)
        self.issueMenu.setObjectName("issueMenu")
        self.settingMenu = QtWidgets.QMenu(self.menuBar)
        self.settingMenu.setObjectName("settingMenu")
        self.contractsMenu = QtWidgets.QMenu(self.settingMenu)
        self.contractsMenu.setObjectName("contractsMenu")
        self.helpMenu = QtWidgets.QMenu(self.menuBar)
        self.helpMenu.setObjectName("helpMenu")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.tafAction = QtWidgets.QAction(MainWindow)
        self.tafAction.setShortcut("Ctrl+F")
        self.tafAction.setObjectName("tafAction")
        self.trendAction = QtWidgets.QAction(MainWindow)
        self.trendAction.setShortcut("Ctrl+T")
        self.trendAction.setObjectName("trendAction")
        self.sigmetAction = QtWidgets.QAction(MainWindow)
        self.sigmetAction.setShortcut("Ctrl+S")
        self.sigmetAction.setObjectName("sigmetAction")
        self.settingAction = QtWidgets.QAction(MainWindow)
        self.settingAction.setShortcut("Ctrl+,")
        self.settingAction.setObjectName("settingAction")
        self.aboutAction = QtWidgets.QAction(MainWindow)
        self.aboutAction.setObjectName("aboutAction")
        self.quitAction = QtWidgets.QAction(MainWindow)
        self.quitAction.setObjectName("quitAction")
        self.contractNo = QtWidgets.QAction(MainWindow)
        self.contractNo.setCheckable(True)
        self.contractNo.setObjectName("contractNo")
        self.reportIssueAction = QtWidgets.QAction(MainWindow)
        self.reportIssueAction.setObjectName("reportIssueAction")
        self.openDocsAction = QtWidgets.QAction(MainWindow)
        self.openDocsAction.setObjectName("openDocsAction")
        self.warnTafAction = QtWidgets.QAction(MainWindow)
        self.warnTafAction.setCheckable(True)
        self.warnTafAction.setChecked(True)
        self.warnTafAction.setObjectName("warnTafAction")
        self.checkUpgradeAction = QtWidgets.QAction(MainWindow)
        self.checkUpgradeAction.setObjectName("checkUpgradeAction")
        self.previousPageAction = QtWidgets.QAction(MainWindow)
        self.previousPageAction.setObjectName("previousPageAction")
        self.nextPageAction = QtWidgets.QAction(MainWindow)
        self.nextPageAction.setObjectName("nextPageAction")
        self.issueMenu.addAction(self.tafAction)
        self.issueMenu.addAction(self.trendAction)
        self.issueMenu.addAction(self.sigmetAction)
        self.issueMenu.addSeparator()
        self.issueMenu.addAction(self.quitAction)
        self.contractsMenu.addAction(self.contractNo)
        self.contractsMenu.addSeparator()
        self.settingMenu.addAction(self.warnTafAction)
        self.settingMenu.addAction(self.contractsMenu.menuAction())
        self.settingMenu.addSeparator()
        self.settingMenu.addAction(self.settingAction)
        self.helpMenu.addAction(self.openDocsAction)
        self.helpMenu.addAction(self.reportIssueAction)
        self.helpMenu.addAction(self.checkUpgradeAction)
        self.helpMenu.addSeparator()
        self.helpMenu.addAction(self.aboutAction)
        self.menuBar.addAction(self.issueMenu.menuAction())
        self.menuBar.addAction(self.settingMenu.menuAction())
        self.menuBar.addAction(self.helpMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.mainTab.setCurrentIndex(0)
        self.quitAction.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Terminal Aerodrome Forecast Encoding Software"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.recentTab), _translate("MainWindow", "RECENT"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.tafTab), _translate("MainWindow", "TAF"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.metarTab), _translate("MainWindow", "METAR"))
        self.issueMenu.setTitle(_translate("MainWindow", "Issue"))
        self.settingMenu.setTitle(_translate("MainWindow", "Options"))
        self.contractsMenu.setTitle(_translate("MainWindow", "Contacts"))
        self.helpMenu.setTitle(_translate("MainWindow", "Help"))
        self.tafAction.setText(_translate("MainWindow", "Terminal Aerodrome Forecast"))
        self.trendAction.setText(_translate("MainWindow", "Trend Forecast"))
        self.sigmetAction.setText(_translate("MainWindow", "Significant Meteorological Information"))
        self.settingAction.setText(_translate("MainWindow", "Settings"))
        self.aboutAction.setText(_translate("MainWindow", "About"))
        self.quitAction.setText(_translate("MainWindow", "Exit"))
        self.contractNo.setText(_translate("MainWindow", "None"))
        self.reportIssueAction.setText(_translate("MainWindow", "Report Issue"))
        self.openDocsAction.setText(_translate("MainWindow", "Documents"))
        self.warnTafAction.setText(_translate("MainWindow", "Alarm Sound"))
        self.checkUpgradeAction.setText(_translate("MainWindow", "Check for Updates"))
        self.previousPageAction.setText(_translate("MainWindow", "Previous Page"))
        self.nextPageAction.setText(_translate("MainWindow", "Next Page"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

