# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Work\tafor\tafor\components\ui\main_recent.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Recent(object):
    def setupUi(self, Recent):
        Recent.setObjectName("Recent")
        Recent.resize(872, 98)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Recent.sizePolicy().hasHeightForWidth())
        Recent.setSizePolicy(sizePolicy)
        Recent.setWindowTitle("Recent")
        self.verticalLayout = QtWidgets.QVBoxLayout(Recent)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Recent)
        self.groupBox.setTitle("Report Type")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.toolsWidget = QtWidgets.QWidget(self.groupBox)
        self.toolsWidget.setMinimumSize(QtCore.QSize(0, 30))
        self.toolsWidget.setObjectName("toolsWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.toolsWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.signLabel = QtWidgets.QLabel(self.toolsWidget)
        self.signLabel.setText("Sign")
        self.signLabel.setObjectName("signLabel")
        self.horizontalLayout.addWidget(self.signLabel)
        self.timeLabel = QtWidgets.QLabel(self.toolsWidget)
        self.timeLabel.setText("Time")
        self.timeLabel.setObjectName("timeLabel")
        self.horizontalLayout.addWidget(self.timeLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.replyButton = QtWidgets.QToolButton(self.toolsWidget)
        self.replyButton.setEnabled(True)
        self.replyButton.setIconSize(QtCore.QSize(20, 20))
        self.replyButton.setAutoRaise(True)
        self.replyButton.setObjectName("replyButton")
        self.horizontalLayout.addWidget(self.replyButton)
        self.markButton = QtWidgets.QToolButton(self.toolsWidget)
        self.markButton.setText("Mark")
        self.markButton.setIconSize(QtCore.QSize(20, 20))
        self.markButton.setAutoRaise(True)
        self.markButton.setObjectName("markButton")
        self.horizontalLayout.addWidget(self.markButton)
        self.verticalLayout_2.addWidget(self.toolsWidget)
        self.rpt = QtWidgets.QLabel(self.groupBox)
        self.rpt.setText("Report Content")
        self.rpt.setWordWrap(True)
        self.rpt.setObjectName("rpt")
        self.verticalLayout_2.addWidget(self.rpt)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(Recent)
        QtCore.QMetaObject.connectSlotsByName(Recent)

    def retranslateUi(self, Recent):
        _translate = QtCore.QCoreApplication.translate
        self.replyButton.setText(_translate("Recent", "Reply"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Recent = QtWidgets.QWidget()
    ui = Ui_Recent()
    ui.setupUi(Recent)
    Recent.show()
    sys.exit(app.exec_())
