# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Work\tafor\tafor\components\ui\setting.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Setting(object):
    def setupUi(self, Setting):
        Setting.setObjectName("Setting")
        Setting.resize(620, 396)
        Setting.setAcceptDrops(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Setting)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainLayout = QtWidgets.QHBoxLayout()
        self.mainLayout.setObjectName("mainLayout")
        self.leftLayout = QtWidgets.QWidget(Setting)
        self.leftLayout.setMaximumSize(QtCore.QSize(120, 16777215))
        self.leftLayout.setObjectName("leftLayout")
        self.leftbox = QtWidgets.QVBoxLayout(self.leftLayout)
        self.leftbox.setContentsMargins(0, 0, 0, 0)
        self.leftbox.setObjectName("leftbox")
        self.menu = QtWidgets.QListWidget(self.leftLayout)
        self.menu.setObjectName("menu")
        item = QtWidgets.QListWidgetItem()
        self.menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menu.addItem(item)
        self.leftbox.addWidget(self.menu)
        self.mainLayout.addWidget(self.leftLayout)
        self.stackedWidget = QtWidgets.QStackedWidget(Setting)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setObjectName("stackedWidget")
        self.generalPage = QtWidgets.QWidget()
        self.generalPage.setObjectName("generalPage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.generalPage)
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.generalGroup = QtWidgets.QGroupBox(self.generalPage)
        self.generalGroup.setObjectName("generalGroup")
        self.formLayout_8 = QtWidgets.QFormLayout(self.generalGroup)
        self.formLayout_8.setObjectName("formLayout_8")
        self.runOnStart = QtWidgets.QCheckBox(self.generalGroup)
        self.runOnStart.setObjectName("runOnStart")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.runOnStart)
        self.closeToMinimize = QtWidgets.QCheckBox(self.generalGroup)
        self.closeToMinimize.setObjectName("closeToMinimize")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.closeToMinimize)
        self.debugMode = QtWidgets.QCheckBox(self.generalGroup)
        self.debugMode.setObjectName("debugMode")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.debugMode)
        self.alwaysShowEditor = QtWidgets.QCheckBox(self.generalGroup)
        self.alwaysShowEditor.setObjectName("alwaysShowEditor")
        self.formLayout_8.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.alwaysShowEditor)
        self.label = QtWidgets.QLabel(self.generalGroup)
        self.label.setObjectName("label")
        self.formLayout_8.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label)
        self.languageCombox = QtWidgets.QComboBox(self.generalGroup)
        self.languageCombox.setObjectName("languageCombox")
        self.languageCombox.addItem("")
        self.languageCombox.addItem("")
        self.formLayout_8.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.languageCombox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_8.setItem(6, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.verticalLayout_6.addWidget(self.generalGroup)
        self.validatorGroup = QtWidgets.QGroupBox(self.generalPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.validatorGroup.sizePolicy().hasHeightForWidth())
        self.validatorGroup.setSizePolicy(sizePolicy)
        self.validatorGroup.setObjectName("validatorGroup")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.validatorGroup)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.visibility5000 = QtWidgets.QCheckBox(self.validatorGroup)
        self.visibility5000.setObjectName("visibility5000")
        self.gridLayout_4.addWidget(self.visibility5000, 0, 0, 1, 1)
        self.cloudHeight450 = QtWidgets.QCheckBox(self.validatorGroup)
        self.cloudHeight450.setObjectName("cloudHeight450")
        self.gridLayout_4.addWidget(self.cloudHeight450, 1, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.validatorGroup)
        self.backupGroup = QtWidgets.QGroupBox(self.generalPage)
        self.backupGroup.setObjectName("backupGroup")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.backupGroup)
        self.gridLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.importPath = QtWidgets.QLineEdit(self.backupGroup)
        self.importPath.setObjectName("importPath")
        self.gridLayout_5.addWidget(self.importPath, 0, 0, 1, 1)
        self.exportButton = QtWidgets.QPushButton(self.backupGroup)
        self.exportButton.setObjectName("exportButton")
        self.gridLayout_5.addWidget(self.exportButton, 1, 2, 1, 1)
        self.importButton = QtWidgets.QPushButton(self.backupGroup)
        self.importButton.setObjectName("importButton")
        self.gridLayout_5.addWidget(self.importButton, 0, 2, 1, 1)
        self.importBrowseButton = QtWidgets.QPushButton(self.backupGroup)
        self.importBrowseButton.setObjectName("importBrowseButton")
        self.gridLayout_5.addWidget(self.importBrowseButton, 0, 1, 1, 1)
        self.exportBrowseButton = QtWidgets.QPushButton(self.backupGroup)
        self.exportBrowseButton.setObjectName("exportBrowseButton")
        self.gridLayout_5.addWidget(self.exportBrowseButton, 1, 1, 1, 1)
        self.exportPath = QtWidgets.QLineEdit(self.backupGroup)
        self.exportPath.setObjectName("exportPath")
        self.gridLayout_5.addWidget(self.exportPath, 1, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.backupGroup)
        self.stackedWidget.addWidget(self.generalPage)
        self.messagePage = QtWidgets.QWidget()
        self.messagePage.setObjectName("messagePage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.messagePage)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.prefixGroup = QtWidgets.QGroupBox(self.messagePage)
        self.prefixGroup.setObjectName("prefixGroup")
        self.formLayout = QtWidgets.QFormLayout(self.prefixGroup)
        self.formLayout.setObjectName("formLayout")
        self.icaoLabel = QtWidgets.QLabel(self.prefixGroup)
        self.icaoLabel.setObjectName("icaoLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.icaoLabel)
        self.icao = QtWidgets.QLineEdit(self.prefixGroup)
        self.icao.setObjectName("icao")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.icao)
        self.areaLabel = QtWidgets.QLabel(self.prefixGroup)
        self.areaLabel.setObjectName("areaLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.areaLabel)
        self.area = QtWidgets.QLineEdit(self.prefixGroup)
        self.area.setObjectName("area")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.area)
        self.firLabel = QtWidgets.QLabel(self.prefixGroup)
        self.firLabel.setObjectName("firLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.firLabel)
        self.fir = QtWidgets.QLineEdit(self.prefixGroup)
        self.fir.setObjectName("fir")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fir)
        self.trendSignLabel = QtWidgets.QLabel(self.prefixGroup)
        self.trendSignLabel.setObjectName("trendSignLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.trendSignLabel)
        self.trendSign = QtWidgets.QLineEdit(self.prefixGroup)
        self.trendSign.setObjectName("trendSign")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.trendSign)
        self.verticalLayout_2.addWidget(self.prefixGroup)
        self.weatherGroup = QtWidgets.QGroupBox(self.messagePage)
        self.weatherGroup.setObjectName("weatherGroup")
        self.gridLayout = QtWidgets.QGridLayout(self.weatherGroup)
        self.gridLayout.setObjectName("gridLayout")
        self.addWeatherLayout = QtWidgets.QHBoxLayout()
        self.addWeatherLayout.setObjectName("addWeatherLayout")
        self.weather = QtWidgets.QLineEdit(self.weatherGroup)
        self.weather.setText("")
        self.weather.setObjectName("weather")
        self.addWeatherLayout.addWidget(self.weather)
        self.addWeatherButton = QtWidgets.QPushButton(self.weatherGroup)
        self.addWeatherButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.addWeatherButton.setObjectName("addWeatherButton")
        self.addWeatherLayout.addWidget(self.addWeatherButton)
        self.delWeatherButton = QtWidgets.QPushButton(self.weatherGroup)
        self.delWeatherButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.delWeatherButton.setObjectName("delWeatherButton")
        self.addWeatherLayout.addWidget(self.delWeatherButton)
        self.gridLayout.addLayout(self.addWeatherLayout, 0, 1, 1, 1)
        self.weatherList = QtWidgets.QListWidget(self.weatherGroup)
        self.weatherList.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.weatherList.setObjectName("weatherList")
        self.gridLayout.addWidget(self.weatherList, 1, 1, 1, 1)
        self.weatherWithIntensityList = QtWidgets.QListWidget(self.weatherGroup)
        self.weatherWithIntensityList.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.weatherWithIntensityList.setObjectName("weatherWithIntensityList")
        self.gridLayout.addWidget(self.weatherWithIntensityList, 1, 0, 1, 1)
        self.addWeatherWithIntensityLayout = QtWidgets.QHBoxLayout()
        self.addWeatherWithIntensityLayout.setObjectName("addWeatherWithIntensityLayout")
        self.weatherWithIntensity = QtWidgets.QLineEdit(self.weatherGroup)
        self.weatherWithIntensity.setObjectName("weatherWithIntensity")
        self.addWeatherWithIntensityLayout.addWidget(self.weatherWithIntensity)
        self.addWeatherWithIntensityButton = QtWidgets.QPushButton(self.weatherGroup)
        self.addWeatherWithIntensityButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.addWeatherWithIntensityButton.setObjectName("addWeatherWithIntensityButton")
        self.addWeatherWithIntensityLayout.addWidget(self.addWeatherWithIntensityButton)
        self.delWeatherWithIntensityButton = QtWidgets.QPushButton(self.weatherGroup)
        self.delWeatherWithIntensityButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.delWeatherWithIntensityButton.setObjectName("delWeatherWithIntensityButton")
        self.addWeatherWithIntensityLayout.addWidget(self.delWeatherWithIntensityButton)
        self.gridLayout.addLayout(self.addWeatherWithIntensityLayout, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.weatherGroup)
        self.stackedWidget.addWidget(self.messagePage)
        self.communicationPage = QtWidgets.QWidget()
        self.communicationPage.setObjectName("communicationPage")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.communicationPage)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.topLayout = QtWidgets.QHBoxLayout()
        self.topLayout.setObjectName("topLayout")
        self.serialGroup = QtWidgets.QGroupBox(self.communicationPage)
        self.serialGroup.setObjectName("serialGroup")
        self.formLayout_3 = QtWidgets.QFormLayout(self.serialGroup)
        self.formLayout_3.setObjectName("formLayout_3")
        self.portLabel = QtWidgets.QLabel(self.serialGroup)
        self.portLabel.setObjectName("portLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.portLabel)
        self.port = QtWidgets.QLineEdit(self.serialGroup)
        self.port.setObjectName("port")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.port)
        self.baudrateLabel = QtWidgets.QLabel(self.serialGroup)
        self.baudrateLabel.setObjectName("baudrateLabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.baudrateLabel)
        self.baudrate = QtWidgets.QLineEdit(self.serialGroup)
        self.baudrate.setObjectName("baudrate")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.baudrate)
        self.parityLabel = QtWidgets.QLabel(self.serialGroup)
        self.parityLabel.setObjectName("parityLabel")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.parityLabel)
        self.parity = QtWidgets.QComboBox(self.serialGroup)
        self.parity.setObjectName("parity")
        self.parity.addItem("")
        self.parity.addItem("")
        self.parity.addItem("")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.parity)
        self.bytesizeLabel = QtWidgets.QLabel(self.serialGroup)
        self.bytesizeLabel.setObjectName("bytesizeLabel")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.bytesizeLabel)
        self.bytesize = QtWidgets.QComboBox(self.serialGroup)
        self.bytesize.setObjectName("bytesize")
        self.bytesize.addItem("")
        self.bytesize.addItem("")
        self.bytesize.addItem("")
        self.bytesize.addItem("")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.bytesize)
        self.stopbitsLabel = QtWidgets.QLabel(self.serialGroup)
        self.stopbitsLabel.setObjectName("stopbitsLabel")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.stopbitsLabel)
        self.stopbits = QtWidgets.QComboBox(self.serialGroup)
        self.stopbits.setObjectName("stopbits")
        self.stopbits.addItem("")
        self.stopbits.addItem("")
        self.stopbits.addItem("")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.stopbits)
        self.topLayout.addWidget(self.serialGroup)
        self.aftnGroup = QtWidgets.QGroupBox(self.communicationPage)
        self.aftnGroup.setMaximumSize(QtCore.QSize(239, 16777215))
        self.aftnGroup.setObjectName("aftnGroup")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.aftnGroup)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.channelLabel = QtWidgets.QLabel(self.aftnGroup)
        self.channelLabel.setObjectName("channelLabel")
        self.gridLayout_3.addWidget(self.channelLabel, 0, 0, 1, 1)
        self.channelSequenceNumber = QtWidgets.QLineEdit(self.aftnGroup)
        self.channelSequenceNumber.setObjectName("channelSequenceNumber")
        self.gridLayout_3.addWidget(self.channelSequenceNumber, 1, 1, 1, 1)
        self.channelSequenceNumberLabel = QtWidgets.QLabel(self.aftnGroup)
        self.channelSequenceNumberLabel.setObjectName("channelSequenceNumberLabel")
        self.gridLayout_3.addWidget(self.channelSequenceNumberLabel, 1, 0, 1, 1)
        self.maxLineChar = QtWidgets.QLineEdit(self.aftnGroup)
        self.maxLineChar.setObjectName("maxLineChar")
        self.gridLayout_3.addWidget(self.maxLineChar, 6, 1, 1, 2)
        self.maxSendAddress = QtWidgets.QLineEdit(self.aftnGroup)
        self.maxSendAddress.setObjectName("maxSendAddress")
        self.gridLayout_3.addWidget(self.maxSendAddress, 5, 1, 1, 2)
        self.originatorAddress = QtWidgets.QLineEdit(self.aftnGroup)
        self.originatorAddress.setObjectName("originatorAddress")
        self.gridLayout_3.addWidget(self.originatorAddress, 4, 1, 1, 2)
        self.originatorAddressLabel = QtWidgets.QLabel(self.aftnGroup)
        self.originatorAddressLabel.setObjectName("originatorAddressLabel")
        self.gridLayout_3.addWidget(self.originatorAddressLabel, 4, 0, 1, 1)
        self.maxLineCharLabel = QtWidgets.QLabel(self.aftnGroup)
        self.maxLineCharLabel.setObjectName("maxLineCharLabel")
        self.gridLayout_3.addWidget(self.maxLineCharLabel, 6, 0, 1, 1)
        self.channel = QtWidgets.QLineEdit(self.aftnGroup)
        self.channel.setObjectName("channel")
        self.gridLayout_3.addWidget(self.channel, 0, 1, 1, 2)
        self.resetNumberButton = QtWidgets.QPushButton(self.aftnGroup)
        self.resetNumberButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.resetNumberButton.setObjectName("resetNumberButton")
        self.gridLayout_3.addWidget(self.resetNumberButton, 1, 2, 1, 1)
        self.maxSendAddressLabel = QtWidgets.QLabel(self.aftnGroup)
        self.maxSendAddressLabel.setObjectName("maxSendAddressLabel")
        self.gridLayout_3.addWidget(self.maxSendAddressLabel, 5, 0, 1, 1)
        self.topLayout.addWidget(self.aftnGroup)
        self.verticalLayout_4.addLayout(self.topLayout)
        self.addressGroup = QtWidgets.QGroupBox(self.communicationPage)
        self.addressGroup.setObjectName("addressGroup")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.addressGroup)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tabWidget = QtWidgets.QTabWidget(self.addressGroup)
        self.tabWidget.setObjectName("tabWidget")
        self.tafTab = QtWidgets.QWidget()
        self.tafTab.setObjectName("tafTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tafTab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tafAddress = QtWidgets.QTextEdit(self.tafTab)
        self.tafAddress.setObjectName("tafAddress")
        self.verticalLayout_3.addWidget(self.tafAddress)
        self.tabWidget.addTab(self.tafTab, "")
        self.sigmetTab = QtWidgets.QWidget()
        self.sigmetTab.setObjectName("sigmetTab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.sigmetTab)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.sigmetAddress = QtWidgets.QTextEdit(self.sigmetTab)
        self.sigmetAddress.setObjectName("sigmetAddress")
        self.verticalLayout_7.addWidget(self.sigmetAddress)
        self.tabWidget.addTab(self.sigmetTab, "")
        self.airmetTab = QtWidgets.QWidget()
        self.airmetTab.setObjectName("airmetTab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.airmetTab)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.airmetAddress = QtWidgets.QTextEdit(self.airmetTab)
        self.airmetAddress.setObjectName("airmetAddress")
        self.verticalLayout_8.addWidget(self.airmetAddress)
        self.tabWidget.addTab(self.airmetTab, "")
        self.trendTab = QtWidgets.QWidget()
        self.trendTab.setObjectName("trendTab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.trendTab)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.trendAddress = QtWidgets.QTextEdit(self.trendTab)
        self.trendAddress.setObjectName("trendAddress")
        self.verticalLayout_9.addWidget(self.trendAddress)
        self.tabWidget.addTab(self.trendTab, "")
        self.verticalLayout_10.addWidget(self.tabWidget)
        self.verticalLayout_4.addWidget(self.addressGroup)
        self.stackedWidget.addWidget(self.communicationPage)
        self.monitorPage = QtWidgets.QWidget()
        self.monitorPage.setObjectName("monitorPage")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.monitorPage)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.dataSourceGroup = QtWidgets.QGroupBox(self.monitorPage)
        self.dataSourceGroup.setObjectName("dataSourceGroup")
        self.formLayout_2 = QtWidgets.QFormLayout(self.dataSourceGroup)
        self.formLayout_2.setObjectName("formLayout_2")
        self.webApiLabel = QtWidgets.QLabel(self.dataSourceGroup)
        self.webApiLabel.setObjectName("webApiLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.webApiLabel)
        self.webApiURL = QtWidgets.QLineEdit(self.dataSourceGroup)
        self.webApiURL.setObjectName("webApiURL")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.webApiURL)
        self.verticalLayout_5.addWidget(self.dataSourceGroup)
        self.warnGroup = QtWidgets.QGroupBox(self.monitorPage)
        self.warnGroup.setObjectName("warnGroup")
        self.formLayout_4 = QtWidgets.QFormLayout(self.warnGroup)
        self.formLayout_4.setObjectName("formLayout_4")
        self.warnTAFTimeLabel = QtWidgets.QLabel(self.warnGroup)
        self.warnTAFTimeLabel.setObjectName("warnTAFTimeLabel")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.warnTAFTimeLabel)
        self.warnTAFTime = QtWidgets.QLineEdit(self.warnGroup)
        self.warnTAFTime.setMaximumSize(QtCore.QSize(120, 16777215))
        self.warnTAFTime.setObjectName("warnTAFTime")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.warnTAFTime)
        self.warnTAFVolumeLabel = QtWidgets.QLabel(self.warnGroup)
        self.warnTAFVolumeLabel.setObjectName("warnTAFVolumeLabel")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.warnTAFVolumeLabel)
        self.warnTAFVolume = QtWidgets.QSlider(self.warnGroup)
        self.warnTAFVolume.setOrientation(QtCore.Qt.Horizontal)
        self.warnTAFVolume.setObjectName("warnTAFVolume")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.warnTAFVolume)
        self.verticalLayout_5.addWidget(self.warnGroup)
        self.remindGroup = QtWidgets.QGroupBox(self.monitorPage)
        self.remindGroup.setObjectName("remindGroup")
        self.formLayout_5 = QtWidgets.QFormLayout(self.remindGroup)
        self.formLayout_5.setObjectName("formLayout_5")
        self.remindTAF = QtWidgets.QCheckBox(self.remindGroup)
        self.remindTAF.setObjectName("remindTAF")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.remindTAF)
        self.remindTAFVolume = QtWidgets.QSlider(self.remindGroup)
        self.remindTAFVolume.setOrientation(QtCore.Qt.Horizontal)
        self.remindTAFVolume.setObjectName("remindTAFVolume")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.remindTAFVolume)
        self.remindTrend = QtWidgets.QCheckBox(self.remindGroup)
        self.remindTrend.setObjectName("remindTrend")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.remindTrend)
        self.remindTrendVolume = QtWidgets.QSlider(self.remindGroup)
        self.remindTrendVolume.setOrientation(QtCore.Qt.Horizontal)
        self.remindTrendVolume.setObjectName("remindTrendVolume")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.remindTrendVolume)
        self.remindSIGMET = QtWidgets.QCheckBox(self.remindGroup)
        self.remindSIGMET.setObjectName("remindSIGMET")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.remindSIGMET)
        self.remindSIGMETVolume = QtWidgets.QSlider(self.remindGroup)
        self.remindSIGMETVolume.setOrientation(QtCore.Qt.Horizontal)
        self.remindSIGMETVolume.setObjectName("remindSIGMETVolume")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.remindSIGMETVolume)
        self.verticalLayout_5.addWidget(self.remindGroup)
        self.callServiceGroup = QtWidgets.QGroupBox(self.monitorPage)
        self.callServiceGroup.setObjectName("callServiceGroup")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.callServiceGroup)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.callServiceURLLabel = QtWidgets.QLabel(self.callServiceGroup)
        self.callServiceURLLabel.setObjectName("callServiceURLLabel")
        self.gridLayout_2.addWidget(self.callServiceURLLabel, 0, 0, 1, 1)
        self.callServiceURL = QtWidgets.QLineEdit(self.callServiceGroup)
        self.callServiceURL.setObjectName("callServiceURL")
        self.gridLayout_2.addWidget(self.callServiceURL, 0, 1, 1, 1)
        self.callServiceTokenLabel = QtWidgets.QLabel(self.callServiceGroup)
        self.callServiceTokenLabel.setObjectName("callServiceTokenLabel")
        self.gridLayout_2.addWidget(self.callServiceTokenLabel, 1, 0, 1, 1)
        self.callUpButton = QtWidgets.QPushButton(self.callServiceGroup)
        self.callUpButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.callUpButton.setObjectName("callUpButton")
        self.gridLayout_2.addWidget(self.callUpButton, 0, 2, 1, 1)
        self.callServiceToken = QtWidgets.QLineEdit(self.callServiceGroup)
        self.callServiceToken.setObjectName("callServiceToken")
        self.gridLayout_2.addWidget(self.callServiceToken, 1, 1, 1, 2)
        self.verticalLayout_5.addWidget(self.callServiceGroup)
        self.stackedWidget.addWidget(self.monitorPage)
        self.contractPage = QtWidgets.QWidget()
        self.contractPage.setObjectName("contractPage")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.contractPage)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.contractGroup = QtWidgets.QGroupBox(self.contractPage)
        self.contractGroup.setObjectName("contractGroup")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.contractGroup)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.addPersonLayout = QtWidgets.QHBoxLayout()
        self.addPersonLayout.setObjectName("addPersonLayout")
        self.personName = QtWidgets.QLineEdit(self.contractGroup)
        self.personName.setText("")
        self.personName.setObjectName("personName")
        self.addPersonLayout.addWidget(self.personName)
        self.personMobile = QtWidgets.QLineEdit(self.contractGroup)
        self.personMobile.setObjectName("personMobile")
        self.addPersonLayout.addWidget(self.personMobile)
        self.addPersonButton = QtWidgets.QPushButton(self.contractGroup)
        self.addPersonButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.addPersonButton.setObjectName("addPersonButton")
        self.addPersonLayout.addWidget(self.addPersonButton)
        self.delPersonButton = QtWidgets.QPushButton(self.contractGroup)
        self.delPersonButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.delPersonButton.setObjectName("delPersonButton")
        self.addPersonLayout.addWidget(self.delPersonButton)
        self.verticalLayout_12.addLayout(self.addPersonLayout)
        self.contractTable = QtWidgets.QTableWidget(self.contractGroup)
        self.contractTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.contractTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.contractTable.setObjectName("contractTable")
        self.contractTable.setColumnCount(2)
        self.contractTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.contractTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.contractTable.setHorizontalHeaderItem(1, item)
        self.contractTable.horizontalHeader().setStretchLastSection(True)
        self.contractTable.verticalHeader().setVisible(False)
        self.verticalLayout_12.addWidget(self.contractTable)
        self.selectedContractLayout = QtWidgets.QHBoxLayout()
        self.selectedContractLayout.setObjectName("selectedContractLayout")
        self.selectedContractLabel = QtWidgets.QLabel(self.contractGroup)
        self.selectedContractLabel.setObjectName("selectedContractLabel")
        self.selectedContractLayout.addWidget(self.selectedContractLabel)
        self.selectedContract = QtWidgets.QComboBox(self.contractGroup)
        self.selectedContract.setObjectName("selectedContract")
        self.selectedContractLayout.addWidget(self.selectedContract)
        self.verticalLayout_12.addLayout(self.selectedContractLayout)
        self.verticalLayout_11.addWidget(self.contractGroup)
        self.stackedWidget.addWidget(self.contractPage)
        self.mainLayout.addWidget(self.stackedWidget)
        self.verticalLayout.addLayout(self.mainLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Setting)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Reset)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Setting)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(1)
        self.buttonBox.accepted.connect(Setting.accept)
        self.buttonBox.rejected.connect(Setting.reject)
        self.menu.currentRowChanged['int'].connect(self.stackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(Setting)
        Setting.setTabOrder(self.menu, self.icao)
        Setting.setTabOrder(self.icao, self.area)
        Setting.setTabOrder(self.area, self.fir)
        Setting.setTabOrder(self.fir, self.trendSign)
        Setting.setTabOrder(self.trendSign, self.weather)
        Setting.setTabOrder(self.weather, self.addWeatherButton)
        Setting.setTabOrder(self.addWeatherButton, self.delWeatherButton)
        Setting.setTabOrder(self.delWeatherButton, self.weatherList)
        Setting.setTabOrder(self.weatherList, self.weatherWithIntensity)
        Setting.setTabOrder(self.weatherWithIntensity, self.addWeatherWithIntensityButton)
        Setting.setTabOrder(self.addWeatherWithIntensityButton, self.delWeatherWithIntensityButton)
        Setting.setTabOrder(self.delWeatherWithIntensityButton, self.port)
        Setting.setTabOrder(self.port, self.baudrate)
        Setting.setTabOrder(self.baudrate, self.parity)
        Setting.setTabOrder(self.parity, self.bytesize)
        Setting.setTabOrder(self.bytesize, self.stopbits)
        Setting.setTabOrder(self.stopbits, self.channel)
        Setting.setTabOrder(self.channel, self.channelSequenceNumber)
        Setting.setTabOrder(self.channelSequenceNumber, self.originatorAddress)
        Setting.setTabOrder(self.originatorAddress, self.tabWidget)
        Setting.setTabOrder(self.tabWidget, self.tafAddress)
        Setting.setTabOrder(self.tafAddress, self.sigmetAddress)
        Setting.setTabOrder(self.sigmetAddress, self.airmetAddress)
        Setting.setTabOrder(self.airmetAddress, self.trendAddress)
        Setting.setTabOrder(self.trendAddress, self.warnTAFVolume)
        Setting.setTabOrder(self.warnTAFVolume, self.remindTAF)
        Setting.setTabOrder(self.remindTAF, self.remindTAFVolume)
        Setting.setTabOrder(self.remindTAFVolume, self.remindTrend)
        Setting.setTabOrder(self.remindTrend, self.remindTrendVolume)
        Setting.setTabOrder(self.remindTrendVolume, self.remindSIGMET)
        Setting.setTabOrder(self.remindSIGMET, self.remindSIGMETVolume)
        Setting.setTabOrder(self.remindSIGMETVolume, self.runOnStart)
        Setting.setTabOrder(self.runOnStart, self.closeToMinimize)
        Setting.setTabOrder(self.closeToMinimize, self.importPath)
        Setting.setTabOrder(self.importPath, self.importBrowseButton)
        Setting.setTabOrder(self.importBrowseButton, self.importButton)
        Setting.setTabOrder(self.importButton, self.exportPath)
        Setting.setTabOrder(self.exportPath, self.exportBrowseButton)
        Setting.setTabOrder(self.exportBrowseButton, self.exportButton)

    def retranslateUi(self, Setting):
        _translate = QtCore.QCoreApplication.translate
        Setting.setWindowTitle(_translate("Setting", "设置"))
        __sortingEnabled = self.menu.isSortingEnabled()
        self.menu.setSortingEnabled(False)
        item = self.menu.item(0)
        item.setText(_translate("Setting", "常规"))
        item = self.menu.item(1)
        item.setText(_translate("Setting", "编报"))
        item = self.menu.item(2)
        item.setText(_translate("Setting", "通信"))
        item = self.menu.item(3)
        item.setText(_translate("Setting", "监控"))
        item = self.menu.item(4)
        item.setText(_translate("Setting", "联系人"))
        self.menu.setSortingEnabled(__sortingEnabled)
        self.generalGroup.setTitle(_translate("Setting", "常规"))
        self.runOnStart.setText(_translate("Setting", "开机自动启动"))
        self.closeToMinimize.setText(_translate("Setting", "关闭时最小化到系统托盘"))
        self.debugMode.setText(_translate("Setting", "启用调试模式"))
        self.alwaysShowEditor.setText(_translate("Setting", "总是显示报文编辑器"))
        self.label.setText(_translate("Setting", "语言"))
        self.languageCombox.setItemText(0, _translate("Setting", "简体中文"))
        self.languageCombox.setItemText(1, _translate("Setting", "English"))
        self.validatorGroup.setTitle(_translate("Setting", "校验"))
        self.visibility5000.setText(_translate("Setting", "能见度 5000 米"))
        self.cloudHeight450.setText(_translate("Setting", "云高 450 米"))
        self.backupGroup.setTitle(_translate("Setting", "备份"))
        self.importPath.setPlaceholderText(_translate("Setting", "PATH"))
        self.exportButton.setText(_translate("Setting", "导出"))
        self.importButton.setText(_translate("Setting", "导入"))
        self.importBrowseButton.setText(_translate("Setting", "浏览"))
        self.exportBrowseButton.setText(_translate("Setting", "浏览"))
        self.exportPath.setPlaceholderText(_translate("Setting", "PATH"))
        self.prefixGroup.setTitle(_translate("Setting", "前缀"))
        self.icaoLabel.setText(_translate("Setting", "机场代码    "))
        self.icao.setPlaceholderText(_translate("Setting", "ZJHK"))
        self.areaLabel.setText(_translate("Setting", "情报区域    "))
        self.area.setPlaceholderText(_translate("Setting", "CI35"))
        self.firLabel.setText(_translate("Setting", "监视台责任区"))
        self.fir.setPlaceholderText(_translate("Setting", "ZJSA SANYA FIR"))
        self.trendSignLabel.setText(_translate("Setting", "趋势识别码  "))
        self.trendSign.setPlaceholderText(_translate("Setting", "TREND"))
        self.weatherGroup.setTitle(_translate("Setting", "天气现象备案"))
        self.weather.setPlaceholderText(_translate("Setting", "无强度变化的天气现象"))
        self.addWeatherButton.setText(_translate("Setting", "+"))
        self.delWeatherButton.setText(_translate("Setting", "—"))
        self.weatherWithIntensity.setPlaceholderText(_translate("Setting", "有强度变化的天气现象"))
        self.addWeatherWithIntensityButton.setText(_translate("Setting", "+"))
        self.delWeatherWithIntensityButton.setText(_translate("Setting", "—"))
        self.serialGroup.setTitle(_translate("Setting", "串口参数"))
        self.portLabel.setText(_translate("Setting", "端口  "))
        self.port.setPlaceholderText(_translate("Setting", "COM1"))
        self.baudrateLabel.setText(_translate("Setting", "波特率"))
        self.baudrate.setPlaceholderText(_translate("Setting", "9600"))
        self.parityLabel.setText(_translate("Setting", "校验位"))
        self.parity.setItemText(0, _translate("Setting", "NONE"))
        self.parity.setItemText(1, _translate("Setting", "EVEN"))
        self.parity.setItemText(2, _translate("Setting", "ODD"))
        self.bytesizeLabel.setText(_translate("Setting", "数据位"))
        self.bytesize.setItemText(0, _translate("Setting", "5"))
        self.bytesize.setItemText(1, _translate("Setting", "6"))
        self.bytesize.setItemText(2, _translate("Setting", "7"))
        self.bytesize.setItemText(3, _translate("Setting", "8"))
        self.stopbitsLabel.setText(_translate("Setting", "停止位"))
        self.stopbits.setItemText(0, _translate("Setting", "1"))
        self.stopbits.setItemText(1, _translate("Setting", "1.5"))
        self.stopbits.setItemText(2, _translate("Setting", "2"))
        self.aftnGroup.setTitle(_translate("Setting", "AFTN 参数"))
        self.channelLabel.setText(_translate("Setting", "线路冠字"))
        self.channelSequenceNumber.setPlaceholderText(_translate("Setting", "1"))
        self.channelSequenceNumberLabel.setText(_translate("Setting", "流水号  "))
        self.maxLineChar.setPlaceholderText(_translate("Setting", "69"))
        self.maxSendAddress.setPlaceholderText(_translate("Setting", "21"))
        self.originatorAddress.setPlaceholderText(_translate("Setting", "ZJHKYMYX"))
        self.originatorAddressLabel.setText(_translate("Setting", "用户单位"))
        self.maxLineCharLabel.setText(_translate("Setting", "行字符上限"))
        self.channel.setPlaceholderText(_translate("Setting", "YMA"))
        self.resetNumberButton.setText(_translate("Setting", "复位"))
        self.maxSendAddressLabel.setText(_translate("Setting", "地址上限"))
        self.addressGroup.setTitle(_translate("Setting", "发报地址"))
        self.tafAddress.setPlaceholderText(_translate("Setting", "发报地址请以空格分隔"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tafTab), _translate("Setting", "TAF"))
        self.sigmetAddress.setPlaceholderText(_translate("Setting", "发报地址请以空格分隔"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sigmetTab), _translate("Setting", "SIGMET"))
        self.airmetAddress.setPlaceholderText(_translate("Setting", "发报地址请以空格分隔"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.airmetTab), _translate("Setting", "AIRMET"))
        self.trendAddress.setPlaceholderText(_translate("Setting", "发报地址请以空格分隔"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.trendTab), _translate("Setting", "TREND"))
        self.dataSourceGroup.setTitle(_translate("Setting", "数据源"))
        self.webApiLabel.setText(_translate("Setting", "请求地址        "))
        self.webApiURL.setPlaceholderText(_translate("Setting", "URL"))
        self.warnGroup.setTitle(_translate("Setting", "迟发监控"))
        self.warnTAFTimeLabel.setText(_translate("Setting", "告警时间        "))
        self.warnTAFTime.setPlaceholderText(_translate("Setting", "单位分钟"))
        self.warnTAFVolumeLabel.setText(_translate("Setting", "告警声音        "))
        self.remindGroup.setTitle(_translate("Setting", "声音提醒和音量"))
        self.remindTAF.setText(_translate("Setting", "预报        "))
        self.remindTrend.setText(_translate("Setting", "趋势        "))
        self.remindSIGMET.setText(_translate("Setting", "重要气象情报"))
        self.callServiceGroup.setTitle(_translate("Setting", "电话服务"))
        self.callServiceURLLabel.setText(_translate("Setting", "请求地址        "))
        self.callServiceURL.setPlaceholderText(_translate("Setting", "URL"))
        self.callServiceTokenLabel.setText(_translate("Setting", "认证            "))
        self.callUpButton.setText(_translate("Setting", "拨号"))
        self.callServiceToken.setPlaceholderText(_translate("Setting", "TOKEN"))
        self.contractGroup.setTitle(_translate("Setting", "联系人"))
        self.personName.setPlaceholderText(_translate("Setting", "姓名"))
        self.personMobile.setPlaceholderText(_translate("Setting", "电话"))
        self.addPersonButton.setText(_translate("Setting", "+"))
        self.delPersonButton.setText(_translate("Setting", "—"))
        item = self.contractTable.horizontalHeaderItem(0)
        item.setText(_translate("Setting", "姓名"))
        item = self.contractTable.horizontalHeaderItem(1)
        item.setText(_translate("Setting", "电话"))
        self.selectedContractLabel.setText(_translate("Setting", "当前告警联系人"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Setting = QtWidgets.QDialog()
    ui = Ui_Setting()
    ui.setupUi(Setting)
    Setting.show()
    sys.exit(app.exec_())

