# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Work\tafor\tafor\components\ui\sigmet_general.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Editor(object):
    def setupUi(self, Editor):
        Editor.setObjectName("Editor")
        Editor.resize(500, 550)
        Editor.setWindowTitle("Sigmet")
        self.verticalLayout = QtWidgets.QVBoxLayout(Editor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.descriptionGroup = QtWidgets.QGroupBox(Editor)
        self.descriptionGroup.setObjectName("descriptionGroup")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.descriptionGroup)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.speed = QtWidgets.QLineEdit(self.descriptionGroup)
        self.speed.setObjectName("speed")
        self.gridLayout_2.addWidget(self.speed, 1, 1, 1, 1)
        self.movement = QtWidgets.QComboBox(self.descriptionGroup)
        self.movement.setObjectName("movement")
        self.movement.addItem("")
        self.movement.setItemText(0, "N")
        self.movement.addItem("")
        self.movement.setItemText(1, "NE")
        self.movement.addItem("")
        self.movement.setItemText(2, "E")
        self.movement.addItem("")
        self.movement.setItemText(3, "SE")
        self.movement.addItem("")
        self.movement.setItemText(4, "S")
        self.movement.addItem("")
        self.movement.setItemText(5, "SW")
        self.movement.addItem("")
        self.movement.setItemText(6, "W")
        self.movement.addItem("")
        self.movement.setItemText(7, "NW")
        self.movement.addItem("")
        self.movement.setItemText(8, "STNR")
        self.gridLayout_2.addWidget(self.movement, 1, 0, 1, 1)
        self.top = QtWidgets.QLineEdit(self.descriptionGroup)
        self.top.setObjectName("top")
        self.gridLayout_2.addWidget(self.top, 1, 4, 1, 1)
        self.movementLabel = QtWidgets.QLabel(self.descriptionGroup)
        self.movementLabel.setObjectName("movementLabel")
        self.gridLayout_2.addWidget(self.movementLabel, 0, 0, 1, 1)
        self.speedLabel = QtWidgets.QLabel(self.descriptionGroup)
        self.speedLabel.setObjectName("speedLabel")
        self.gridLayout_2.addWidget(self.speedLabel, 0, 1, 1, 1)
        self.positionLabel = QtWidgets.QLabel(self.descriptionGroup)
        self.positionLabel.setObjectName("positionLabel")
        self.gridLayout_2.addWidget(self.positionLabel, 0, 2, 1, 1)
        self.intensityChangeLabel = QtWidgets.QLabel(self.descriptionGroup)
        self.intensityChangeLabel.setObjectName("intensityChangeLabel")
        self.gridLayout_2.addWidget(self.intensityChangeLabel, 0, 5, 1, 1)
        self.intensityChange = QtWidgets.QComboBox(self.descriptionGroup)
        self.intensityChange.setObjectName("intensityChange")
        self.intensityChange.addItem("")
        self.intensityChange.setItemText(0, "NC")
        self.intensityChange.addItem("")
        self.intensityChange.setItemText(1, "INTSF")
        self.intensityChange.addItem("")
        self.intensityChange.setItemText(2, "WKN")
        self.gridLayout_2.addWidget(self.intensityChange, 1, 5, 1, 1)
        self.base = QtWidgets.QLineEdit(self.descriptionGroup)
        self.base.setObjectName("base")
        self.gridLayout_2.addWidget(self.base, 1, 3, 1, 1)
        self.position = QtWidgets.QComboBox(self.descriptionGroup)
        self.position.setObjectName("position")
        self.position.addItem("")
        self.position.setItemText(0, "")
        self.position.addItem("")
        self.position.setItemText(1, "TOP")
        self.position.addItem("")
        self.position.setItemText(2, "ABV")
        self.position.addItem("")
        self.position.setItemText(3, "BLW")
        self.gridLayout_2.addWidget(self.position, 1, 2, 1, 1)
        self.baseLabel = QtWidgets.QLabel(self.descriptionGroup)
        self.baseLabel.setObjectName("baseLabel")
        self.gridLayout_2.addWidget(self.baseLabel, 0, 3, 1, 1)
        self.topLabel = QtWidgets.QLabel(self.descriptionGroup)
        self.topLabel.setObjectName("topLabel")
        self.gridLayout_2.addWidget(self.topLabel, 0, 4, 1, 1)
        self.verticalLayout.addWidget(self.descriptionGroup)
        self.areaGroup = QtWidgets.QGroupBox(Editor)
        self.areaGroup.setObjectName("areaGroup")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.areaGroup)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.changeAreaWidget = QtWidgets.QWidget(self.areaGroup)
        self.changeAreaWidget.setObjectName("changeAreaWidget")
        self.changeAreaLayout = QtWidgets.QHBoxLayout(self.changeAreaWidget)
        self.changeAreaLayout.setContentsMargins(0, 0, 0, 0)
        self.changeAreaLayout.setObjectName("changeAreaLayout")
        self.latitudeAndLongitude = QtWidgets.QRadioButton(self.changeAreaWidget)
        self.latitudeAndLongitude.setChecked(True)
        self.latitudeAndLongitude.setObjectName("latitudeAndLongitude")
        self.changeAreaLayout.addWidget(self.latitudeAndLongitude)
        self.line = QtWidgets.QRadioButton(self.changeAreaWidget)
        self.line.setObjectName("line")
        self.changeAreaLayout.addWidget(self.line)
        self.points = QtWidgets.QRadioButton(self.changeAreaWidget)
        self.points.setObjectName("points")
        self.changeAreaLayout.addWidget(self.points)
        self.local = QtWidgets.QRadioButton(self.changeAreaWidget)
        self.local.setObjectName("local")
        self.changeAreaLayout.addWidget(self.local)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.changeAreaLayout.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.changeAreaWidget)
        self.latitudeAndLongitudeWidget = QtWidgets.QWidget(self.areaGroup)
        self.latitudeAndLongitudeWidget.setObjectName("latitudeAndLongitudeWidget")
        self.latitudeAndLongitudeLayout = QtWidgets.QGridLayout(self.latitudeAndLongitudeWidget)
        self.latitudeAndLongitudeLayout.setContentsMargins(0, 0, 0, 0)
        self.latitudeAndLongitudeLayout.setObjectName("latitudeAndLongitudeLayout")
        self.longtitudeLabel = QtWidgets.QLabel(self.latitudeAndLongitudeWidget)
        self.longtitudeLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.longtitudeLabel.setObjectName("longtitudeLabel")
        self.latitudeAndLongitudeLayout.addWidget(self.longtitudeLabel, 5, 0, 1, 1)
        self.westLabel = QtWidgets.QLabel(self.latitudeAndLongitudeWidget)
        self.westLabel.setObjectName("westLabel")
        self.latitudeAndLongitudeLayout.addWidget(self.westLabel, 4, 2, 1, 1)
        self.west = QtWidgets.QLineEdit(self.latitudeAndLongitudeWidget)
        self.west.setObjectName("west")
        self.latitudeAndLongitudeLayout.addWidget(self.west, 5, 2, 1, 1)
        self.north = QtWidgets.QLineEdit(self.latitudeAndLongitudeWidget)
        self.north.setObjectName("north")
        self.latitudeAndLongitudeLayout.addWidget(self.north, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.latitudeAndLongitudeLayout.addItem(spacerItem1, 1, 3, 1, 1)
        self.east = QtWidgets.QLineEdit(self.latitudeAndLongitudeWidget)
        self.east.setObjectName("east")
        self.latitudeAndLongitudeLayout.addWidget(self.east, 5, 1, 1, 1)
        self.southLabel = QtWidgets.QLabel(self.latitudeAndLongitudeWidget)
        self.southLabel.setObjectName("southLabel")
        self.latitudeAndLongitudeLayout.addWidget(self.southLabel, 0, 2, 1, 1)
        self.south = QtWidgets.QLineEdit(self.latitudeAndLongitudeWidget)
        self.south.setObjectName("south")
        self.latitudeAndLongitudeLayout.addWidget(self.south, 1, 2, 1, 1)
        self.northLabel = QtWidgets.QLabel(self.latitudeAndLongitudeWidget)
        self.northLabel.setObjectName("northLabel")
        self.latitudeAndLongitudeLayout.addWidget(self.northLabel, 0, 1, 1, 1)
        self.latitudeLabel = QtWidgets.QLabel(self.latitudeAndLongitudeWidget)
        self.latitudeLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.latitudeLabel.setObjectName("latitudeLabel")
        self.latitudeAndLongitudeLayout.addWidget(self.latitudeLabel, 1, 0, 1, 1)
        self.eastLabel = QtWidgets.QLabel(self.latitudeAndLongitudeWidget)
        self.eastLabel.setObjectName("eastLabel")
        self.latitudeAndLongitudeLayout.addWidget(self.eastLabel, 4, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.latitudeAndLongitudeWidget)
        self.lineWidget = QtWidgets.QWidget(self.areaGroup)
        self.lineWidget.setObjectName("lineWidget")
        self.lineLayout = QtWidgets.QGridLayout(self.lineWidget)
        self.lineLayout.setContentsMargins(0, 0, 0, 0)
        self.lineLayout.setObjectName("lineLayout")
        self.lineLongitude1 = QtWidgets.QLineEdit(self.lineWidget)
        self.lineLongitude1.setObjectName("lineLongitude1")
        self.lineLayout.addWidget(self.lineLongitude1, 2, 2, 1, 1)
        self.lineLatitude1 = QtWidgets.QLineEdit(self.lineWidget)
        self.lineLatitude1.setObjectName("lineLatitude1")
        self.lineLayout.addWidget(self.lineLatitude1, 2, 1, 1, 1)
        self.lineLongitudeLabel = QtWidgets.QLabel(self.lineWidget)
        self.lineLongitudeLabel.setObjectName("lineLongitudeLabel")
        self.lineLayout.addWidget(self.lineLongitudeLabel, 1, 2, 1, 1)
        self.lineLabel1 = QtWidgets.QLabel(self.lineWidget)
        self.lineLabel1.setMinimumSize(QtCore.QSize(100, 0))
        self.lineLabel1.setObjectName("lineLabel1")
        self.lineLayout.addWidget(self.lineLabel1, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.lineLayout.addItem(spacerItem2, 2, 3, 1, 1)
        self.lineLatitudeLabel = QtWidgets.QLabel(self.lineWidget)
        self.lineLatitudeLabel.setObjectName("lineLatitudeLabel")
        self.lineLayout.addWidget(self.lineLatitudeLabel, 1, 1, 1, 1)
        self.lineLatitude2 = QtWidgets.QLineEdit(self.lineWidget)
        self.lineLatitude2.setObjectName("lineLatitude2")
        self.lineLayout.addWidget(self.lineLatitude2, 3, 1, 1, 1)
        self.lineLongitude2 = QtWidgets.QLineEdit(self.lineWidget)
        self.lineLongitude2.setObjectName("lineLongitude2")
        self.lineLayout.addWidget(self.lineLongitude2, 3, 2, 1, 1)
        self.lineDirection1 = QtWidgets.QComboBox(self.lineWidget)
        self.lineDirection1.setObjectName("lineDirection1")
        self.lineDirection1.addItem("")
        self.lineDirection1.setItemText(0, "N")
        self.lineDirection1.addItem("")
        self.lineDirection1.setItemText(1, "NE")
        self.lineDirection1.addItem("")
        self.lineDirection1.setItemText(2, "E")
        self.lineDirection1.addItem("")
        self.lineDirection1.setItemText(3, "SE")
        self.lineDirection1.addItem("")
        self.lineDirection1.setItemText(4, "S")
        self.lineDirection1.addItem("")
        self.lineDirection1.setItemText(5, "SW")
        self.lineDirection1.addItem("")
        self.lineDirection1.setItemText(6, "W")
        self.lineDirection1.addItem("")
        self.lineDirection1.setItemText(7, "NW")
        self.lineLayout.addWidget(self.lineDirection1, 3, 3, 1, 1)
        self.lineLongitude4 = QtWidgets.QLineEdit(self.lineWidget)
        self.lineLongitude4.setObjectName("lineLongitude4")
        self.lineLayout.addWidget(self.lineLongitude4, 5, 2, 1, 1)
        self.lineLatitude3 = QtWidgets.QLineEdit(self.lineWidget)
        self.lineLatitude3.setObjectName("lineLatitude3")
        self.lineLayout.addWidget(self.lineLatitude3, 4, 1, 1, 1)
        self.lineLabel2 = QtWidgets.QLabel(self.lineWidget)
        self.lineLabel2.setMinimumSize(QtCore.QSize(100, 0))
        self.lineLabel2.setObjectName("lineLabel2")
        self.lineLayout.addWidget(self.lineLabel2, 4, 0, 1, 1)
        self.lineLongitude3 = QtWidgets.QLineEdit(self.lineWidget)
        self.lineLongitude3.setObjectName("lineLongitude3")
        self.lineLayout.addWidget(self.lineLongitude3, 4, 2, 1, 1)
        self.lineLatitude4 = QtWidgets.QLineEdit(self.lineWidget)
        self.lineLatitude4.setObjectName("lineLatitude4")
        self.lineLayout.addWidget(self.lineLatitude4, 5, 1, 1, 1)
        self.lineDirection2 = QtWidgets.QComboBox(self.lineWidget)
        self.lineDirection2.setObjectName("lineDirection2")
        self.lineDirection2.addItem("")
        self.lineDirection2.setItemText(0, "N")
        self.lineDirection2.addItem("")
        self.lineDirection2.setItemText(1, "NE")
        self.lineDirection2.addItem("")
        self.lineDirection2.setItemText(2, "E")
        self.lineDirection2.addItem("")
        self.lineDirection2.setItemText(3, "SE")
        self.lineDirection2.addItem("")
        self.lineDirection2.setItemText(4, "S")
        self.lineDirection2.addItem("")
        self.lineDirection2.setItemText(5, "SW")
        self.lineDirection2.addItem("")
        self.lineDirection2.setItemText(6, "W")
        self.lineDirection2.addItem("")
        self.lineDirection2.setItemText(7, "NW")
        self.lineLayout.addWidget(self.lineDirection2, 5, 3, 1, 1)
        self.lineDirectionLabel = QtWidgets.QLabel(self.lineWidget)
        self.lineDirectionLabel.setObjectName("lineDirectionLabel")
        self.lineLayout.addWidget(self.lineDirectionLabel, 1, 3, 1, 1)
        self.verticalLayout_2.addWidget(self.lineWidget)
        self.pointsWidget = QtWidgets.QWidget(self.areaGroup)
        self.pointsWidget.setObjectName("pointsWidget")
        self.pointsLayout = QtWidgets.QGridLayout(self.pointsWidget)
        self.pointsLayout.setContentsMargins(0, 0, 0, 0)
        self.pointsLayout.setObjectName("pointsLayout")
        self.pointsLabel = QtWidgets.QLabel(self.pointsWidget)
        self.pointsLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.pointsLabel.setObjectName("pointsLabel")
        self.pointsLayout.addWidget(self.pointsLabel, 1, 0, 1, 1)
        self.pointsLongitude2 = QtWidgets.QLineEdit(self.pointsWidget)
        self.pointsLongitude2.setObjectName("pointsLongitude2")
        self.pointsLayout.addWidget(self.pointsLongitude2, 2, 2, 1, 1)
        self.pointsLatitude3 = QtWidgets.QLineEdit(self.pointsWidget)
        self.pointsLatitude3.setObjectName("pointsLatitude3")
        self.pointsLayout.addWidget(self.pointsLatitude3, 3, 1, 1, 1)
        self.pointsLatitude4 = QtWidgets.QLineEdit(self.pointsWidget)
        self.pointsLatitude4.setObjectName("pointsLatitude4")
        self.pointsLayout.addWidget(self.pointsLatitude4, 4, 1, 1, 1)
        self.pointsLongitude4 = QtWidgets.QLineEdit(self.pointsWidget)
        self.pointsLongitude4.setObjectName("pointsLongitude4")
        self.pointsLayout.addWidget(self.pointsLongitude4, 4, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.pointsLayout.addItem(spacerItem3, 1, 3, 1, 1)
        self.pointsLongitude3 = QtWidgets.QLineEdit(self.pointsWidget)
        self.pointsLongitude3.setObjectName("pointsLongitude3")
        self.pointsLayout.addWidget(self.pointsLongitude3, 3, 2, 1, 1)
        self.pointsLatitudeLabel = QtWidgets.QLabel(self.pointsWidget)
        self.pointsLatitudeLabel.setObjectName("pointsLatitudeLabel")
        self.pointsLayout.addWidget(self.pointsLatitudeLabel, 0, 1, 1, 1)
        self.pointsLongitude1 = QtWidgets.QLineEdit(self.pointsWidget)
        self.pointsLongitude1.setObjectName("pointsLongitude1")
        self.pointsLayout.addWidget(self.pointsLongitude1, 1, 2, 1, 1)
        self.pointsLatitude2 = QtWidgets.QLineEdit(self.pointsWidget)
        self.pointsLatitude2.setObjectName("pointsLatitude2")
        self.pointsLayout.addWidget(self.pointsLatitude2, 2, 1, 1, 1)
        self.pointsLongitudeLabel = QtWidgets.QLabel(self.pointsWidget)
        self.pointsLongitudeLabel.setObjectName("pointsLongitudeLabel")
        self.pointsLayout.addWidget(self.pointsLongitudeLabel, 0, 2, 1, 1)
        self.pointsLatitude1 = QtWidgets.QLineEdit(self.pointsWidget)
        self.pointsLatitude1.setObjectName("pointsLatitude1")
        self.pointsLayout.addWidget(self.pointsLatitude1, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.pointsWidget)
        self.verticalLayout.addWidget(self.areaGroup)
        self.movementLabel.setBuddy(self.movement)
        self.speedLabel.setBuddy(self.speed)
        self.positionLabel.setBuddy(self.position)
        self.intensityChangeLabel.setBuddy(self.intensityChange)
        self.baseLabel.setBuddy(self.base)
        self.topLabel.setBuddy(self.top)
        self.westLabel.setBuddy(self.west)
        self.southLabel.setBuddy(self.south)
        self.northLabel.setBuddy(self.north)
        self.eastLabel.setBuddy(self.east)

        self.retranslateUi(Editor)
        QtCore.QMetaObject.connectSlotsByName(Editor)
        Editor.setTabOrder(self.movement, self.speed)
        Editor.setTabOrder(self.speed, self.position)
        Editor.setTabOrder(self.position, self.base)
        Editor.setTabOrder(self.base, self.top)
        Editor.setTabOrder(self.top, self.intensityChange)
        Editor.setTabOrder(self.intensityChange, self.latitudeAndLongitude)
        Editor.setTabOrder(self.latitudeAndLongitude, self.line)
        Editor.setTabOrder(self.line, self.points)
        Editor.setTabOrder(self.points, self.local)
        Editor.setTabOrder(self.local, self.north)
        Editor.setTabOrder(self.north, self.south)
        Editor.setTabOrder(self.south, self.east)
        Editor.setTabOrder(self.east, self.west)
        Editor.setTabOrder(self.west, self.lineLatitude1)
        Editor.setTabOrder(self.lineLatitude1, self.lineLongitude1)
        Editor.setTabOrder(self.lineLongitude1, self.lineLatitude2)
        Editor.setTabOrder(self.lineLatitude2, self.lineLongitude2)
        Editor.setTabOrder(self.lineLongitude2, self.lineDirection1)
        Editor.setTabOrder(self.lineDirection1, self.lineLatitude3)
        Editor.setTabOrder(self.lineLatitude3, self.lineLongitude3)
        Editor.setTabOrder(self.lineLongitude3, self.lineLatitude4)
        Editor.setTabOrder(self.lineLatitude4, self.lineLongitude4)
        Editor.setTabOrder(self.lineLongitude4, self.lineDirection2)
        Editor.setTabOrder(self.lineDirection2, self.pointsLatitude1)
        Editor.setTabOrder(self.pointsLatitude1, self.pointsLongitude1)
        Editor.setTabOrder(self.pointsLongitude1, self.pointsLatitude2)
        Editor.setTabOrder(self.pointsLatitude2, self.pointsLongitude2)
        Editor.setTabOrder(self.pointsLongitude2, self.pointsLatitude3)
        Editor.setTabOrder(self.pointsLatitude3, self.pointsLongitude3)
        Editor.setTabOrder(self.pointsLongitude3, self.pointsLatitude4)
        Editor.setTabOrder(self.pointsLatitude4, self.pointsLongitude4)

    def retranslateUi(self, Editor):
        _translate = QtCore.QCoreApplication.translate
        self.descriptionGroup.setTitle(_translate("Editor", "Description"))
        self.movementLabel.setText(_translate("Editor", "Movement"))
        self.speedLabel.setText(_translate("Editor", "Speed"))
        self.positionLabel.setText(_translate("Editor", "Position"))
        self.intensityChangeLabel.setText(_translate("Editor", "Intensity Change"))
        self.baseLabel.setText(_translate("Editor", "FL Base"))
        self.topLabel.setText(_translate("Editor", "FL Top"))
        self.areaGroup.setTitle(_translate("Editor", "Area"))
        self.latitudeAndLongitude.setText(_translate("Editor", "Latitude and Longitude"))
        self.line.setText(_translate("Editor", "Line"))
        self.points.setText(_translate("Editor", "Points"))
        self.local.setText(_translate("Editor", "Local"))
        self.longtitudeLabel.setText(_translate("Editor", "Longitude"))
        self.westLabel.setText(_translate("Editor", "W OF"))
        self.southLabel.setText(_translate("Editor", "S OF"))
        self.northLabel.setText(_translate("Editor", "N OF"))
        self.latitudeLabel.setText(_translate("Editor", "Latitude"))
        self.eastLabel.setText(_translate("Editor", "E OF"))
        self.lineLongitudeLabel.setText(_translate("Editor", "Longitude"))
        self.lineLabel1.setText(_translate("Editor", "Line"))
        self.lineLatitudeLabel.setText(_translate("Editor", "Latitude"))
        self.lineLabel2.setText(_translate("Editor", "Line"))
        self.lineDirectionLabel.setText(_translate("Editor", "Direction"))
        self.pointsLabel.setText(_translate("Editor", "Points"))
        self.pointsLatitudeLabel.setText(_translate("Editor", "Latitude"))
        self.pointsLongitudeLabel.setText(_translate("Editor", "Longitude"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Editor = QtWidgets.QWidget()
    ui = Ui_Editor()
    ui.setupUi(Editor)
    Editor.show()
    sys.exit(app.exec_())

