# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Work\tafor\tafor\components\ui\sigmet_custom.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Editor(object):
    def setupUi(self, Editor):
        Editor.setObjectName("Editor")
        Editor.resize(620, 222)
        Editor.setWindowTitle("Sigmet")
        self.verticalLayout = QtWidgets.QVBoxLayout(Editor)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headingGroup = QtWidgets.QGroupBox(Editor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.headingGroup.sizePolicy().hasHeightForWidth())
        self.headingGroup.setSizePolicy(sizePolicy)
        self.headingGroup.setObjectName("headingGroup")
        self.gridLayout_1 = QtWidgets.QGridLayout(self.headingGroup)
        self.gridLayout_1.setObjectName("gridLayout_1")
        self.beginningTimeLabel = QtWidgets.QLabel(self.headingGroup)
        self.beginningTimeLabel.setObjectName("beginningTimeLabel")
        self.gridLayout_1.addWidget(self.beginningTimeLabel, 0, 0, 1, 1)
        self.endingTime = QtWidgets.QLineEdit(self.headingGroup)
        self.endingTime.setObjectName("endingTime")
        self.gridLayout_1.addWidget(self.endingTime, 1, 1, 1, 1)
        self.endingTimeLabel = QtWidgets.QLabel(self.headingGroup)
        self.endingTimeLabel.setObjectName("endingTimeLabel")
        self.gridLayout_1.addWidget(self.endingTimeLabel, 0, 1, 1, 1)
        self.beginningTime = QtWidgets.QLineEdit(self.headingGroup)
        self.beginningTime.setObjectName("beginningTime")
        self.gridLayout_1.addWidget(self.beginningTime, 1, 0, 1, 1)
        self.sequenceLabel = QtWidgets.QLabel(self.headingGroup)
        self.sequenceLabel.setObjectName("sequenceLabel")
        self.gridLayout_1.addWidget(self.sequenceLabel, 0, 2, 1, 1)
        self.sequence = QtWidgets.QLineEdit(self.headingGroup)
        self.sequence.setObjectName("sequence")
        self.gridLayout_1.addWidget(self.sequence, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.headingGroup)
        self.textGroup = QtWidgets.QGroupBox(Editor)
        self.textGroup.setObjectName("textGroup")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.textGroup)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.text = QtWidgets.QTextEdit(self.textGroup)
        self.text.setMinimumSize(QtCore.QSize(575, 0))
        self.text.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>")
        self.text.setAcceptRichText(False)
        self.text.setObjectName("text")
        self.verticalLayout_2.addWidget(self.text)
        self.verticalLayout.addWidget(self.textGroup)
        self.beginningTimeLabel.setBuddy(self.beginningTime)
        self.endingTimeLabel.setBuddy(self.endingTime)
        self.sequenceLabel.setBuddy(self.sequence)

        self.retranslateUi(Editor)
        QtCore.QMetaObject.connectSlotsByName(Editor)
        Editor.setTabOrder(self.beginningTime, self.endingTime)
        Editor.setTabOrder(self.endingTime, self.sequence)
        Editor.setTabOrder(self.sequence, self.text)

    def retranslateUi(self, Editor):
        _translate = QtCore.QCoreApplication.translate
        self.headingGroup.setTitle(_translate("Editor", "Heading"))
        self.beginningTimeLabel.setText(_translate("Editor", "Beginning"))
        self.endingTimeLabel.setText(_translate("Editor", "Ending"))
        self.sequenceLabel.setText(_translate("Editor", "Sequence"))
        self.textGroup.setTitle(_translate("Editor", "Text"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Editor = QtWidgets.QWidget()
    ui = Ui_Editor()
    ui.setupUi(Editor)
    Editor.show()
    sys.exit(app.exec_())
