# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Chen\Work\tafor\tafor\components\ui\setting.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(620, 408)
        Settings.setAcceptDrops(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Settings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainLayout = QtWidgets.QHBoxLayout()
        self.mainLayout.setObjectName("mainLayout")
        self.leftLayout = QtWidgets.QWidget(Settings)
        self.leftLayout.setMaximumSize(QtCore.QSize(120, 16777215))
        self.leftLayout.setObjectName("leftLayout")
        self.leftbox = QtWidgets.QVBoxLayout(self.leftLayout)
        self.leftbox.setContentsMargins(0, 0, 0, 0)
        self.leftbox.setObjectName("leftbox")
        self.menu = QtWidgets.QListWidget(self.leftLayout)
        self.menu.setObjectName("menu")
        item = QtWidgets.QListWidgetItem()
        self.menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menu.addItem(item)
        self.leftbox.addWidget(self.menu)
        self.mainLayout.addWidget(self.leftLayout)
        self.stackedWidget = QtWidgets.QStackedWidget(Settings)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setObjectName("stackedWidget")
        self.generalPage = QtWidgets.QWidget()
        self.generalPage.setObjectName("generalPage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.generalPage)
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.generalGroup = QtWidgets.QGroupBox(self.generalPage)
        self.generalGroup.setObjectName("generalGroup")
        self.formLayout_8 = QtWidgets.QFormLayout(self.generalGroup)
        self.formLayout_8.setObjectName("formLayout_8")
        self.runOnStart = QtWidgets.QCheckBox(self.generalGroup)
        self.runOnStart.setObjectName("runOnStart")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.runOnStart)
        self.closeToMinimize = QtWidgets.QCheckBox(self.generalGroup)
        self.closeToMinimize.setObjectName("closeToMinimize")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.closeToMinimize)
        self.debugMode = QtWidgets.QCheckBox(self.generalGroup)
        self.debugMode.setObjectName("debugMode")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.debugMode)
        self.alwaysShowEditor = QtWidgets.QCheckBox(self.generalGroup)
        self.alwaysShowEditor.setObjectName("alwaysShowEditor")
        self.formLayout_8.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.alwaysShowEditor)
        self.verticalLayout_6.addWidget(self.generalGroup)
        self.validatorGroup = QtWidgets.QGroupBox(self.generalPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.validatorGroup.sizePolicy().hasHeightForWidth())
        self.validatorGroup.setSizePolicy(sizePolicy)
        self.validatorGroup.setObjectName("validatorGroup")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.validatorGroup)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.visibility5000 = QtWidgets.QCheckBox(self.validatorGroup)
        self.visibility5000.setObjectName("visibility5000")
        self.gridLayout_4.addWidget(self.visibility5000, 0, 0, 1, 1)
        self.cloudHeight450 = QtWidgets.QCheckBox(self.validatorGroup)
        self.cloudHeight450.setObjectName("cloudHeight450")
        self.gridLayout_4.addWidget(self.cloudHeight450, 1, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.validatorGroup)
        self.backupGroup = QtWidgets.QGroupBox(self.generalPage)
        self.backupGroup.setObjectName("backupGroup")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.backupGroup)
        self.gridLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.importPath = QtWidgets.QLineEdit(self.backupGroup)
        self.importPath.setObjectName("importPath")
        self.gridLayout_5.addWidget(self.importPath, 0, 0, 1, 1)
        self.exportButton = QtWidgets.QPushButton(self.backupGroup)
        self.exportButton.setObjectName("exportButton")
        self.gridLayout_5.addWidget(self.exportButton, 1, 2, 1, 1)
        self.importButton = QtWidgets.QPushButton(self.backupGroup)
        self.importButton.setObjectName("importButton")
        self.gridLayout_5.addWidget(self.importButton, 0, 2, 1, 1)
        self.importBrowseButton = QtWidgets.QPushButton(self.backupGroup)
        self.importBrowseButton.setObjectName("importBrowseButton")
        self.gridLayout_5.addWidget(self.importBrowseButton, 0, 1, 1, 1)
        self.exportBrowseButton = QtWidgets.QPushButton(self.backupGroup)
        self.exportBrowseButton.setObjectName("exportBrowseButton")
        self.gridLayout_5.addWidget(self.exportBrowseButton, 1, 1, 1, 1)
        self.exportPath = QtWidgets.QLineEdit(self.backupGroup)
        self.exportPath.setObjectName("exportPath")
        self.gridLayout_5.addWidget(self.exportPath, 1, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.backupGroup)
        self.stackedWidget.addWidget(self.generalPage)
        self.messagePage = QtWidgets.QWidget()
        self.messagePage.setObjectName("messagePage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.messagePage)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.prefixGroup = QtWidgets.QGroupBox(self.messagePage)
        self.prefixGroup.setObjectName("prefixGroup")
        self.formLayout = QtWidgets.QFormLayout(self.prefixGroup)
        self.formLayout.setObjectName("formLayout")
        self.icaoLabel = QtWidgets.QLabel(self.prefixGroup)
        self.icaoLabel.setObjectName("icaoLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.icaoLabel)
        self.icao = QtWidgets.QLineEdit(self.prefixGroup)
        self.icao.setPlaceholderText("ZJHK")
        self.icao.setObjectName("icao")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.icao)
        self.areaLabel = QtWidgets.QLabel(self.prefixGroup)
        self.areaLabel.setObjectName("areaLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.areaLabel)
        self.area = QtWidgets.QLineEdit(self.prefixGroup)
        self.area.setPlaceholderText("CI35")
        self.area.setObjectName("area")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.area)
        self.firLabel = QtWidgets.QLabel(self.prefixGroup)
        self.firLabel.setObjectName("firLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.firLabel)
        self.fir = QtWidgets.QLineEdit(self.prefixGroup)
        self.fir.setPlaceholderText("ZJSA SANYA FIR")
        self.fir.setObjectName("fir")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fir)
        self.trendSignLabel = QtWidgets.QLabel(self.prefixGroup)
        self.trendSignLabel.setObjectName("trendSignLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.trendSignLabel)
        self.trendSign = QtWidgets.QLineEdit(self.prefixGroup)
        self.trendSign.setPlaceholderText("TREND")
        self.trendSign.setObjectName("trendSign")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.trendSign)
        self.verticalLayout_2.addWidget(self.prefixGroup)
        self.weatherGroup = QtWidgets.QGroupBox(self.messagePage)
        self.weatherGroup.setObjectName("weatherGroup")
        self.gridLayout = QtWidgets.QGridLayout(self.weatherGroup)
        self.gridLayout.setObjectName("gridLayout")
        self.addWeatherLayout = QtWidgets.QHBoxLayout()
        self.addWeatherLayout.setObjectName("addWeatherLayout")
        self.weather = QtWidgets.QLineEdit(self.weatherGroup)
        self.weather.setText("")
        self.weather.setObjectName("weather")
        self.addWeatherLayout.addWidget(self.weather)
        self.addWeatherButton = QtWidgets.QPushButton(self.weatherGroup)
        self.addWeatherButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.addWeatherButton.setText("+")
        self.addWeatherButton.setObjectName("addWeatherButton")
        self.addWeatherLayout.addWidget(self.addWeatherButton)
        self.delWeatherButton = QtWidgets.QPushButton(self.weatherGroup)
        self.delWeatherButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.delWeatherButton.setText("—")
        self.delWeatherButton.setObjectName("delWeatherButton")
        self.addWeatherLayout.addWidget(self.delWeatherButton)
        self.gridLayout.addLayout(self.addWeatherLayout, 0, 1, 1, 1)
        self.weatherList = QtWidgets.QListWidget(self.weatherGroup)
        self.weatherList.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.weatherList.setObjectName("weatherList")
        self.gridLayout.addWidget(self.weatherList, 1, 1, 1, 1)
        self.weatherWithIntensityList = QtWidgets.QListWidget(self.weatherGroup)
        self.weatherWithIntensityList.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.weatherWithIntensityList.setObjectName("weatherWithIntensityList")
        self.gridLayout.addWidget(self.weatherWithIntensityList, 1, 0, 1, 1)
        self.addWeatherWithIntensityLayout = QtWidgets.QHBoxLayout()
        self.addWeatherWithIntensityLayout.setObjectName("addWeatherWithIntensityLayout")
        self.weatherWithIntensity = QtWidgets.QLineEdit(self.weatherGroup)
        self.weatherWithIntensity.setObjectName("weatherWithIntensity")
        self.addWeatherWithIntensityLayout.addWidget(self.weatherWithIntensity)
        self.addWeatherWithIntensityButton = QtWidgets.QPushButton(self.weatherGroup)
        self.addWeatherWithIntensityButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.addWeatherWithIntensityButton.setText("+")
        self.addWeatherWithIntensityButton.setObjectName("addWeatherWithIntensityButton")
        self.addWeatherWithIntensityLayout.addWidget(self.addWeatherWithIntensityButton)
        self.delWeatherWithIntensityButton = QtWidgets.QPushButton(self.weatherGroup)
        self.delWeatherWithIntensityButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.delWeatherWithIntensityButton.setText("—")
        self.delWeatherWithIntensityButton.setObjectName("delWeatherWithIntensityButton")
        self.addWeatherWithIntensityLayout.addWidget(self.delWeatherWithIntensityButton)
        self.gridLayout.addLayout(self.addWeatherWithIntensityLayout, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.weatherGroup)
        self.stackedWidget.addWidget(self.messagePage)
        self.communicationPage = QtWidgets.QWidget()
        self.communicationPage.setObjectName("communicationPage")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.communicationPage)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.topLayout = QtWidgets.QHBoxLayout()
        self.topLayout.setObjectName("topLayout")
        self.serialGroup = QtWidgets.QGroupBox(self.communicationPage)
        self.serialGroup.setObjectName("serialGroup")
        self.formLayout_3 = QtWidgets.QFormLayout(self.serialGroup)
        self.formLayout_3.setObjectName("formLayout_3")
        self.portLabel = QtWidgets.QLabel(self.serialGroup)
        self.portLabel.setObjectName("portLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.portLabel)
        self.port = QtWidgets.QLineEdit(self.serialGroup)
        self.port.setPlaceholderText("COM1")
        self.port.setObjectName("port")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.port)
        self.baudrateLabel = QtWidgets.QLabel(self.serialGroup)
        self.baudrateLabel.setObjectName("baudrateLabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.baudrateLabel)
        self.baudrate = QtWidgets.QLineEdit(self.serialGroup)
        self.baudrate.setPlaceholderText("9600")
        self.baudrate.setObjectName("baudrate")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.baudrate)
        self.parityLabel = QtWidgets.QLabel(self.serialGroup)
        self.parityLabel.setObjectName("parityLabel")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.parityLabel)
        self.parity = QtWidgets.QComboBox(self.serialGroup)
        self.parity.setCurrentText("NONE")
        self.parity.setObjectName("parity")
        self.parity.addItem("")
        self.parity.setItemText(0, "NONE")
        self.parity.addItem("")
        self.parity.setItemText(1, "EVEN")
        self.parity.addItem("")
        self.parity.setItemText(2, "ODD")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.parity)
        self.bytesizeLabel = QtWidgets.QLabel(self.serialGroup)
        self.bytesizeLabel.setObjectName("bytesizeLabel")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.bytesizeLabel)
        self.bytesize = QtWidgets.QComboBox(self.serialGroup)
        self.bytesize.setCurrentText("5")
        self.bytesize.setObjectName("bytesize")
        self.bytesize.addItem("")
        self.bytesize.setItemText(0, "5")
        self.bytesize.addItem("")
        self.bytesize.setItemText(1, "6")
        self.bytesize.addItem("")
        self.bytesize.setItemText(2, "7")
        self.bytesize.addItem("")
        self.bytesize.setItemText(3, "8")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.bytesize)
        self.stopbitsLabel = QtWidgets.QLabel(self.serialGroup)
        self.stopbitsLabel.setObjectName("stopbitsLabel")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.stopbitsLabel)
        self.stopbits = QtWidgets.QComboBox(self.serialGroup)
        self.stopbits.setCurrentText("1")
        self.stopbits.setObjectName("stopbits")
        self.stopbits.addItem("")
        self.stopbits.setItemText(0, "1")
        self.stopbits.addItem("")
        self.stopbits.setItemText(1, "1.5")
        self.stopbits.addItem("")
        self.stopbits.setItemText(2, "2")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.stopbits)
        self.topLayout.addWidget(self.serialGroup)
        self.aftnGroup = QtWidgets.QGroupBox(self.communicationPage)
        self.aftnGroup.setMaximumSize(QtCore.QSize(239, 16777215))
        self.aftnGroup.setObjectName("aftnGroup")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.aftnGroup)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.channelLabel = QtWidgets.QLabel(self.aftnGroup)
        self.channelLabel.setObjectName("channelLabel")
        self.gridLayout_3.addWidget(self.channelLabel, 0, 0, 1, 1)
        self.channelSequenceNumber = QtWidgets.QLineEdit(self.aftnGroup)
        self.channelSequenceNumber.setPlaceholderText("1")
        self.channelSequenceNumber.setObjectName("channelSequenceNumber")
        self.gridLayout_3.addWidget(self.channelSequenceNumber, 1, 1, 1, 1)
        self.channelSequenceNumberLabel = QtWidgets.QLabel(self.aftnGroup)
        self.channelSequenceNumberLabel.setObjectName("channelSequenceNumberLabel")
        self.gridLayout_3.addWidget(self.channelSequenceNumberLabel, 1, 0, 1, 1)
        self.maxLineChar = QtWidgets.QLineEdit(self.aftnGroup)
        self.maxLineChar.setPlaceholderText("69")
        self.maxLineChar.setObjectName("maxLineChar")
        self.gridLayout_3.addWidget(self.maxLineChar, 6, 1, 1, 2)
        self.maxSendAddress = QtWidgets.QLineEdit(self.aftnGroup)
        self.maxSendAddress.setPlaceholderText("21")
        self.maxSendAddress.setObjectName("maxSendAddress")
        self.gridLayout_3.addWidget(self.maxSendAddress, 5, 1, 1, 2)
        self.originatorAddress = QtWidgets.QLineEdit(self.aftnGroup)
        self.originatorAddress.setPlaceholderText("ZJHKYMYX")
        self.originatorAddress.setObjectName("originatorAddress")
        self.gridLayout_3.addWidget(self.originatorAddress, 4, 1, 1, 2)
        self.originatorAddressLabel = QtWidgets.QLabel(self.aftnGroup)
        self.originatorAddressLabel.setObjectName("originatorAddressLabel")
        self.gridLayout_3.addWidget(self.originatorAddressLabel, 4, 0, 1, 1)
        self.maxLineCharLabel = QtWidgets.QLabel(self.aftnGroup)
        self.maxLineCharLabel.setObjectName("maxLineCharLabel")
        self.gridLayout_3.addWidget(self.maxLineCharLabel, 6, 0, 1, 1)
        self.channel = QtWidgets.QLineEdit(self.aftnGroup)
        self.channel.setPlaceholderText("YMA")
        self.channel.setObjectName("channel")
        self.gridLayout_3.addWidget(self.channel, 0, 1, 1, 2)
        self.resetNumberButton = QtWidgets.QPushButton(self.aftnGroup)
        self.resetNumberButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.resetNumberButton.setObjectName("resetNumberButton")
        self.gridLayout_3.addWidget(self.resetNumberButton, 1, 2, 1, 1)
        self.maxSendAddressLabel = QtWidgets.QLabel(self.aftnGroup)
        self.maxSendAddressLabel.setObjectName("maxSendAddressLabel")
        self.gridLayout_3.addWidget(self.maxSendAddressLabel, 5, 0, 1, 1)
        self.topLayout.addWidget(self.aftnGroup)
        self.verticalLayout_4.addLayout(self.topLayout)
        self.addressGroup = QtWidgets.QGroupBox(self.communicationPage)
        self.addressGroup.setObjectName("addressGroup")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.addressGroup)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tabWidget = QtWidgets.QTabWidget(self.addressGroup)
        self.tabWidget.setObjectName("tabWidget")
        self.tafTab = QtWidgets.QWidget()
        self.tafTab.setObjectName("tafTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tafTab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tafAddress = QtWidgets.QTextEdit(self.tafTab)
        self.tafAddress.setObjectName("tafAddress")
        self.verticalLayout_3.addWidget(self.tafAddress)
        self.tabWidget.addTab(self.tafTab, "TAF")
        self.sigmetTab = QtWidgets.QWidget()
        self.sigmetTab.setObjectName("sigmetTab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.sigmetTab)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.sigmetAddress = QtWidgets.QTextEdit(self.sigmetTab)
        self.sigmetAddress.setObjectName("sigmetAddress")
        self.verticalLayout_7.addWidget(self.sigmetAddress)
        self.tabWidget.addTab(self.sigmetTab, "SIGMET")
        self.trendTab = QtWidgets.QWidget()
        self.trendTab.setObjectName("trendTab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.trendTab)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.trendAddress = QtWidgets.QTextEdit(self.trendTab)
        self.trendAddress.setObjectName("trendAddress")
        self.verticalLayout_9.addWidget(self.trendAddress)
        self.tabWidget.addTab(self.trendTab, "TREND")
        self.verticalLayout_10.addWidget(self.tabWidget)
        self.verticalLayout_4.addWidget(self.addressGroup)
        self.stackedWidget.addWidget(self.communicationPage)
        self.monitorPage = QtWidgets.QWidget()
        self.monitorPage.setObjectName("monitorPage")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.monitorPage)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.dataSourceGroup = QtWidgets.QGroupBox(self.monitorPage)
        self.dataSourceGroup.setObjectName("dataSourceGroup")
        self.formLayout_2 = QtWidgets.QFormLayout(self.dataSourceGroup)
        self.formLayout_2.setObjectName("formLayout_2")
        self.webApiLabel = QtWidgets.QLabel(self.dataSourceGroup)
        self.webApiLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.webApiLabel.setObjectName("webApiLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.webApiLabel)
        self.webApiURL = QtWidgets.QLineEdit(self.dataSourceGroup)
        self.webApiURL.setObjectName("webApiURL")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.webApiURL)
        self.verticalLayout_5.addWidget(self.dataSourceGroup)
        self.warnGroup = QtWidgets.QGroupBox(self.monitorPage)
        self.warnGroup.setObjectName("warnGroup")
        self.formLayout_4 = QtWidgets.QFormLayout(self.warnGroup)
        self.formLayout_4.setObjectName("formLayout_4")
        self.warnTAFTimeLabel = QtWidgets.QLabel(self.warnGroup)
        self.warnTAFTimeLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.warnTAFTimeLabel.setObjectName("warnTAFTimeLabel")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.warnTAFTimeLabel)
        self.warnTAFTime = QtWidgets.QLineEdit(self.warnGroup)
        self.warnTAFTime.setMaximumSize(QtCore.QSize(120, 16777215))
        self.warnTAFTime.setText("")
        self.warnTAFTime.setObjectName("warnTAFTime")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.warnTAFTime)
        self.warnTAFVolumeLabel = QtWidgets.QLabel(self.warnGroup)
        self.warnTAFVolumeLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.warnTAFVolumeLabel.setObjectName("warnTAFVolumeLabel")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.warnTAFVolumeLabel)
        self.warnTAFVolume = QtWidgets.QSlider(self.warnGroup)
        self.warnTAFVolume.setOrientation(QtCore.Qt.Horizontal)
        self.warnTAFVolume.setObjectName("warnTAFVolume")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.warnTAFVolume)
        self.verticalLayout_5.addWidget(self.warnGroup)
        self.remindGroup = QtWidgets.QGroupBox(self.monitorPage)
        self.remindGroup.setObjectName("remindGroup")
        self.formLayout_5 = QtWidgets.QFormLayout(self.remindGroup)
        self.formLayout_5.setObjectName("formLayout_5")
        self.remindTAF = QtWidgets.QCheckBox(self.remindGroup)
        self.remindTAF.setMinimumSize(QtCore.QSize(100, 0))
        self.remindTAF.setObjectName("remindTAF")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.remindTAF)
        self.remindTAFVolume = QtWidgets.QSlider(self.remindGroup)
        self.remindTAFVolume.setOrientation(QtCore.Qt.Horizontal)
        self.remindTAFVolume.setObjectName("remindTAFVolume")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.remindTAFVolume)
        self.remindTrend = QtWidgets.QCheckBox(self.remindGroup)
        self.remindTrend.setMinimumSize(QtCore.QSize(100, 0))
        self.remindTrend.setObjectName("remindTrend")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.remindTrend)
        self.remindTrendVolume = QtWidgets.QSlider(self.remindGroup)
        self.remindTrendVolume.setOrientation(QtCore.Qt.Horizontal)
        self.remindTrendVolume.setObjectName("remindTrendVolume")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.remindTrendVolume)
        self.remindSIGMET = QtWidgets.QCheckBox(self.remindGroup)
        self.remindSIGMET.setMinimumSize(QtCore.QSize(100, 0))
        self.remindSIGMET.setObjectName("remindSIGMET")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.remindSIGMET)
        self.remindSIGMETVolume = QtWidgets.QSlider(self.remindGroup)
        self.remindSIGMETVolume.setOrientation(QtCore.Qt.Horizontal)
        self.remindSIGMETVolume.setObjectName("remindSIGMETVolume")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.remindSIGMETVolume)
        self.verticalLayout_5.addWidget(self.remindGroup)
        self.callServiceGroup = QtWidgets.QGroupBox(self.monitorPage)
        self.callServiceGroup.setObjectName("callServiceGroup")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.callServiceGroup)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.callServiceURLLabel = QtWidgets.QLabel(self.callServiceGroup)
        self.callServiceURLLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.callServiceURLLabel.setObjectName("callServiceURLLabel")
        self.gridLayout_2.addWidget(self.callServiceURLLabel, 0, 0, 1, 1)
        self.callServiceURL = QtWidgets.QLineEdit(self.callServiceGroup)
        self.callServiceURL.setObjectName("callServiceURL")
        self.gridLayout_2.addWidget(self.callServiceURL, 0, 1, 1, 1)
        self.callServiceTokenLabel = QtWidgets.QLabel(self.callServiceGroup)
        self.callServiceTokenLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.callServiceTokenLabel.setObjectName("callServiceTokenLabel")
        self.gridLayout_2.addWidget(self.callServiceTokenLabel, 1, 0, 1, 1)
        self.callUpButton = QtWidgets.QPushButton(self.callServiceGroup)
        self.callUpButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.callUpButton.setObjectName("callUpButton")
        self.gridLayout_2.addWidget(self.callUpButton, 0, 2, 1, 1)
        self.callServiceToken = QtWidgets.QLineEdit(self.callServiceGroup)
        self.callServiceToken.setObjectName("callServiceToken")
        self.gridLayout_2.addWidget(self.callServiceToken, 1, 1, 1, 2)
        self.verticalLayout_5.addWidget(self.callServiceGroup)
        self.stackedWidget.addWidget(self.monitorPage)
        self.contractPage = QtWidgets.QWidget()
        self.contractPage.setObjectName("contractPage")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.contractPage)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.contractGroup = QtWidgets.QGroupBox(self.contractPage)
        self.contractGroup.setObjectName("contractGroup")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.contractGroup)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.addPersonLayout = QtWidgets.QHBoxLayout()
        self.addPersonLayout.setObjectName("addPersonLayout")
        self.personName = QtWidgets.QLineEdit(self.contractGroup)
        self.personName.setText("")
        self.personName.setObjectName("personName")
        self.addPersonLayout.addWidget(self.personName)
        self.personMobile = QtWidgets.QLineEdit(self.contractGroup)
        self.personMobile.setObjectName("personMobile")
        self.addPersonLayout.addWidget(self.personMobile)
        self.addPersonButton = QtWidgets.QPushButton(self.contractGroup)
        self.addPersonButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.addPersonButton.setText("+")
        self.addPersonButton.setObjectName("addPersonButton")
        self.addPersonLayout.addWidget(self.addPersonButton)
        self.delPersonButton = QtWidgets.QPushButton(self.contractGroup)
        self.delPersonButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.delPersonButton.setText("—")
        self.delPersonButton.setObjectName("delPersonButton")
        self.addPersonLayout.addWidget(self.delPersonButton)
        self.verticalLayout_12.addLayout(self.addPersonLayout)
        self.contractTable = QtWidgets.QTableWidget(self.contractGroup)
        self.contractTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.contractTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.contractTable.setObjectName("contractTable")
        self.contractTable.setColumnCount(2)
        self.contractTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.contractTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.contractTable.setHorizontalHeaderItem(1, item)
        self.contractTable.horizontalHeader().setStretchLastSection(True)
        self.contractTable.verticalHeader().setVisible(False)
        self.verticalLayout_12.addWidget(self.contractTable)
        self.selectedContractLayout = QtWidgets.QHBoxLayout()
        self.selectedContractLayout.setObjectName("selectedContractLayout")
        self.selectedContractLabel = QtWidgets.QLabel(self.contractGroup)
        self.selectedContractLabel.setObjectName("selectedContractLabel")
        self.selectedContractLayout.addWidget(self.selectedContractLabel)
        self.selectedContract = QtWidgets.QComboBox(self.contractGroup)
        self.selectedContract.setObjectName("selectedContract")
        self.selectedContractLayout.addWidget(self.selectedContract)
        self.verticalLayout_12.addLayout(self.selectedContractLayout)
        self.verticalLayout_11.addWidget(self.contractGroup)
        self.stackedWidget.addWidget(self.contractPage)
        self.mainLayout.addWidget(self.stackedWidget)
        self.verticalLayout.addLayout(self.mainLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Settings)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Settings)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Settings.accept)
        self.buttonBox.rejected.connect(Settings.reject)
        self.menu.currentRowChanged['int'].connect(self.stackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(Settings)
        Settings.setTabOrder(self.menu, self.icao)
        Settings.setTabOrder(self.icao, self.area)
        Settings.setTabOrder(self.area, self.fir)
        Settings.setTabOrder(self.fir, self.trendSign)
        Settings.setTabOrder(self.trendSign, self.weather)
        Settings.setTabOrder(self.weather, self.addWeatherButton)
        Settings.setTabOrder(self.addWeatherButton, self.delWeatherButton)
        Settings.setTabOrder(self.delWeatherButton, self.weatherList)
        Settings.setTabOrder(self.weatherList, self.weatherWithIntensity)
        Settings.setTabOrder(self.weatherWithIntensity, self.addWeatherWithIntensityButton)
        Settings.setTabOrder(self.addWeatherWithIntensityButton, self.delWeatherWithIntensityButton)
        Settings.setTabOrder(self.delWeatherWithIntensityButton, self.port)
        Settings.setTabOrder(self.port, self.baudrate)
        Settings.setTabOrder(self.baudrate, self.parity)
        Settings.setTabOrder(self.parity, self.bytesize)
        Settings.setTabOrder(self.bytesize, self.stopbits)
        Settings.setTabOrder(self.stopbits, self.channel)
        Settings.setTabOrder(self.channel, self.channelSequenceNumber)
        Settings.setTabOrder(self.channelSequenceNumber, self.originatorAddress)
        Settings.setTabOrder(self.originatorAddress, self.tabWidget)
        Settings.setTabOrder(self.tabWidget, self.tafAddress)
        Settings.setTabOrder(self.tafAddress, self.sigmetAddress)
        Settings.setTabOrder(self.sigmetAddress, self.trendAddress)
        Settings.setTabOrder(self.trendAddress, self.warnTAFVolume)
        Settings.setTabOrder(self.warnTAFVolume, self.remindTAF)
        Settings.setTabOrder(self.remindTAF, self.remindTAFVolume)
        Settings.setTabOrder(self.remindTAFVolume, self.remindTrend)
        Settings.setTabOrder(self.remindTrend, self.remindTrendVolume)
        Settings.setTabOrder(self.remindTrendVolume, self.remindSIGMET)
        Settings.setTabOrder(self.remindSIGMET, self.remindSIGMETVolume)
        Settings.setTabOrder(self.remindSIGMETVolume, self.runOnStart)
        Settings.setTabOrder(self.runOnStart, self.closeToMinimize)
        Settings.setTabOrder(self.closeToMinimize, self.importPath)
        Settings.setTabOrder(self.importPath, self.importBrowseButton)
        Settings.setTabOrder(self.importBrowseButton, self.importButton)
        Settings.setTabOrder(self.importButton, self.exportPath)
        Settings.setTabOrder(self.exportPath, self.exportBrowseButton)
        Settings.setTabOrder(self.exportBrowseButton, self.exportButton)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Settings"))
        __sortingEnabled = self.menu.isSortingEnabled()
        self.menu.setSortingEnabled(False)
        item = self.menu.item(0)
        item.setText(_translate("Settings", "General"))
        item = self.menu.item(1)
        item.setText(_translate("Settings", "Message"))
        item = self.menu.item(2)
        item.setText(_translate("Settings", "Communication"))
        item = self.menu.item(3)
        item.setText(_translate("Settings", "Monitor"))
        item = self.menu.item(4)
        item.setText(_translate("Settings", "Contacts"))
        self.menu.setSortingEnabled(__sortingEnabled)
        self.generalGroup.setTitle(_translate("Settings", "General"))
        self.runOnStart.setText(_translate("Settings", "Run on system startup"))
        self.closeToMinimize.setText(_translate("Settings", "Minimize to system tray when closed"))
        self.debugMode.setText(_translate("Settings", "Debug mode"))
        self.alwaysShowEditor.setText(_translate("Settings", "Always show forecast editor"))
        self.validatorGroup.setTitle(_translate("Settings", "Validator"))
        self.visibility5000.setText(_translate("Settings", "Visibility has 5000 meters"))
        self.cloudHeight450.setText(_translate("Settings", "Cloud height has 450 meters"))
        self.backupGroup.setTitle(_translate("Settings", "Backup"))
        self.importPath.setPlaceholderText(_translate("Settings", "PATH"))
        self.exportButton.setText(_translate("Settings", "Export"))
        self.importButton.setText(_translate("Settings", "Import"))
        self.importBrowseButton.setText(_translate("Settings", "Browse"))
        self.exportBrowseButton.setText(_translate("Settings", "Browse"))
        self.exportPath.setPlaceholderText(_translate("Settings", "PATH"))
        self.prefixGroup.setTitle(_translate("Settings", "Prefix"))
        self.icaoLabel.setText(_translate("Settings", "Airport Code"))
        self.areaLabel.setText(_translate("Settings", "Intelligence Area"))
        self.firLabel.setText(_translate("Settings", "SIGMET Area"))
        self.trendSignLabel.setText(_translate("Settings", "Trend Identifier"))
        self.weatherGroup.setTitle(_translate("Settings", "Weather Phenomenon"))
        self.weather.setPlaceholderText(_translate("Settings", "Weather without intensity"))
        self.weatherWithIntensity.setPlaceholderText(_translate("Settings", "Weather with intensity"))
        self.serialGroup.setTitle(_translate("Settings", "Serial Parameters"))
        self.portLabel.setText(_translate("Settings", "Port"))
        self.baudrateLabel.setText(_translate("Settings", "Baudrate"))
        self.parityLabel.setText(_translate("Settings", "Parity"))
        self.bytesizeLabel.setText(_translate("Settings", "Bytesize"))
        self.stopbitsLabel.setText(_translate("Settings", "Stopbits"))
        self.aftnGroup.setTitle(_translate("Settings", "AFTN Parameters"))
        self.channelLabel.setText(_translate("Settings", "Channel"))
        self.channelSequenceNumberLabel.setText(_translate("Settings", "Sequence Number"))
        self.originatorAddressLabel.setText(_translate("Settings", "Originator"))
        self.maxLineCharLabel.setText(_translate("Settings", "Max Line Char"))
        self.resetNumberButton.setText(_translate("Settings", "Reset"))
        self.maxSendAddressLabel.setText(_translate("Settings", "Max Address"))
        self.addressGroup.setTitle(_translate("Settings", "Send Address"))
        self.tafAddress.setPlaceholderText(_translate("Settings", "Please separate multiple addresses by space"))
        self.sigmetAddress.setPlaceholderText(_translate("Settings", "Please separate multiple addresses by space"))
        self.trendAddress.setPlaceholderText(_translate("Settings", "Please separate multiple addresses by space"))
        self.dataSourceGroup.setTitle(_translate("Settings", "Data Source"))
        self.webApiLabel.setText(_translate("Settings", "Request URL"))
        self.webApiURL.setPlaceholderText(_translate("Settings", "URL"))
        self.warnGroup.setTitle(_translate("Settings", "Late Monitoring"))
        self.warnTAFTimeLabel.setText(_translate("Settings", "Alarm Time"))
        self.warnTAFTime.setPlaceholderText(_translate("Settings", "Unit minutes"))
        self.warnTAFVolumeLabel.setText(_translate("Settings", "Alarm Sound"))
        self.remindGroup.setTitle(_translate("Settings", "Sound Reminder and Volume"))
        self.remindTAF.setText(_translate("Settings", "TAF"))
        self.remindTrend.setText(_translate("Settings", "Trend"))
        self.remindSIGMET.setText(_translate("Settings", "SIGMET"))
        self.callServiceGroup.setTitle(_translate("Settings", "Phone Service"))
        self.callServiceURLLabel.setText(_translate("Settings", "Request URL"))
        self.callServiceURL.setPlaceholderText(_translate("Settings", "URL"))
        self.callServiceTokenLabel.setText(_translate("Settings", "Auth Token"))
        self.callUpButton.setText(_translate("Settings", "Dial"))
        self.callServiceToken.setPlaceholderText(_translate("Settings", "Token"))
        self.contractGroup.setTitle(_translate("Settings", "Contacts"))
        self.personName.setPlaceholderText(_translate("Settings", "Name"))
        self.personMobile.setPlaceholderText(_translate("Settings", "Mobile"))
        item = self.contractTable.horizontalHeaderItem(0)
        item.setText(_translate("Settings", "Name"))
        item = self.contractTable.horizontalHeaderItem(1)
        item.setText(_translate("Settings", "Mobile"))
        self.selectedContractLabel.setText(_translate("Settings", "Current Selected Contact"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Settings = QtWidgets.QDialog()
    ui = Ui_Settings()
    ui.setupUi(Settings)
    Settings.show()
    sys.exit(app.exec_())

