# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Work\tafor\tafor\components\ui\sigmet_area.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Editor(object):
    def setupUi(self, Editor):
        Editor.setObjectName("Editor")
        Editor.resize(526, 180)
        Editor.setWindowTitle("Sigmet")
        self.layout = QtWidgets.QVBoxLayout(Editor)
        self.layout.setContentsMargins(0, 0, 0, 0)
        self.layout.setObjectName("layout")
        self.areaGroup = QtWidgets.QGroupBox(Editor)
        self.areaGroup.setObjectName("areaGroup")
        self.areaLayout = QtWidgets.QVBoxLayout(self.areaGroup)
        self.areaLayout.setContentsMargins(-1, -1, -1, 5)
        self.areaLayout.setObjectName("areaLayout")
        self.changeAreaWidget = QtWidgets.QWidget(self.areaGroup)
        self.changeAreaWidget.setObjectName("changeAreaWidget")
        self.changeAreaLayout = QtWidgets.QHBoxLayout(self.changeAreaWidget)
        self.changeAreaLayout.setContentsMargins(0, 0, 0, 0)
        self.changeAreaLayout.setObjectName("changeAreaLayout")
        self.canvas = QtWidgets.QRadioButton(self.changeAreaWidget)
        self.canvas.setChecked(True)
        self.canvas.setObjectName("canvas")
        self.changeAreaLayout.addWidget(self.canvas)
        self.manual = QtWidgets.QRadioButton(self.changeAreaWidget)
        self.manual.setObjectName("manual")
        self.changeAreaLayout.addWidget(self.manual)
        self.entire = QtWidgets.QRadioButton(self.changeAreaWidget)
        self.entire.setObjectName("entire")
        self.changeAreaLayout.addWidget(self.entire)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.changeAreaLayout.addItem(spacerItem)
        self.fcstButton = QtWidgets.QToolButton(self.changeAreaWidget)
        self.fcstButton.setText("")
        self.fcstButton.setIconSize(QtCore.QSize(16, 16))
        self.fcstButton.setCheckable(True)
        self.fcstButton.setAutoRaise(True)
        self.fcstButton.setObjectName("fcstButton")
        self.changeAreaLayout.addWidget(self.fcstButton)
        self.modeButton = QtWidgets.QToolButton(self.changeAreaWidget)
        self.modeButton.setText("")
        self.modeButton.setIconSize(QtCore.QSize(16, 16))
        self.modeButton.setAutoRaise(True)
        self.modeButton.setObjectName("modeButton")
        self.changeAreaLayout.addWidget(self.modeButton)
        self.areaLayout.addWidget(self.changeAreaWidget)
        self.latitudeAndLongitudeWidget = QtWidgets.QWidget(self.areaGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.latitudeAndLongitudeWidget.sizePolicy().hasHeightForWidth())
        self.latitudeAndLongitudeWidget.setSizePolicy(sizePolicy)
        self.latitudeAndLongitudeWidget.setObjectName("latitudeAndLongitudeWidget")
        self.latitudeAndLongitudeLayout = QtWidgets.QGridLayout(self.latitudeAndLongitudeWidget)
        self.latitudeAndLongitudeLayout.setContentsMargins(0, 15, 0, 0)
        self.latitudeAndLongitudeLayout.setObjectName("latitudeAndLongitudeLayout")
        self.eastLabel = QtWidgets.QLabel(self.latitudeAndLongitudeWidget)
        self.eastLabel.setObjectName("eastLabel")
        self.latitudeAndLongitudeLayout.addWidget(self.eastLabel, 4, 1, 1, 1)
        self.north = QtWidgets.QLineEdit(self.latitudeAndLongitudeWidget)
        self.north.setObjectName("north")
        self.latitudeAndLongitudeLayout.addWidget(self.north, 1, 1, 1, 1)
        self.westLabel = QtWidgets.QLabel(self.latitudeAndLongitudeWidget)
        self.westLabel.setObjectName("westLabel")
        self.latitudeAndLongitudeLayout.addWidget(self.westLabel, 4, 2, 1, 1)
        self.east = QtWidgets.QLineEdit(self.latitudeAndLongitudeWidget)
        self.east.setObjectName("east")
        self.latitudeAndLongitudeLayout.addWidget(self.east, 5, 1, 1, 1)
        self.south = QtWidgets.QLineEdit(self.latitudeAndLongitudeWidget)
        self.south.setObjectName("south")
        self.latitudeAndLongitudeLayout.addWidget(self.south, 1, 2, 1, 1)
        self.longtitudeLabel = QtWidgets.QLabel(self.latitudeAndLongitudeWidget)
        self.longtitudeLabel.setMinimumSize(QtCore.QSize(77, 0))
        self.longtitudeLabel.setObjectName("longtitudeLabel")
        self.latitudeAndLongitudeLayout.addWidget(self.longtitudeLabel, 5, 0, 1, 1)
        self.west = QtWidgets.QLineEdit(self.latitudeAndLongitudeWidget)
        self.west.setObjectName("west")
        self.latitudeAndLongitudeLayout.addWidget(self.west, 5, 2, 1, 1)
        self.latitudeLabel = QtWidgets.QLabel(self.latitudeAndLongitudeWidget)
        self.latitudeLabel.setMinimumSize(QtCore.QSize(77, 0))
        self.latitudeLabel.setObjectName("latitudeLabel")
        self.latitudeAndLongitudeLayout.addWidget(self.latitudeLabel, 1, 0, 1, 1)
        self.southLabel = QtWidgets.QLabel(self.latitudeAndLongitudeWidget)
        self.southLabel.setObjectName("southLabel")
        self.latitudeAndLongitudeLayout.addWidget(self.southLabel, 0, 2, 1, 1)
        self.northLabel = QtWidgets.QLabel(self.latitudeAndLongitudeWidget)
        self.northLabel.setObjectName("northLabel")
        self.latitudeAndLongitudeLayout.addWidget(self.northLabel, 0, 1, 1, 1)
        self.areaLayout.addWidget(self.latitudeAndLongitudeWidget)
        self.layout.addWidget(self.areaGroup)
        self.eastLabel.setBuddy(self.east)
        self.westLabel.setBuddy(self.west)
        self.southLabel.setBuddy(self.south)
        self.northLabel.setBuddy(self.north)

        self.retranslateUi(Editor)
        QtCore.QMetaObject.connectSlotsByName(Editor)
        Editor.setTabOrder(self.canvas, self.manual)
        Editor.setTabOrder(self.manual, self.entire)
        Editor.setTabOrder(self.entire, self.modeButton)
        Editor.setTabOrder(self.modeButton, self.north)
        Editor.setTabOrder(self.north, self.south)
        Editor.setTabOrder(self.south, self.east)
        Editor.setTabOrder(self.east, self.west)

    def retranslateUi(self, Editor):
        _translate = QtCore.QCoreApplication.translate
        self.areaGroup.setTitle(_translate("Editor", "Area"))
        self.canvas.setText(_translate("Editor", "Canvas"))
        self.manual.setText(_translate("Editor", "Manual"))
        self.entire.setText(_translate("Editor", "Entire"))
        self.eastLabel.setText(_translate("Editor", "E OF"))
        self.westLabel.setText(_translate("Editor", "W OF"))
        self.longtitudeLabel.setText(_translate("Editor", "Longitude"))
        self.latitudeLabel.setText(_translate("Editor", "Latitude"))
        self.southLabel.setText(_translate("Editor", "S OF"))
        self.northLabel.setText(_translate("Editor", "N OF"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Editor = QtWidgets.QWidget()
    ui = Ui_Editor()
    ui.setupUi(Editor)
    Editor.show()
    sys.exit(app.exec_())

