# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Work\tafor\tafor\components\ui\sigmet_general.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Editor(object):
    def setupUi(self, Editor):
        Editor.setObjectName("Editor")
        Editor.resize(662, 278)
        Editor.setWindowTitle("Sigmet")
        self.verticalLayout = QtWidgets.QVBoxLayout(Editor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.descriptionGroup = QtWidgets.QGroupBox(Editor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.descriptionGroup.sizePolicy().hasHeightForWidth())
        self.descriptionGroup.setSizePolicy(sizePolicy)
        self.descriptionGroup.setObjectName("descriptionGroup")
        self.descriptionLayout = QtWidgets.QGridLayout(self.descriptionGroup)
        self.descriptionLayout.setObjectName("descriptionLayout")
        self.speed = QtWidgets.QLineEdit(self.descriptionGroup)
        self.speed.setObjectName("speed")
        self.descriptionLayout.addWidget(self.speed, 1, 1, 1, 1)
        self.movement = QtWidgets.QComboBox(self.descriptionGroup)
        self.movement.setObjectName("movement")
        self.movement.addItem("")
        self.movement.setItemText(0, "N")
        self.movement.addItem("")
        self.movement.setItemText(1, "NE")
        self.movement.addItem("")
        self.movement.setItemText(2, "E")
        self.movement.addItem("")
        self.movement.setItemText(3, "SE")
        self.movement.addItem("")
        self.movement.setItemText(4, "S")
        self.movement.addItem("")
        self.movement.setItemText(5, "SW")
        self.movement.addItem("")
        self.movement.setItemText(6, "W")
        self.movement.addItem("")
        self.movement.setItemText(7, "NW")
        self.movement.addItem("")
        self.movement.setItemText(8, "STNR")
        self.descriptionLayout.addWidget(self.movement, 1, 0, 1, 1)
        self.top = QtWidgets.QLineEdit(self.descriptionGroup)
        self.top.setObjectName("top")
        self.descriptionLayout.addWidget(self.top, 1, 4, 1, 1)
        self.movementLabel = QtWidgets.QLabel(self.descriptionGroup)
        self.movementLabel.setObjectName("movementLabel")
        self.descriptionLayout.addWidget(self.movementLabel, 0, 0, 1, 1)
        self.speedLabel = QtWidgets.QLabel(self.descriptionGroup)
        self.speedLabel.setObjectName("speedLabel")
        self.descriptionLayout.addWidget(self.speedLabel, 0, 1, 1, 1)
        self.positionLabel = QtWidgets.QLabel(self.descriptionGroup)
        self.positionLabel.setObjectName("positionLabel")
        self.descriptionLayout.addWidget(self.positionLabel, 0, 2, 1, 1)
        self.intensityChangeLabel = QtWidgets.QLabel(self.descriptionGroup)
        self.intensityChangeLabel.setObjectName("intensityChangeLabel")
        self.descriptionLayout.addWidget(self.intensityChangeLabel, 0, 5, 1, 1)
        self.intensityChange = QtWidgets.QComboBox(self.descriptionGroup)
        self.intensityChange.setObjectName("intensityChange")
        self.intensityChange.addItem("")
        self.intensityChange.setItemText(0, "NC")
        self.intensityChange.addItem("")
        self.intensityChange.setItemText(1, "INTSF")
        self.intensityChange.addItem("")
        self.intensityChange.setItemText(2, "WKN")
        self.descriptionLayout.addWidget(self.intensityChange, 1, 5, 1, 1)
        self.base = QtWidgets.QLineEdit(self.descriptionGroup)
        self.base.setObjectName("base")
        self.descriptionLayout.addWidget(self.base, 1, 3, 1, 1)
        self.position = QtWidgets.QComboBox(self.descriptionGroup)
        self.position.setObjectName("position")
        self.position.addItem("")
        self.position.setItemText(0, "")
        self.position.addItem("")
        self.position.setItemText(1, "TOP")
        self.position.addItem("")
        self.position.setItemText(2, "ABV")
        self.position.addItem("")
        self.position.setItemText(3, "BLW")
        self.position.addItem("")
        self.position.setItemText(4, "SFC")
        self.descriptionLayout.addWidget(self.position, 1, 2, 1, 1)
        self.baseLabel = QtWidgets.QLabel(self.descriptionGroup)
        self.baseLabel.setObjectName("baseLabel")
        self.descriptionLayout.addWidget(self.baseLabel, 0, 3, 1, 1)
        self.topLabel = QtWidgets.QLabel(self.descriptionGroup)
        self.topLabel.setObjectName("topLabel")
        self.descriptionLayout.addWidget(self.topLabel, 0, 4, 1, 1)
        self.verticalLayout.addWidget(self.descriptionGroup)
        self.areaGroup = QtWidgets.QGroupBox(Editor)
        self.areaGroup.setObjectName("areaGroup")
        self.areaLayout = QtWidgets.QVBoxLayout(self.areaGroup)
        self.areaLayout.setObjectName("areaLayout")
        self.changeAreaWidget = QtWidgets.QWidget(self.areaGroup)
        self.changeAreaWidget.setObjectName("changeAreaWidget")
        self.changeAreaLayout = QtWidgets.QHBoxLayout(self.changeAreaWidget)
        self.changeAreaLayout.setContentsMargins(0, 0, 0, 0)
        self.changeAreaLayout.setObjectName("changeAreaLayout")
        self.canvas = QtWidgets.QRadioButton(self.changeAreaWidget)
        self.canvas.setChecked(True)
        self.canvas.setObjectName("canvas")
        self.changeAreaLayout.addWidget(self.canvas)
        self.manual = QtWidgets.QRadioButton(self.changeAreaWidget)
        self.manual.setObjectName("manual")
        self.changeAreaLayout.addWidget(self.manual)
        self.entire = QtWidgets.QRadioButton(self.changeAreaWidget)
        self.entire.setObjectName("entire")
        self.changeAreaLayout.addWidget(self.entire)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.changeAreaLayout.addItem(spacerItem)
        self.modeButton = QtWidgets.QToolButton(self.changeAreaWidget)
        self.modeButton.setText("")
        self.modeButton.setIconSize(QtCore.QSize(16, 16))
        self.modeButton.setAutoRaise(True)
        self.modeButton.setObjectName("modeButton")
        self.changeAreaLayout.addWidget(self.modeButton)
        self.areaLayout.addWidget(self.changeAreaWidget)
        self.latitudeAndLongitudeWidget = QtWidgets.QWidget(self.areaGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.latitudeAndLongitudeWidget.sizePolicy().hasHeightForWidth())
        self.latitudeAndLongitudeWidget.setSizePolicy(sizePolicy)
        self.latitudeAndLongitudeWidget.setObjectName("latitudeAndLongitudeWidget")
        self.latitudeAndLongitudeLayout = QtWidgets.QGridLayout(self.latitudeAndLongitudeWidget)
        self.latitudeAndLongitudeLayout.setContentsMargins(0, 15, 0, 0)
        self.latitudeAndLongitudeLayout.setObjectName("latitudeAndLongitudeLayout")
        self.eastLabel = QtWidgets.QLabel(self.latitudeAndLongitudeWidget)
        self.eastLabel.setObjectName("eastLabel")
        self.latitudeAndLongitudeLayout.addWidget(self.eastLabel, 4, 1, 1, 1)
        self.north = QtWidgets.QLineEdit(self.latitudeAndLongitudeWidget)
        self.north.setObjectName("north")
        self.latitudeAndLongitudeLayout.addWidget(self.north, 1, 1, 1, 1)
        self.westLabel = QtWidgets.QLabel(self.latitudeAndLongitudeWidget)
        self.westLabel.setObjectName("westLabel")
        self.latitudeAndLongitudeLayout.addWidget(self.westLabel, 4, 2, 1, 1)
        self.east = QtWidgets.QLineEdit(self.latitudeAndLongitudeWidget)
        self.east.setObjectName("east")
        self.latitudeAndLongitudeLayout.addWidget(self.east, 5, 1, 1, 1)
        self.south = QtWidgets.QLineEdit(self.latitudeAndLongitudeWidget)
        self.south.setObjectName("south")
        self.latitudeAndLongitudeLayout.addWidget(self.south, 1, 2, 1, 1)
        self.longtitudeLabel = QtWidgets.QLabel(self.latitudeAndLongitudeWidget)
        self.longtitudeLabel.setMinimumSize(QtCore.QSize(77, 0))
        self.longtitudeLabel.setObjectName("longtitudeLabel")
        self.latitudeAndLongitudeLayout.addWidget(self.longtitudeLabel, 5, 0, 1, 1)
        self.west = QtWidgets.QLineEdit(self.latitudeAndLongitudeWidget)
        self.west.setObjectName("west")
        self.latitudeAndLongitudeLayout.addWidget(self.west, 5, 2, 1, 1)
        self.latitudeLabel = QtWidgets.QLabel(self.latitudeAndLongitudeWidget)
        self.latitudeLabel.setMinimumSize(QtCore.QSize(77, 0))
        self.latitudeLabel.setObjectName("latitudeLabel")
        self.latitudeAndLongitudeLayout.addWidget(self.latitudeLabel, 1, 0, 1, 1)
        self.southLabel = QtWidgets.QLabel(self.latitudeAndLongitudeWidget)
        self.southLabel.setObjectName("southLabel")
        self.latitudeAndLongitudeLayout.addWidget(self.southLabel, 0, 2, 1, 1)
        self.northLabel = QtWidgets.QLabel(self.latitudeAndLongitudeWidget)
        self.northLabel.setObjectName("northLabel")
        self.latitudeAndLongitudeLayout.addWidget(self.northLabel, 0, 1, 1, 1)
        self.areaLayout.addWidget(self.latitudeAndLongitudeWidget)
        self.verticalLayout.addWidget(self.areaGroup)
        self.movementLabel.setBuddy(self.movement)
        self.speedLabel.setBuddy(self.speed)
        self.positionLabel.setBuddy(self.position)
        self.intensityChangeLabel.setBuddy(self.intensityChange)
        self.baseLabel.setBuddy(self.base)
        self.topLabel.setBuddy(self.top)
        self.eastLabel.setBuddy(self.east)
        self.westLabel.setBuddy(self.west)
        self.southLabel.setBuddy(self.south)
        self.northLabel.setBuddy(self.north)

        self.retranslateUi(Editor)
        QtCore.QMetaObject.connectSlotsByName(Editor)
        Editor.setTabOrder(self.movement, self.speed)
        Editor.setTabOrder(self.speed, self.position)
        Editor.setTabOrder(self.position, self.base)
        Editor.setTabOrder(self.base, self.top)
        Editor.setTabOrder(self.top, self.intensityChange)

    def retranslateUi(self, Editor):
        _translate = QtCore.QCoreApplication.translate
        self.descriptionGroup.setTitle(_translate("Editor", "Description"))
        self.movementLabel.setText(_translate("Editor", "Movement"))
        self.speedLabel.setText(_translate("Editor", "Speed"))
        self.positionLabel.setText(_translate("Editor", "Position"))
        self.intensityChangeLabel.setText(_translate("Editor", "Intensity Change"))
        self.baseLabel.setText(_translate("Editor", "FL Base"))
        self.topLabel.setText(_translate("Editor", "FL Top"))
        self.areaGroup.setTitle(_translate("Editor", "Area"))
        self.canvas.setText(_translate("Editor", "Canvas"))
        self.manual.setText(_translate("Editor", "Manual"))
        self.entire.setText(_translate("Editor", "Entire"))
        self.eastLabel.setText(_translate("Editor", "E OF"))
        self.westLabel.setText(_translate("Editor", "W OF"))
        self.longtitudeLabel.setText(_translate("Editor", "Longitude"))
        self.latitudeLabel.setText(_translate("Editor", "Latitude"))
        self.southLabel.setText(_translate("Editor", "S OF"))
        self.northLabel.setText(_translate("Editor", "N OF"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Editor = QtWidgets.QWidget()
    ui = Ui_Editor()
    ui.setupUi(Editor)
    Editor.show()
    sys.exit(app.exec_())

