# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Work\tafor\tafor\components\ui\sigmet_general.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Editor(object):
    def setupUi(self, Editor):
        Editor.setObjectName("Editor")
        Editor.resize(819, 70)
        Editor.setWindowTitle("Sigmet")
        self.layout = QtWidgets.QVBoxLayout(Editor)
        self.layout.setContentsMargins(-1, 0, -1, 0)
        self.layout.setObjectName("layout")
        self.descriptionGroup = QtWidgets.QGroupBox(Editor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.descriptionGroup.sizePolicy().hasHeightForWidth())
        self.descriptionGroup.setSizePolicy(sizePolicy)
        self.descriptionGroup.setObjectName("descriptionGroup")
        self.descriptionLayout = QtWidgets.QGridLayout(self.descriptionGroup)
        self.descriptionLayout.setObjectName("descriptionLayout")
        self.speed = QtWidgets.QLineEdit(self.descriptionGroup)
        self.speed.setObjectName("speed")
        self.descriptionLayout.addWidget(self.speed, 1, 6, 1, 1)
        self.top = QtWidgets.QLineEdit(self.descriptionGroup)
        self.top.setObjectName("top")
        self.descriptionLayout.addWidget(self.top, 1, 4, 1, 1)
        self.movement = QtWidgets.QComboBox(self.descriptionGroup)
        self.movement.setObjectName("movement")
        self.movement.addItem("")
        self.movement.setItemText(0, "N")
        self.movement.addItem("")
        self.movement.setItemText(1, "NNE")
        self.movement.addItem("")
        self.movement.setItemText(2, "NE")
        self.movement.addItem("")
        self.movement.setItemText(3, "ENE")
        self.movement.addItem("")
        self.movement.setItemText(4, "E")
        self.movement.addItem("")
        self.movement.setItemText(5, "ESE")
        self.movement.addItem("")
        self.movement.setItemText(6, "SE")
        self.movement.addItem("")
        self.movement.setItemText(7, "SSE")
        self.movement.addItem("")
        self.movement.setItemText(8, "S")
        self.movement.addItem("")
        self.movement.setItemText(9, "SSW")
        self.movement.addItem("")
        self.movement.setItemText(10, "SW")
        self.movement.addItem("")
        self.movement.setItemText(11, "WSW")
        self.movement.addItem("")
        self.movement.setItemText(12, "W")
        self.movement.addItem("")
        self.movement.setItemText(13, "WNW")
        self.movement.addItem("")
        self.movement.setItemText(14, "NW")
        self.movement.addItem("")
        self.movement.setItemText(15, "NNW")
        self.movement.addItem("")
        self.movement.setItemText(16, "STNR")
        self.descriptionLayout.addWidget(self.movement, 1, 5, 1, 1)
        self.intensityChange = QtWidgets.QComboBox(self.descriptionGroup)
        self.intensityChange.setObjectName("intensityChange")
        self.intensityChange.addItem("")
        self.intensityChange.setItemText(0, "NC")
        self.intensityChange.addItem("")
        self.intensityChange.setItemText(1, "INTSF")
        self.intensityChange.addItem("")
        self.intensityChange.setItemText(2, "WKN")
        self.descriptionLayout.addWidget(self.intensityChange, 1, 7, 1, 1)
        self.base = QtWidgets.QLineEdit(self.descriptionGroup)
        self.base.setObjectName("base")
        self.descriptionLayout.addWidget(self.base, 1, 3, 1, 1)
        self.topLabel = QtWidgets.QLabel(self.descriptionGroup)
        self.topLabel.setObjectName("topLabel")
        self.descriptionLayout.addWidget(self.topLabel, 0, 4, 1, 1)
        self.movementLabel = QtWidgets.QLabel(self.descriptionGroup)
        self.movementLabel.setObjectName("movementLabel")
        self.descriptionLayout.addWidget(self.movementLabel, 0, 5, 1, 1)
        self.levelLabel = QtWidgets.QLabel(self.descriptionGroup)
        self.levelLabel.setObjectName("levelLabel")
        self.descriptionLayout.addWidget(self.levelLabel, 0, 2, 1, 1)
        self.baseLabel = QtWidgets.QLabel(self.descriptionGroup)
        self.baseLabel.setObjectName("baseLabel")
        self.descriptionLayout.addWidget(self.baseLabel, 0, 3, 1, 1)
        self.level = QtWidgets.QComboBox(self.descriptionGroup)
        self.level.setObjectName("level")
        self.level.addItem("")
        self.level.setItemText(0, "")
        self.level.addItem("")
        self.level.setItemText(1, "TOP")
        self.level.addItem("")
        self.level.setItemText(2, "ABV")
        self.level.addItem("")
        self.level.setItemText(3, "BLW")
        self.level.addItem("")
        self.level.setItemText(4, "SFC")
        self.descriptionLayout.addWidget(self.level, 1, 2, 1, 1)
        self.speedLabel = QtWidgets.QLabel(self.descriptionGroup)
        self.speedLabel.setObjectName("speedLabel")
        self.descriptionLayout.addWidget(self.speedLabel, 0, 6, 1, 1)
        self.intensityChangeLabel = QtWidgets.QLabel(self.descriptionGroup)
        self.intensityChangeLabel.setObjectName("intensityChangeLabel")
        self.descriptionLayout.addWidget(self.intensityChangeLabel, 0, 7, 1, 1)
        self.forecastTime = QtWidgets.QLineEdit(self.descriptionGroup)
        self.forecastTime.setEnabled(False)
        self.forecastTime.setObjectName("forecastTime")
        self.descriptionLayout.addWidget(self.forecastTime, 1, 8, 1, 1)
        self.forecastTimeLabel = QtWidgets.QLabel(self.descriptionGroup)
        self.forecastTimeLabel.setEnabled(False)
        self.forecastTimeLabel.setObjectName("forecastTimeLabel")
        self.descriptionLayout.addWidget(self.forecastTimeLabel, 0, 8, 1, 1)
        self.layout.addWidget(self.descriptionGroup)
        self.topLabel.setBuddy(self.top)
        self.movementLabel.setBuddy(self.movement)
        self.levelLabel.setBuddy(self.level)
        self.baseLabel.setBuddy(self.base)
        self.speedLabel.setBuddy(self.speed)
        self.intensityChangeLabel.setBuddy(self.intensityChange)

        self.retranslateUi(Editor)
        QtCore.QMetaObject.connectSlotsByName(Editor)
        Editor.setTabOrder(self.level, self.base)
        Editor.setTabOrder(self.base, self.top)
        Editor.setTabOrder(self.top, self.movement)
        Editor.setTabOrder(self.movement, self.speed)
        Editor.setTabOrder(self.speed, self.intensityChange)

    def retranslateUi(self, Editor):
        _translate = QtCore.QCoreApplication.translate
        self.descriptionGroup.setTitle(_translate("Editor", "Description"))
        self.topLabel.setText(_translate("Editor", "FL Top"))
        self.movementLabel.setText(_translate("Editor", "Movement"))
        self.levelLabel.setText(_translate("Editor", "Fight Level"))
        self.baseLabel.setText(_translate("Editor", "FL Base"))
        self.speedLabel.setText(_translate("Editor", "Speed"))
        self.intensityChangeLabel.setText(_translate("Editor", "Intensity Change"))
        self.forecastTimeLabel.setText(_translate("Editor", "Forecast Time"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Editor = QtWidgets.QWidget()
    ui = Ui_Editor()
    ui.setupUi(Editor)
    Editor.show()
    sys.exit(app.exec_())

