# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Work\tafor\tafor\components\ui\trend.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Editor(object):
    def setupUi(self, Editor):
        Editor.setObjectName("Editor")
        Editor.resize(868, 185)
        Editor.setWindowTitle("Trend")
        self.verticalLayout = QtWidgets.QVBoxLayout(Editor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layout = QtWidgets.QGridLayout()
        self.layout.setObjectName("layout")
        self.cloud1Label = QtWidgets.QLabel(Editor)
        self.cloud1Label.setObjectName("cloud1Label")
        self.layout.addWidget(self.cloud1Label, 2, 8, 1, 1)
        self.gust = QtWidgets.QLineEdit(Editor)
        self.gust.setObjectName("gust")
        self.layout.addWidget(self.gust, 3, 3, 1, 1)
        self.vis = QtWidgets.QLineEdit(Editor)
        self.vis.setObjectName("vis")
        self.layout.addWidget(self.vis, 3, 4, 1, 1)
        self.cloud3Label = QtWidgets.QLabel(Editor)
        self.cloud3Label.setObjectName("cloud3Label")
        self.layout.addWidget(self.cloud3Label, 2, 10, 1, 1)
        self.typeGroup = QtWidgets.QGroupBox(Editor)
        self.typeGroup.setTitle("")
        self.typeGroup.setObjectName("typeGroup")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.typeGroup)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.becmg = QtWidgets.QRadioButton(self.typeGroup)
        self.becmg.setText("BECMG")
        self.becmg.setChecked(True)
        self.becmg.setObjectName("becmg")
        self.gridLayout_6.addWidget(self.becmg, 0, 0, 1, 1)
        self.tempo = QtWidgets.QRadioButton(self.typeGroup)
        self.tempo.setText("TEMPO")
        self.tempo.setObjectName("tempo")
        self.gridLayout_6.addWidget(self.tempo, 0, 1, 1, 1)
        self.layout.addWidget(self.typeGroup, 0, 0, 1, 3)
        self.weatherWithIntensityLabel = QtWidgets.QLabel(Editor)
        self.weatherWithIntensityLabel.setObjectName("weatherWithIntensityLabel")
        self.layout.addWidget(self.weatherWithIntensityLabel, 2, 6, 1, 1)
        self.cloud2 = QtWidgets.QLineEdit(Editor)
        self.cloud2.setObjectName("cloud2")
        self.layout.addWidget(self.cloud2, 3, 9, 1, 1)
        self.prefixGroup = QtWidgets.QGroupBox(Editor)
        self.prefixGroup.setTitle("")
        self.prefixGroup.setObjectName("prefixGroup")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.prefixGroup)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.at = QtWidgets.QCheckBox(self.prefixGroup)
        self.at.setText("AT")
        self.at.setCheckable(True)
        self.at.setObjectName("at")
        self.gridLayout_5.addWidget(self.at, 0, 2, 1, 1)
        self.fm = QtWidgets.QCheckBox(self.prefixGroup)
        self.fm.setText("FM")
        self.fm.setCheckable(True)
        self.fm.setObjectName("fm")
        self.gridLayout_5.addWidget(self.fm, 0, 0, 1, 1)
        self.tl = QtWidgets.QCheckBox(self.prefixGroup)
        self.tl.setText("TL")
        self.tl.setChecked(False)
        self.tl.setObjectName("tl")
        self.gridLayout_5.addWidget(self.tl, 0, 1, 1, 1)
        self.layout.addWidget(self.prefixGroup, 0, 3, 1, 2)
        self.cbLabel = QtWidgets.QLabel(Editor)
        self.cbLabel.setObjectName("cbLabel")
        self.layout.addWidget(self.cbLabel, 2, 11, 1, 1)
        self.cavok = QtWidgets.QCheckBox(Editor)
        self.cavok.setText("CAVOK")
        self.cavok.setCheckable(True)
        self.cavok.setObjectName("cavok")
        self.layout.addWidget(self.cavok, 4, 4, 1, 1)
        self.wind = QtWidgets.QLineEdit(Editor)
        self.wind.setObjectName("wind")
        self.layout.addWidget(self.wind, 3, 2, 1, 1)
        self.nsc = QtWidgets.QCheckBox(Editor)
        self.nsc.setText("NSC")
        self.nsc.setObjectName("nsc")
        self.layout.addWidget(self.nsc, 4, 9, 1, 1)
        self.cloud3 = QtWidgets.QLineEdit(Editor)
        self.cloud3.setObjectName("cloud3")
        self.layout.addWidget(self.cloud3, 3, 10, 1, 1)
        self.cloud2Label = QtWidgets.QLabel(Editor)
        self.cloud2Label.setObjectName("cloud2Label")
        self.layout.addWidget(self.cloud2Label, 2, 9, 1, 1)
        self.weatherWithIntensity = QtWidgets.QComboBox(Editor)
        self.weatherWithIntensity.setObjectName("weatherWithIntensity")
        self.layout.addWidget(self.weatherWithIntensity, 3, 6, 1, 1)
        self.skc = QtWidgets.QCheckBox(Editor)
        self.skc.setText("SKC")
        self.skc.setObjectName("skc")
        self.layout.addWidget(self.skc, 4, 8, 1, 1)
        self.period = QtWidgets.QLineEdit(Editor)
        self.period.setEnabled(False)
        self.period.setObjectName("period")
        self.layout.addWidget(self.period, 3, 1, 1, 1)
        self.periodLabel = QtWidgets.QLabel(Editor)
        self.periodLabel.setObjectName("periodLabel")
        self.layout.addWidget(self.periodLabel, 2, 1, 1, 1)
        self.gustLabel = QtWidgets.QLabel(Editor)
        self.gustLabel.setObjectName("gustLabel")
        self.layout.addWidget(self.gustLabel, 2, 3, 1, 1)
        self.windLabel = QtWidgets.QLabel(Editor)
        self.windLabel.setObjectName("windLabel")
        self.layout.addWidget(self.windLabel, 2, 2, 1, 1)
        self.cloud1 = QtWidgets.QLineEdit(Editor)
        self.cloud1.setObjectName("cloud1")
        self.layout.addWidget(self.cloud1, 3, 8, 1, 1)
        self.visLabel = QtWidgets.QLabel(Editor)
        self.visLabel.setObjectName("visLabel")
        self.layout.addWidget(self.visLabel, 2, 4, 1, 1)
        self.cb = QtWidgets.QLineEdit(Editor)
        self.cb.setObjectName("cb")
        self.layout.addWidget(self.cb, 3, 11, 1, 1)
        self.nosig = QtWidgets.QCheckBox(Editor)
        self.nosig.setText("NOSIG")
        self.nosig.setObjectName("nosig")
        self.layout.addWidget(self.nosig, 5, 1, 1, 1)
        self.weather = QtWidgets.QComboBox(Editor)
        self.weather.setObjectName("weather")
        self.layout.addWidget(self.weather, 3, 7, 1, 1)
        self.weatherLabel = QtWidgets.QLabel(Editor)
        self.weatherLabel.setObjectName("weatherLabel")
        self.layout.addWidget(self.weatherLabel, 2, 7, 1, 1)
        self.verticalLayout.addLayout(self.layout)
        self.cloud1Label.setBuddy(self.cloud1)
        self.cloud3Label.setBuddy(self.cloud3)
        self.weatherWithIntensityLabel.setBuddy(self.weatherWithIntensity)
        self.cbLabel.setBuddy(self.cb)
        self.cloud2Label.setBuddy(self.cloud2)
        self.periodLabel.setBuddy(self.period)
        self.gustLabel.setBuddy(self.gust)
        self.windLabel.setBuddy(self.wind)
        self.visLabel.setBuddy(self.vis)
        self.weatherLabel.setBuddy(self.weather)

        self.retranslateUi(Editor)
        QtCore.QMetaObject.connectSlotsByName(Editor)
        Editor.setTabOrder(self.becmg, self.tempo)
        Editor.setTabOrder(self.tempo, self.fm)
        Editor.setTabOrder(self.fm, self.tl)
        Editor.setTabOrder(self.tl, self.at)
        Editor.setTabOrder(self.at, self.period)
        Editor.setTabOrder(self.period, self.wind)
        Editor.setTabOrder(self.wind, self.gust)
        Editor.setTabOrder(self.gust, self.vis)
        Editor.setTabOrder(self.vis, self.weatherWithIntensity)
        Editor.setTabOrder(self.weatherWithIntensity, self.cloud1)
        Editor.setTabOrder(self.cloud1, self.cloud2)
        Editor.setTabOrder(self.cloud2, self.cloud3)
        Editor.setTabOrder(self.cloud3, self.cb)
        Editor.setTabOrder(self.cb, self.skc)
        Editor.setTabOrder(self.skc, self.nsc)

    def retranslateUi(self, Editor):
        _translate = QtCore.QCoreApplication.translate
        self.cloud1Label.setText(_translate("Editor", "Cloud1"))
        self.cloud3Label.setText(_translate("Editor", "Cloud3"))
        self.weatherWithIntensityLabel.setText(_translate("Editor", "Weather1"))
        self.cbLabel.setText(_translate("Editor", "Cumulonimbus"))
        self.cloud2Label.setText(_translate("Editor", "Cloud2"))
        self.periodLabel.setText(_translate("Editor", "Interval"))
        self.gustLabel.setText(_translate("Editor", "Gust"))
        self.windLabel.setText(_translate("Editor", "Wind"))
        self.visLabel.setText(_translate("Editor", "Visibility"))
        self.weatherLabel.setText(_translate("Editor", "Weather2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Editor = QtWidgets.QWidget()
    ui = Ui_Editor()
    ui.setupUi(Editor)
    Editor.show()
    sys.exit(app.exec_())

