# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Chen\Work\tafor\tafor\ui\main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(857, 662)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.main_tab.setMovable(True)
        self.main_tab.setObjectName("main_tab")
        self.tab_recent = QtWidgets.QWidget()
        self.tab_recent.setObjectName("tab_recent")
        self.recent_layout = QtWidgets.QVBoxLayout(self.tab_recent)
        self.recent_layout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.recent_layout.setContentsMargins(0, 0, 0, 0)
        self.recent_layout.setObjectName("recent_layout")
        self.main_tab.addTab(self.tab_recent, "")
        self.tab_taf = QtWidgets.QWidget()
        self.tab_taf.setObjectName("tab_taf")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_taf)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.taf_table = QtWidgets.QTableWidget(self.tab_taf)
        self.taf_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.taf_table.setObjectName("taf_table")
        self.taf_table.setColumnCount(5)
        self.taf_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.taf_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.taf_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.taf_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.taf_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.taf_table.setHorizontalHeaderItem(4, item)
        self.verticalLayout_2.addWidget(self.taf_table)
        self.main_tab.addTab(self.tab_taf, "")
        self.tab_metar = QtWidgets.QWidget()
        self.tab_metar.setObjectName("tab_metar")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_metar)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.metar_table = QtWidgets.QTableWidget(self.tab_metar)
        self.metar_table.setObjectName("metar_table")
        self.metar_table.setColumnCount(2)
        self.metar_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.metar_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.metar_table.setHorizontalHeaderItem(1, item)
        self.verticalLayout_3.addWidget(self.metar_table)
        self.main_tab.addTab(self.tab_metar, "")
        self.verticalLayout.addWidget(self.main_tab)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 857, 23))
        self.menubar.setObjectName("menubar")
        self.post_menu = QtWidgets.QMenu(self.menubar)
        self.post_menu.setObjectName("post_menu")
        self.setting_menu = QtWidgets.QMenu(self.menubar)
        self.setting_menu.setObjectName("setting_menu")
        self.help_menu = QtWidgets.QMenu(self.menubar)
        self.help_menu.setObjectName("help_menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.taf_action = QtWidgets.QAction(MainWindow)
        self.taf_action.setObjectName("taf_action")
        self.trend_action = QtWidgets.QAction(MainWindow)
        self.trend_action.setObjectName("trend_action")
        self.sigmet_action = QtWidgets.QAction(MainWindow)
        self.sigmet_action.setObjectName("sigmet_action")
        self.setting_action = QtWidgets.QAction(MainWindow)
        self.setting_action.setObjectName("setting_action")
        self.about_action = QtWidgets.QAction(MainWindow)
        self.about_action.setObjectName("about_action")
        self.warn_action = QtWidgets.QAction(MainWindow)
        self.warn_action.setCheckable(True)
        self.warn_action.setObjectName("warn_action")
        self.post_menu.addAction(self.taf_action)
        self.post_menu.addAction(self.sigmet_action)
        self.post_menu.addAction(self.trend_action)
        self.setting_menu.addAction(self.warn_action)
        self.setting_menu.addAction(self.setting_action)
        self.help_menu.addAction(self.about_action)
        self.menubar.addAction(self.post_menu.menuAction())
        self.menubar.addAction(self.setting_menu.menuAction())
        self.menubar.addAction(self.help_menu.menuAction())

        self.retranslateUi(MainWindow)
        self.main_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.tab_recent), _translate("MainWindow", "RECENT"))
        item = self.taf_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "类型"))
        item = self.taf_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "报文内容"))
        item = self.taf_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "发布时间"))
        item = self.taf_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "查询"))
        item = self.taf_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "其他"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.tab_taf), _translate("MainWindow", "TAF"))
        item = self.metar_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "类型"))
        item = self.metar_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "报文内容"))
        self.main_tab.setTabText(self.main_tab.indexOf(self.tab_metar), _translate("MainWindow", "METAR"))
        self.post_menu.setTitle(_translate("MainWindow", "编发"))
        self.setting_menu.setTitle(_translate("MainWindow", "设置"))
        self.help_menu.setTitle(_translate("MainWindow", "关于"))
        self.taf_action.setText(_translate("MainWindow", "预报"))
        self.trend_action.setText(_translate("MainWindow", "趋势"))
        self.sigmet_action.setText(_translate("MainWindow", "重要气象情报"))
        self.setting_action.setText(_translate("MainWindow", "首选项"))
        self.about_action.setText(_translate("MainWindow", "帮助"))
        self.warn_action.setText(_translate("MainWindow", "告警"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

