# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Chen\Work\tafor\tafor\ui\preference.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_preference(object):
    def setupUi(self, preference):
        preference.setObjectName("preference")
        preference.resize(622, 501)
        preference.setAcceptDrops(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(preference)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main = QtWidgets.QHBoxLayout()
        self.main.setObjectName("main")
        self.left_side = QtWidgets.QWidget(preference)
        self.left_side.setMaximumSize(QtCore.QSize(120, 16777215))
        self.left_side.setObjectName("left_side")
        self.leftbox = QtWidgets.QVBoxLayout(self.left_side)
        self.leftbox.setContentsMargins(0, 0, 0, 0)
        self.leftbox.setObjectName("leftbox")
        self.search = QtWidgets.QLineEdit(self.left_side)
        self.search.setObjectName("search")
        self.leftbox.addWidget(self.search)
        self.menu = QtWidgets.QListWidget(self.left_side)
        self.menu.setObjectName("menu")
        item = QtWidgets.QListWidgetItem()
        self.menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menu.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.menu.addItem(item)
        self.leftbox.addWidget(self.menu)
        self.main.addWidget(self.left_side)
        self.stacked = QtWidgets.QStackedWidget(preference)
        self.stacked.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stacked.setObjectName("stacked")
        self.convention_page = QtWidgets.QWidget()
        self.convention_page.setObjectName("convention_page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.convention_page)
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.convention_group = QtWidgets.QGroupBox(self.convention_page)
        self.convention_group.setObjectName("convention_group")
        self.formLayout_8 = QtWidgets.QFormLayout(self.convention_group)
        self.formLayout_8.setObjectName("formLayout_8")
        self.run_on_start = QtWidgets.QCheckBox(self.convention_group)
        self.run_on_start.setObjectName("run_on_start")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.run_on_start)
        self.close_to_minimize = QtWidgets.QCheckBox(self.convention_group)
        self.close_to_minimize.setObjectName("close_to_minimize")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.close_to_minimize)
        self.verticalLayout_6.addWidget(self.convention_group)
        self.backup_group = QtWidgets.QGroupBox(self.convention_page)
        self.backup_group.setObjectName("backup_group")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.backup_group)
        self.gridLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.import_path = QtWidgets.QLineEdit(self.backup_group)
        self.import_path.setObjectName("import_path")
        self.gridLayout_5.addWidget(self.import_path, 0, 0, 1, 1)
        self.export_button = QtWidgets.QPushButton(self.backup_group)
        self.export_button.setObjectName("export_button")
        self.gridLayout_5.addWidget(self.export_button, 1, 2, 1, 1)
        self.import_button = QtWidgets.QPushButton(self.backup_group)
        self.import_button.setObjectName("import_button")
        self.gridLayout_5.addWidget(self.import_button, 0, 2, 1, 1)
        self.import_explore = QtWidgets.QPushButton(self.backup_group)
        self.import_explore.setObjectName("import_explore")
        self.gridLayout_5.addWidget(self.import_explore, 0, 1, 1, 1)
        self.export_explore = QtWidgets.QPushButton(self.backup_group)
        self.export_explore.setObjectName("export_explore")
        self.gridLayout_5.addWidget(self.export_explore, 1, 1, 1, 1)
        self.export_path = QtWidgets.QLineEdit(self.backup_group)
        self.export_path.setObjectName("export_path")
        self.gridLayout_5.addWidget(self.export_path, 1, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.backup_group)
        self.stacked.addWidget(self.convention_page)
        self.message_page = QtWidgets.QWidget()
        self.message_page.setObjectName("message_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.message_page)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.prefix_group = QtWidgets.QGroupBox(self.message_page)
        self.prefix_group.setObjectName("prefix_group")
        self.formLayout = QtWidgets.QFormLayout(self.prefix_group)
        self.formLayout.setObjectName("formLayout")
        self.icao_label = QtWidgets.QLabel(self.prefix_group)
        self.icao_label.setObjectName("icao_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.icao_label)
        self.icao = QtWidgets.QLineEdit(self.prefix_group)
        self.icao.setObjectName("icao")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.icao)
        self.intelligence_label = QtWidgets.QLabel(self.prefix_group)
        self.intelligence_label.setObjectName("intelligence_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.intelligence_label)
        self.intelligence = QtWidgets.QLineEdit(self.prefix_group)
        self.intelligence.setObjectName("intelligence")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.intelligence)
        self.fir_label = QtWidgets.QLabel(self.prefix_group)
        self.fir_label.setObjectName("fir_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.fir_label)
        self.fir = QtWidgets.QLineEdit(self.prefix_group)
        self.fir.setObjectName("fir")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fir)
        self.trend_sign_label = QtWidgets.QLabel(self.prefix_group)
        self.trend_sign_label.setObjectName("trend_sign_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.trend_sign_label)
        self.trend_sign = QtWidgets.QLineEdit(self.prefix_group)
        self.trend_sign.setObjectName("trend_sign")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.trend_sign)
        self.verticalLayout_2.addWidget(self.prefix_group)
        self.weather_group = QtWidgets.QGroupBox(self.message_page)
        self.weather_group.setObjectName("weather_group")
        self.gridLayout = QtWidgets.QGridLayout(self.weather_group)
        self.gridLayout.setObjectName("gridLayout")
        self.add_wx1_layout = QtWidgets.QHBoxLayout()
        self.add_wx1_layout.setObjectName("add_wx1_layout")
        self.weather1 = QtWidgets.QLineEdit(self.weather_group)
        self.weather1.setText("")
        self.weather1.setObjectName("weather1")
        self.add_wx1_layout.addWidget(self.weather1)
        self.add_weather1_button = QtWidgets.QPushButton(self.weather_group)
        self.add_weather1_button.setMaximumSize(QtCore.QSize(25, 16777215))
        self.add_weather1_button.setObjectName("add_weather1_button")
        self.add_wx1_layout.addWidget(self.add_weather1_button)
        self.del_weather1_button = QtWidgets.QPushButton(self.weather_group)
        self.del_weather1_button.setMaximumSize(QtCore.QSize(25, 16777215))
        self.del_weather1_button.setObjectName("del_weather1_button")
        self.add_wx1_layout.addWidget(self.del_weather1_button)
        self.gridLayout.addLayout(self.add_wx1_layout, 0, 0, 1, 1)
        self.add_wx2_layout = QtWidgets.QHBoxLayout()
        self.add_wx2_layout.setObjectName("add_wx2_layout")
        self.weather2 = QtWidgets.QLineEdit(self.weather_group)
        self.weather2.setObjectName("weather2")
        self.add_wx2_layout.addWidget(self.weather2)
        self.add_weather2_button = QtWidgets.QPushButton(self.weather_group)
        self.add_weather2_button.setMaximumSize(QtCore.QSize(25, 16777215))
        self.add_weather2_button.setObjectName("add_weather2_button")
        self.add_wx2_layout.addWidget(self.add_weather2_button)
        self.del_weather2_button = QtWidgets.QPushButton(self.weather_group)
        self.del_weather2_button.setMaximumSize(QtCore.QSize(25, 16777215))
        self.del_weather2_button.setObjectName("del_weather2_button")
        self.add_wx2_layout.addWidget(self.del_weather2_button)
        self.gridLayout.addLayout(self.add_wx2_layout, 0, 1, 1, 1)
        self.weather1_list = QtWidgets.QListWidget(self.weather_group)
        self.weather1_list.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.weather1_list.setObjectName("weather1_list")
        self.gridLayout.addWidget(self.weather1_list, 1, 0, 1, 1)
        self.weather2_list = QtWidgets.QListWidget(self.weather_group)
        self.weather2_list.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.weather2_list.setObjectName("weather2_list")
        self.gridLayout.addWidget(self.weather2_list, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.weather_group)
        self.stacked.addWidget(self.message_page)
        self.communication_page = QtWidgets.QWidget()
        self.communication_page.setObjectName("communication_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.communication_page)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.top_layout = QtWidgets.QHBoxLayout()
        self.top_layout.setObjectName("top_layout")
        self.serial_group = QtWidgets.QGroupBox(self.communication_page)
        self.serial_group.setObjectName("serial_group")
        self.formLayout_3 = QtWidgets.QFormLayout(self.serial_group)
        self.formLayout_3.setObjectName("formLayout_3")
        self.port_label = QtWidgets.QLabel(self.serial_group)
        self.port_label.setObjectName("port_label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.port_label)
        self.port = QtWidgets.QLineEdit(self.serial_group)
        self.port.setObjectName("port")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.port)
        self.baudrate_label = QtWidgets.QLabel(self.serial_group)
        self.baudrate_label.setObjectName("baudrate_label")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.baudrate_label)
        self.baudrate = QtWidgets.QLineEdit(self.serial_group)
        self.baudrate.setObjectName("baudrate")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.baudrate)
        self.parity_label = QtWidgets.QLabel(self.serial_group)
        self.parity_label.setObjectName("parity_label")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.parity_label)
        self.parity = QtWidgets.QComboBox(self.serial_group)
        self.parity.setObjectName("parity")
        self.parity.addItem("")
        self.parity.addItem("")
        self.parity.addItem("")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.parity)
        self.bytesize_label = QtWidgets.QLabel(self.serial_group)
        self.bytesize_label.setObjectName("bytesize_label")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.bytesize_label)
        self.bytesize = QtWidgets.QComboBox(self.serial_group)
        self.bytesize.setObjectName("bytesize")
        self.bytesize.addItem("")
        self.bytesize.addItem("")
        self.bytesize.addItem("")
        self.bytesize.addItem("")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.bytesize)
        self.stopbits_label = QtWidgets.QLabel(self.serial_group)
        self.stopbits_label.setObjectName("stopbits_label")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.stopbits_label)
        self.stopbits = QtWidgets.QComboBox(self.serial_group)
        self.stopbits.setObjectName("stopbits")
        self.stopbits.addItem("")
        self.stopbits.addItem("")
        self.stopbits.addItem("")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.stopbits)
        self.top_layout.addWidget(self.serial_group)
        self.other_group = QtWidgets.QGroupBox(self.communication_page)
        self.other_group.setObjectName("other_group")
        self.formLayout_7 = QtWidgets.QFormLayout(self.other_group)
        self.formLayout_7.setObjectName("formLayout_7")
        self.channel_label = QtWidgets.QLabel(self.other_group)
        self.channel_label.setObjectName("channel_label")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.channel_label)
        self.channel = QtWidgets.QLineEdit(self.other_group)
        self.channel.setObjectName("channel")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.channel)
        self.number_label = QtWidgets.QLabel(self.other_group)
        self.number_label.setObjectName("number_label")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.number_label)
        self.number = QtWidgets.QLineEdit(self.other_group)
        self.number.setObjectName("number")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.number)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_7.setItem(2, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.request_addr = QtWidgets.QLineEdit(self.other_group)
        self.request_addr.setObjectName("request_addr")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.request_addr)
        self.request_addr_label = QtWidgets.QLabel(self.other_group)
        self.request_addr_label.setObjectName("request_addr_label")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.request_addr_label)
        self.user_addr = QtWidgets.QLineEdit(self.other_group)
        self.user_addr.setObjectName("user_addr")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.user_addr)
        self.user_addr_label = QtWidgets.QLabel(self.other_group)
        self.user_addr_label.setObjectName("user_addr_label")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.user_addr_label)
        self.top_layout.addWidget(self.other_group)
        self.verticalLayout_4.addLayout(self.top_layout)
        self.address_group = QtWidgets.QGroupBox(self.communication_page)
        self.address_group.setObjectName("address_group")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.address_group)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tabWidget = QtWidgets.QTabWidget(self.address_group)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_taf = QtWidgets.QWidget()
        self.tab_taf.setObjectName("tab_taf")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_taf)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.taf = QtWidgets.QTextEdit(self.tab_taf)
        self.taf.setObjectName("taf")
        self.verticalLayout_3.addWidget(self.taf)
        self.tabWidget.addTab(self.tab_taf, "")
        self.tab_sigmet = QtWidgets.QWidget()
        self.tab_sigmet.setObjectName("tab_sigmet")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_sigmet)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.sigmet = QtWidgets.QTextEdit(self.tab_sigmet)
        self.sigmet.setObjectName("sigmet")
        self.verticalLayout_7.addWidget(self.sigmet)
        self.tabWidget.addTab(self.tab_sigmet, "")
        self.tab_airmet = QtWidgets.QWidget()
        self.tab_airmet.setObjectName("tab_airmet")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_airmet)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.airmet = QtWidgets.QTextEdit(self.tab_airmet)
        self.airmet.setObjectName("airmet")
        self.verticalLayout_8.addWidget(self.airmet)
        self.tabWidget.addTab(self.tab_airmet, "")
        self.tab_trend = QtWidgets.QWidget()
        self.tab_trend.setObjectName("tab_trend")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_trend)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.trend = QtWidgets.QTextEdit(self.tab_trend)
        self.trend.setObjectName("trend")
        self.verticalLayout_9.addWidget(self.trend)
        self.tabWidget.addTab(self.tab_trend, "")
        self.verticalLayout_10.addWidget(self.tabWidget)
        self.verticalLayout_4.addWidget(self.address_group)
        self.stacked.addWidget(self.communication_page)
        self.monitor_page = QtWidgets.QWidget()
        self.monitor_page.setObjectName("monitor_page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.monitor_page)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.db_source_group = QtWidgets.QGroupBox(self.monitor_page)
        self.db_source_group.setObjectName("db_source_group")
        self.formLayout_6 = QtWidgets.QFormLayout(self.db_source_group)
        self.formLayout_6.setObjectName("formLayout_6")
        self.sydb = QtWidgets.QRadioButton(self.db_source_group)
        self.sydb.setChecked(True)
        self.sydb.setObjectName("sydb")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.sydb)
        self.sydb_url = QtWidgets.QLineEdit(self.db_source_group)
        self.sydb_url.setObjectName("sydb_url")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sydb_url)
        self.web = QtWidgets.QRadioButton(self.db_source_group)
        self.web.setObjectName("web")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.web)
        self.web_url = QtWidgets.QLineEdit(self.db_source_group)
        self.web_url.setObjectName("web_url")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.web_url)
        self.verticalLayout_5.addWidget(self.db_source_group)
        self.clock_group = QtWidgets.QGroupBox(self.monitor_page)
        self.clock_group.setObjectName("clock_group")
        self.formLayout_5 = QtWidgets.QFormLayout(self.clock_group)
        self.formLayout_5.setObjectName("formLayout_5")
        self.clock = QtWidgets.QCheckBox(self.clock_group)
        self.clock.setObjectName("clock")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.clock)
        self.clock_time_label = QtWidgets.QLabel(self.clock_group)
        self.clock_time_label.setObjectName("clock_time_label")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.clock_time_label)
        self.clock_time = QtWidgets.QLineEdit(self.clock_group)
        self.clock_time.setMaximumSize(QtCore.QSize(120, 16777215))
        self.clock_time.setObjectName("clock_time")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.clock_time)
        self.clock_volume_label = QtWidgets.QLabel(self.clock_group)
        self.clock_volume_label.setObjectName("clock_volume_label")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.clock_volume_label)
        self.clock_volume = QtWidgets.QSlider(self.clock_group)
        self.clock_volume.setOrientation(QtCore.Qt.Horizontal)
        self.clock_volume.setObjectName("clock_volume")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.clock_volume)
        self.verticalLayout_5.addWidget(self.clock_group)
        self.sound_group = QtWidgets.QGroupBox(self.monitor_page)
        self.sound_group.setObjectName("sound_group")
        self.formLayout_2 = QtWidgets.QFormLayout(self.sound_group)
        self.formLayout_2.setObjectName("formLayout_2")
        self.warn_taf = QtWidgets.QCheckBox(self.sound_group)
        self.warn_taf.setObjectName("warn_taf")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.warn_taf)
        self.warn_taf_volume = QtWidgets.QSlider(self.sound_group)
        self.warn_taf_volume.setOrientation(QtCore.Qt.Horizontal)
        self.warn_taf_volume.setObjectName("warn_taf_volume")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.warn_taf_volume)
        self.warn_trend = QtWidgets.QCheckBox(self.sound_group)
        self.warn_trend.setObjectName("warn_trend")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.warn_trend)
        self.warn_trend_volume = QtWidgets.QSlider(self.sound_group)
        self.warn_trend_volume.setOrientation(QtCore.Qt.Horizontal)
        self.warn_trend_volume.setObjectName("warn_trend_volume")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.warn_trend_volume)
        self.warn_sigmet = QtWidgets.QCheckBox(self.sound_group)
        self.warn_sigmet.setObjectName("warn_sigmet")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.warn_sigmet)
        self.warn_sigmet_volume = QtWidgets.QSlider(self.sound_group)
        self.warn_sigmet_volume.setOrientation(QtCore.Qt.Horizontal)
        self.warn_sigmet_volume.setObjectName("warn_sigmet_volume")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.warn_sigmet_volume)
        self.verticalLayout_5.addWidget(self.sound_group)
        self.phone_group = QtWidgets.QGroupBox(self.monitor_page)
        self.phone_group.setObjectName("phone_group")
        self.formLayout_4 = QtWidgets.QFormLayout(self.phone_group)
        self.formLayout_4.setObjectName("formLayout_4")
        self.phone_warn_taf = QtWidgets.QCheckBox(self.phone_group)
        self.phone_warn_taf.setObjectName("phone_warn_taf")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.phone_warn_taf)
        self.warn_taf_time_label = QtWidgets.QLabel(self.phone_group)
        self.warn_taf_time_label.setObjectName("warn_taf_time_label")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.warn_taf_time_label)
        self.warn_taf_time = QtWidgets.QLineEdit(self.phone_group)
        self.warn_taf_time.setMaximumSize(QtCore.QSize(120, 16777215))
        self.warn_taf_time.setObjectName("warn_taf_time")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.warn_taf_time)
        self.call_service_url_label = QtWidgets.QLabel(self.phone_group)
        self.call_service_url_label.setObjectName("call_service_url_label")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.call_service_url_label)
        self.call_service_url = QtWidgets.QLineEdit(self.phone_group)
        self.call_service_url.setObjectName("call_service_url")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.call_service_url)
        self.call_service_auth_label = QtWidgets.QLabel(self.phone_group)
        self.call_service_auth_label.setObjectName("call_service_auth_label")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.call_service_auth_label)
        self.call_service_auth = QtWidgets.QLineEdit(self.phone_group)
        self.call_service_auth.setObjectName("call_service_auth")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.call_service_auth)
        self.verticalLayout_5.addWidget(self.phone_group)
        self.stacked.addWidget(self.monitor_page)
        self.contract_page = QtWidgets.QWidget()
        self.contract_page.setObjectName("contract_page")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.contract_page)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.contract_group = QtWidgets.QGroupBox(self.contract_page)
        self.contract_group.setObjectName("contract_group")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.contract_group)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.add_person_layout = QtWidgets.QHBoxLayout()
        self.add_person_layout.setObjectName("add_person_layout")
        self.person_name = QtWidgets.QLineEdit(self.contract_group)
        self.person_name.setText("")
        self.person_name.setObjectName("person_name")
        self.add_person_layout.addWidget(self.person_name)
        self.person_phone_number = QtWidgets.QLineEdit(self.contract_group)
        self.person_phone_number.setObjectName("person_phone_number")
        self.add_person_layout.addWidget(self.person_phone_number)
        self.add_person_button = QtWidgets.QPushButton(self.contract_group)
        self.add_person_button.setMaximumSize(QtCore.QSize(25, 16777215))
        self.add_person_button.setObjectName("add_person_button")
        self.add_person_layout.addWidget(self.add_person_button)
        self.del_person_button = QtWidgets.QPushButton(self.contract_group)
        self.del_person_button.setMaximumSize(QtCore.QSize(25, 16777215))
        self.del_person_button.setObjectName("del_person_button")
        self.add_person_layout.addWidget(self.del_person_button)
        self.verticalLayout_12.addLayout(self.add_person_layout)
        self.contract_table = QtWidgets.QTableWidget(self.contract_group)
        self.contract_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.contract_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.contract_table.setObjectName("contract_table")
        self.contract_table.setColumnCount(2)
        self.contract_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.contract_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.contract_table.setHorizontalHeaderItem(1, item)
        self.contract_table.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_12.addWidget(self.contract_table)
        self.select_contract_layout = QtWidgets.QHBoxLayout()
        self.select_contract_layout.setObjectName("select_contract_layout")
        self.select_contract_label = QtWidgets.QLabel(self.contract_group)
        self.select_contract_label.setObjectName("select_contract_label")
        self.select_contract_layout.addWidget(self.select_contract_label)
        self.select_contract = QtWidgets.QComboBox(self.contract_group)
        self.select_contract.setObjectName("select_contract")
        self.select_contract_layout.addWidget(self.select_contract)
        self.verticalLayout_12.addLayout(self.select_contract_layout)
        self.verticalLayout_11.addWidget(self.contract_group)
        self.stacked.addWidget(self.contract_page)
        self.main.addWidget(self.stacked)
        self.verticalLayout.addLayout(self.main)
        self.button_box = QtWidgets.QDialogButtonBox(preference)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Reset)
        self.button_box.setObjectName("button_box")
        self.verticalLayout.addWidget(self.button_box)

        self.retranslateUi(preference)
        self.stacked.setCurrentIndex(2)
        self.tabWidget.setCurrentIndex(0)
        self.button_box.accepted.connect(preference.accept)
        self.button_box.rejected.connect(preference.reject)
        self.menu.currentRowChanged['int'].connect(self.stacked.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(preference)
        preference.setTabOrder(self.search, self.menu)
        preference.setTabOrder(self.menu, self.icao)
        preference.setTabOrder(self.icao, self.intelligence)
        preference.setTabOrder(self.intelligence, self.fir)
        preference.setTabOrder(self.fir, self.trend_sign)
        preference.setTabOrder(self.trend_sign, self.weather1)
        preference.setTabOrder(self.weather1, self.add_weather1_button)
        preference.setTabOrder(self.add_weather1_button, self.del_weather1_button)
        preference.setTabOrder(self.del_weather1_button, self.weather1_list)
        preference.setTabOrder(self.weather1_list, self.weather2)
        preference.setTabOrder(self.weather2, self.add_weather2_button)
        preference.setTabOrder(self.add_weather2_button, self.del_weather2_button)
        preference.setTabOrder(self.del_weather2_button, self.weather2_list)
        preference.setTabOrder(self.weather2_list, self.port)
        preference.setTabOrder(self.port, self.baudrate)
        preference.setTabOrder(self.baudrate, self.parity)
        preference.setTabOrder(self.parity, self.bytesize)
        preference.setTabOrder(self.bytesize, self.stopbits)
        preference.setTabOrder(self.stopbits, self.channel)
        preference.setTabOrder(self.channel, self.number)
        preference.setTabOrder(self.number, self.request_addr)
        preference.setTabOrder(self.request_addr, self.user_addr)
        preference.setTabOrder(self.user_addr, self.tabWidget)
        preference.setTabOrder(self.tabWidget, self.taf)
        preference.setTabOrder(self.taf, self.sigmet)
        preference.setTabOrder(self.sigmet, self.airmet)
        preference.setTabOrder(self.airmet, self.trend)
        preference.setTabOrder(self.trend, self.clock)
        preference.setTabOrder(self.clock, self.clock_time)
        preference.setTabOrder(self.clock_time, self.clock_volume)
        preference.setTabOrder(self.clock_volume, self.warn_taf)
        preference.setTabOrder(self.warn_taf, self.warn_taf_volume)
        preference.setTabOrder(self.warn_taf_volume, self.warn_trend)
        preference.setTabOrder(self.warn_trend, self.warn_trend_volume)
        preference.setTabOrder(self.warn_trend_volume, self.warn_sigmet)
        preference.setTabOrder(self.warn_sigmet, self.warn_sigmet_volume)
        preference.setTabOrder(self.warn_sigmet_volume, self.phone_warn_taf)
        preference.setTabOrder(self.phone_warn_taf, self.warn_taf_time)
        preference.setTabOrder(self.warn_taf_time, self.run_on_start)
        preference.setTabOrder(self.run_on_start, self.close_to_minimize)
        preference.setTabOrder(self.close_to_minimize, self.import_path)
        preference.setTabOrder(self.import_path, self.import_explore)
        preference.setTabOrder(self.import_explore, self.import_button)
        preference.setTabOrder(self.import_button, self.export_path)
        preference.setTabOrder(self.export_path, self.export_explore)
        preference.setTabOrder(self.export_explore, self.export_button)

    def retranslateUi(self, preference):
        _translate = QtCore.QCoreApplication.translate
        preference.setWindowTitle(_translate("preference", "设置"))
        __sortingEnabled = self.menu.isSortingEnabled()
        self.menu.setSortingEnabled(False)
        item = self.menu.item(0)
        item.setText(_translate("preference", "常规"))
        item = self.menu.item(1)
        item.setText(_translate("preference", "编报"))
        item = self.menu.item(2)
        item.setText(_translate("preference", "通信"))
        item = self.menu.item(3)
        item.setText(_translate("preference", "监控"))
        item = self.menu.item(4)
        item.setText(_translate("preference", "联系人"))
        self.menu.setSortingEnabled(__sortingEnabled)
        self.convention_group.setTitle(_translate("preference", "常规"))
        self.run_on_start.setText(_translate("preference", "开机自动启动"))
        self.close_to_minimize.setText(_translate("preference", "关闭时最小化到系统托盘"))
        self.backup_group.setTitle(_translate("preference", "备份"))
        self.import_path.setPlaceholderText(_translate("preference", "PATH"))
        self.export_button.setText(_translate("preference", "导出"))
        self.import_button.setText(_translate("preference", "导入"))
        self.import_explore.setText(_translate("preference", "浏览"))
        self.export_explore.setText(_translate("preference", "浏览"))
        self.export_path.setPlaceholderText(_translate("preference", "PATH"))
        self.prefix_group.setTitle(_translate("preference", "前缀"))
        self.icao_label.setText(_translate("preference", "机场代码"))
        self.icao.setPlaceholderText(_translate("preference", "ZJHK"))
        self.intelligence_label.setText(_translate("preference", "气象情报"))
        self.intelligence.setPlaceholderText(_translate("preference", "CI35"))
        self.fir_label.setText(_translate("preference", "监视台责任区"))
        self.fir.setPlaceholderText(_translate("preference", "ZJSA SANYA FIR"))
        self.trend_sign_label.setText(_translate("preference", "趋势识别码"))
        self.trend_sign.setPlaceholderText(_translate("preference", "TREND"))
        self.weather_group.setTitle(_translate("preference", "天气现象备案"))
        self.weather1.setPlaceholderText(_translate("preference", "无强度变化的天气现象"))
        self.add_weather1_button.setText(_translate("preference", "+"))
        self.del_weather1_button.setText(_translate("preference", "—"))
        self.weather2.setPlaceholderText(_translate("preference", "有强度变化的天气现象"))
        self.add_weather2_button.setText(_translate("preference", "+"))
        self.del_weather2_button.setText(_translate("preference", "—"))
        self.serial_group.setTitle(_translate("preference", "串口参数"))
        self.port_label.setText(_translate("preference", "端口"))
        self.port.setPlaceholderText(_translate("preference", "COM1"))
        self.baudrate_label.setText(_translate("preference", "波特率"))
        self.baudrate.setPlaceholderText(_translate("preference", "9600"))
        self.parity_label.setText(_translate("preference", "校验位"))
        self.parity.setItemText(0, _translate("preference", "NONE"))
        self.parity.setItemText(1, _translate("preference", "EVEN"))
        self.parity.setItemText(2, _translate("preference", "ODD"))
        self.bytesize_label.setText(_translate("preference", "数据位"))
        self.bytesize.setItemText(0, _translate("preference", "5"))
        self.bytesize.setItemText(1, _translate("preference", "6"))
        self.bytesize.setItemText(2, _translate("preference", "7"))
        self.bytesize.setItemText(3, _translate("preference", "8"))
        self.stopbits_label.setText(_translate("preference", "停止位"))
        self.stopbits.setItemText(0, _translate("preference", "1"))
        self.stopbits.setItemText(1, _translate("preference", "1.5"))
        self.stopbits.setItemText(2, _translate("preference", "2"))
        self.other_group.setTitle(_translate("preference", "其他"))
        self.channel_label.setText(_translate("preference", "线路冠字"))
        self.channel.setPlaceholderText(_translate("preference", "YMA"))
        self.number_label.setText(_translate("preference", "流水号"))
        self.number.setPlaceholderText(_translate("preference", "1"))
        self.request_addr.setPlaceholderText(_translate("preference", "ZGGGYZYX"))
        self.request_addr_label.setText(_translate("preference", "请求地址"))
        self.user_addr.setPlaceholderText(_translate("preference", "ZJHKYMYX"))
        self.user_addr_label.setText(_translate("preference", "用户单位"))
        self.address_group.setTitle(_translate("preference", "发报地址"))
        self.taf.setPlaceholderText(_translate("preference", "发报地址请以空格分隔"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_taf), _translate("preference", "TAF"))
        self.sigmet.setPlaceholderText(_translate("preference", "发报地址请以空格分隔"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_sigmet), _translate("preference", "SIGMET"))
        self.airmet.setPlaceholderText(_translate("preference", "发报地址请以空格分隔"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_airmet), _translate("preference", "AIRMET"))
        self.trend.setPlaceholderText(_translate("preference", "发报地址请以空格分隔"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_trend), _translate("preference", "TREND"))
        self.db_source_group.setTitle(_translate("preference", "监控数据源"))
        self.sydb.setText(_translate("preference", "三亚区管数据库"))
        self.web.setText(_translate("preference", "中南综合信息服务系统"))
        self.clock_group.setTitle(_translate("preference", "闹钟和音量"))
        self.clock.setText(_translate("preference", "启用    "))
        self.clock_time_label.setText(_translate("preference", "闹铃时间        "))
        self.clock_time.setPlaceholderText(_translate("preference", "单位分钟"))
        self.clock_volume_label.setText(_translate("preference", "音量"))
        self.sound_group.setTitle(_translate("preference", "声音提醒和音量"))
        self.warn_taf.setText(_translate("preference", "报文迟发"))
        self.warn_trend.setText(_translate("preference", "趋势预报"))
        self.warn_sigmet.setText(_translate("preference", "重要气象情报"))
        self.phone_group.setTitle(_translate("preference", "电话"))
        self.phone_warn_taf.setText(_translate("preference", "报文迟发"))
        self.warn_taf_time_label.setText(_translate("preference", "提醒时间        "))
        self.warn_taf_time.setPlaceholderText(_translate("preference", "单位分钟"))
        self.call_service_url_label.setText(_translate("preference", "请求地址"))
        self.call_service_url.setPlaceholderText(_translate("preference", "URL"))
        self.call_service_auth_label.setText(_translate("preference", "认证"))
        self.call_service_auth.setPlaceholderText(_translate("preference", "AUTH"))
        self.contract_group.setTitle(_translate("preference", "联系人"))
        self.person_name.setPlaceholderText(_translate("preference", "姓名"))
        self.person_phone_number.setPlaceholderText(_translate("preference", "电话"))
        self.add_person_button.setText(_translate("preference", "+"))
        self.del_person_button.setText(_translate("preference", "—"))
        item = self.contract_table.horizontalHeaderItem(0)
        item.setText(_translate("preference", "姓名"))
        item = self.contract_table.horizontalHeaderItem(1)
        item.setText(_translate("preference", "电话"))
        self.select_contract_label.setText(_translate("preference", "当前设置告警号码"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    preference = QtWidgets.QDialog()
    ui = Ui_preference()
    ui.setupUi(preference)
    preference.show()
    sys.exit(app.exec_())

