# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Work\tafor\tafor\ui\taf.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TAF(object):
    def setupUi(self, TAF):
        TAF.setObjectName(_fromUtf8("TAF"))
        TAF.resize(1024, 665)
        TAF.setMaximumSize(QtCore.QSize(1024, 16777215))
        self.verticalLayout = QtGui.QVBoxLayout(TAF)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.main_frame = QtGui.QFrame(TAF)
        self.main_frame.setMaximumSize(QtCore.QSize(16777215, 172))
        self.main_frame.setObjectName(_fromUtf8("main_frame"))
        self.main = QtGui.QVBoxLayout(self.main_frame)
        self.main.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.main.setObjectName(_fromUtf8("main"))
        self.main_layout = QtGui.QGridLayout()
        self.main_layout.setObjectName(_fromUtf8("main_layout"))
        self.tempo1_checkbox = QtGui.QCheckBox(self.main_frame)
        self.tempo1_checkbox.setObjectName(_fromUtf8("tempo1_checkbox"))
        self.main_layout.addWidget(self.tempo1_checkbox, 5, 1, 1, 1)
        self.becmg2_checkbox = QtGui.QCheckBox(self.main_frame)
        self.becmg2_checkbox.setObjectName(_fromUtf8("becmg2_checkbox"))
        self.main_layout.addWidget(self.becmg2_checkbox, 6, 0, 1, 1)
        self.taf_cloud1_label = QtGui.QLabel(self.main_frame)
        self.taf_cloud1_label.setObjectName(_fromUtf8("taf_cloud1_label"))
        self.main_layout.addWidget(self.taf_cloud1_label, 2, 7, 1, 1)
        self.taf_cloud2_label = QtGui.QLabel(self.main_frame)
        self.taf_cloud2_label.setObjectName(_fromUtf8("taf_cloud2_label"))
        self.main_layout.addWidget(self.taf_cloud2_label, 2, 8, 1, 1)
        self.taf_cloud2 = QtGui.QLineEdit(self.main_frame)
        self.taf_cloud2.setObjectName(_fromUtf8("taf_cloud2"))
        self.main_layout.addWidget(self.taf_cloud2, 3, 8, 1, 1)
        self.taf_gust = QtGui.QLineEdit(self.main_frame)
        self.taf_gust.setObjectName(_fromUtf8("taf_gust"))
        self.main_layout.addWidget(self.taf_gust, 3, 3, 1, 1)
        self.taf_skc = QtGui.QCheckBox(self.main_frame)
        self.taf_skc.setObjectName(_fromUtf8("taf_skc"))
        self.main_layout.addWidget(self.taf_skc, 4, 7, 1, 1)
        self.taf_nsc = QtGui.QCheckBox(self.main_frame)
        self.taf_nsc.setObjectName(_fromUtf8("taf_nsc"))
        self.main_layout.addWidget(self.taf_nsc, 4, 8, 1, 1)
        self.taf_cloud3_label = QtGui.QLabel(self.main_frame)
        self.taf_cloud3_label.setObjectName(_fromUtf8("taf_cloud3_label"))
        self.main_layout.addWidget(self.taf_cloud3_label, 2, 9, 1, 1)
        self.taf_weather1_combobox = QtGui.QComboBox(self.main_frame)
        self.taf_weather1_combobox.setObjectName(_fromUtf8("taf_weather1_combobox"))
        self.main_layout.addWidget(self.taf_weather1_combobox, 3, 5, 1, 1)
        self.taf_weather2_combobox = QtGui.QComboBox(self.main_frame)
        self.taf_weather2_combobox.setObjectName(_fromUtf8("taf_weather2_combobox"))
        self.main_layout.addWidget(self.taf_weather2_combobox, 3, 6, 1, 1)
        self.taf_vis = QtGui.QLineEdit(self.main_frame)
        self.taf_vis.setObjectName(_fromUtf8("taf_vis"))
        self.main_layout.addWidget(self.taf_vis, 3, 4, 1, 1)
        self.taf_temp_min = QtGui.QLineEdit(self.main_frame)
        self.taf_temp_min.setObjectName(_fromUtf8("taf_temp_min"))
        self.main_layout.addWidget(self.taf_temp_min, 6, 10, 1, 1)
        self.cls_amd_combobox = QtGui.QComboBox(self.main_frame)
        self.cls_amd_combobox.setObjectName(_fromUtf8("cls_amd_combobox"))
        self.main_layout.addWidget(self.cls_amd_combobox, 0, 8, 1, 1)
        self.cls_cor_combobox = QtGui.QComboBox(self.main_frame)
        self.cls_cor_combobox.setObjectName(_fromUtf8("cls_cor_combobox"))
        self.main_layout.addWidget(self.cls_cor_combobox, 0, 6, 1, 1)
        self.cls_cnl = QtGui.QRadioButton(self.main_frame)
        self.cls_cnl.setObjectName(_fromUtf8("cls_cnl"))
        self.main_layout.addWidget(self.cls_cnl, 0, 9, 1, 1, QtCore.Qt.AlignRight)
        self.cls_normal = QtGui.QRadioButton(self.main_frame)
        self.cls_normal.setChecked(True)
        self.cls_normal.setObjectName(_fromUtf8("cls_normal"))
        self.main_layout.addWidget(self.cls_normal, 0, 4, 1, 1)
        self.taf_temp_min_label = QtGui.QLabel(self.main_frame)
        self.taf_temp_min_label.setObjectName(_fromUtf8("taf_temp_min_label"))
        self.main_layout.addWidget(self.taf_temp_min_label, 5, 10, 1, 1)
        self.cls_cnl_combobox = QtGui.QComboBox(self.main_frame)
        self.cls_cnl_combobox.setObjectName(_fromUtf8("cls_cnl_combobox"))
        self.main_layout.addWidget(self.cls_cnl_combobox, 0, 10, 1, 1)
        self.tempo2_checkbox = QtGui.QCheckBox(self.main_frame)
        self.tempo2_checkbox.setObjectName(_fromUtf8("tempo2_checkbox"))
        self.main_layout.addWidget(self.tempo2_checkbox, 6, 1, 1, 1)
        self.taf_date_label = QtGui.QLabel(self.main_frame)
        self.taf_date_label.setObjectName(_fromUtf8("taf_date_label"))
        self.main_layout.addWidget(self.taf_date_label, 2, 0, 1, 1)
        self.taf_gust_label = QtGui.QLabel(self.main_frame)
        self.taf_gust_label.setObjectName(_fromUtf8("taf_gust_label"))
        self.main_layout.addWidget(self.taf_gust_label, 2, 3, 1, 1)
        self.period_line = QtGui.QLineEdit(self.main_frame)
        self.period_line.setObjectName(_fromUtf8("period_line"))
        self.main_layout.addWidget(self.period_line, 3, 1, 1, 1)
        self.taf_wind_label = QtGui.QLabel(self.main_frame)
        self.taf_wind_label.setObjectName(_fromUtf8("taf_wind_label"))
        self.main_layout.addWidget(self.taf_wind_label, 2, 2, 1, 1)
        self.period_label = QtGui.QLabel(self.main_frame)
        self.period_label.setObjectName(_fromUtf8("period_label"))
        self.main_layout.addWidget(self.period_label, 2, 1, 1, 1)
        self.taf_cb = QtGui.QLineEdit(self.main_frame)
        self.taf_cb.setObjectName(_fromUtf8("taf_cb"))
        self.main_layout.addWidget(self.taf_cb, 3, 10, 1, 1)
        self.taf_cb_label = QtGui.QLabel(self.main_frame)
        self.taf_cb_label.setObjectName(_fromUtf8("taf_cb_label"))
        self.main_layout.addWidget(self.taf_cb_label, 2, 10, 1, 1)
        self.becmg1_checkbox = QtGui.QCheckBox(self.main_frame)
        self.becmg1_checkbox.setObjectName(_fromUtf8("becmg1_checkbox"))
        self.main_layout.addWidget(self.becmg1_checkbox, 5, 0, 1, 1)
        self.type_ft = QtGui.QRadioButton(self.main_frame)
        self.type_ft.setObjectName(_fromUtf8("type_ft"))
        self.main_layout.addWidget(self.type_ft, 0, 1, 1, 1)
        self.becmg3_checkbox = QtGui.QCheckBox(self.main_frame)
        self.becmg3_checkbox.setObjectName(_fromUtf8("becmg3_checkbox"))
        self.main_layout.addWidget(self.becmg3_checkbox, 8, 0, 1, 1)
        self.cls_amd = QtGui.QRadioButton(self.main_frame)
        self.cls_amd.setObjectName(_fromUtf8("cls_amd"))
        self.main_layout.addWidget(self.cls_amd, 0, 7, 1, 1, QtCore.Qt.AlignRight)
        self.taf_cloud3 = QtGui.QLineEdit(self.main_frame)
        self.taf_cloud3.setObjectName(_fromUtf8("taf_cloud3"))
        self.main_layout.addWidget(self.taf_cloud3, 3, 9, 1, 1)
        self.cls_cor = QtGui.QRadioButton(self.main_frame)
        self.cls_cor.setObjectName(_fromUtf8("cls_cor"))
        self.main_layout.addWidget(self.cls_cor, 0, 5, 1, 1, QtCore.Qt.AlignRight)
        self.type_fc = QtGui.QRadioButton(self.main_frame)
        self.type_fc.setObjectName(_fromUtf8("type_fc"))
        self.main_layout.addWidget(self.type_fc, 0, 0, 1, 1)
        self.taf_vis_label = QtGui.QLabel(self.main_frame)
        self.taf_vis_label.setObjectName(_fromUtf8("taf_vis_label"))
        self.main_layout.addWidget(self.taf_vis_label, 2, 4, 1, 1)
        self.taf_date = QtGui.QLineEdit(self.main_frame)
        self.taf_date.setObjectName(_fromUtf8("taf_date"))
        self.main_layout.addWidget(self.taf_date, 3, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.main_layout.addItem(spacerItem, 0, 2, 1, 2)
        self.taf_weather1_label = QtGui.QLabel(self.main_frame)
        self.taf_weather1_label.setObjectName(_fromUtf8("taf_weather1_label"))
        self.main_layout.addWidget(self.taf_weather1_label, 2, 5, 1, 1)
        self.taf_temp_max = QtGui.QLineEdit(self.main_frame)
        self.taf_temp_max.setObjectName(_fromUtf8("taf_temp_max"))
        self.main_layout.addWidget(self.taf_temp_max, 6, 9, 1, 1)
        self.taf_weather2_label = QtGui.QLabel(self.main_frame)
        self.taf_weather2_label.setObjectName(_fromUtf8("taf_weather2_label"))
        self.main_layout.addWidget(self.taf_weather2_label, 2, 6, 1, 1)
        self.taf_wind = QtGui.QLineEdit(self.main_frame)
        self.taf_wind.setObjectName(_fromUtf8("taf_wind"))
        self.main_layout.addWidget(self.taf_wind, 3, 2, 1, 1)
        self.taf_cavok = QtGui.QCheckBox(self.main_frame)
        self.taf_cavok.setObjectName(_fromUtf8("taf_cavok"))
        self.main_layout.addWidget(self.taf_cavok, 4, 4, 1, 1)
        self.taf_temp_max_label = QtGui.QLabel(self.main_frame)
        self.taf_temp_max_label.setObjectName(_fromUtf8("taf_temp_max_label"))
        self.main_layout.addWidget(self.taf_temp_max_label, 5, 9, 1, 1)
        self.taf_cloud1 = QtGui.QLineEdit(self.main_frame)
        self.taf_cloud1.setObjectName(_fromUtf8("taf_cloud1"))
        self.main_layout.addWidget(self.taf_cloud1, 3, 7, 1, 1)
        self.main.addLayout(self.main_layout)
        self.verticalLayout.addWidget(self.main_frame)
        self.becmg1_frame = QtGui.QFrame(TAF)
        self.becmg1_frame.setObjectName(_fromUtf8("becmg1_frame"))
        self.becmg1 = QtGui.QVBoxLayout(self.becmg1_frame)
        self.becmg1.setObjectName(_fromUtf8("becmg1"))
        self.becmg1_layout = QtGui.QGridLayout()
        self.becmg1_layout.setObjectName(_fromUtf8("becmg1_layout"))
        self.becmg1_cb = QtGui.QLineEdit(self.becmg1_frame)
        self.becmg1_cb.setObjectName(_fromUtf8("becmg1_cb"))
        self.becmg1_layout.addWidget(self.becmg1_cb, 3, 13, 1, 1)
        self.becmg1_cloud2_label = QtGui.QLabel(self.becmg1_frame)
        self.becmg1_cloud2_label.setObjectName(_fromUtf8("becmg1_cloud2_label"))
        self.becmg1_layout.addWidget(self.becmg1_cloud2_label, 1, 11, 1, 1)
        self.becmg1_cloud3_label = QtGui.QLabel(self.becmg1_frame)
        self.becmg1_cloud3_label.setObjectName(_fromUtf8("becmg1_cloud3_label"))
        self.becmg1_layout.addWidget(self.becmg1_cloud3_label, 1, 12, 1, 1)
        self.becmg1_wind_label = QtGui.QLabel(self.becmg1_frame)
        self.becmg1_wind_label.setObjectName(_fromUtf8("becmg1_wind_label"))
        self.becmg1_layout.addWidget(self.becmg1_wind_label, 1, 5, 1, 1)
        self.becmg1_period = QtGui.QLineEdit(self.becmg1_frame)
        self.becmg1_period.setObjectName(_fromUtf8("becmg1_period"))
        self.becmg1_layout.addWidget(self.becmg1_period, 3, 4, 1, 1)
        self.becmg1_gust_label = QtGui.QLabel(self.becmg1_frame)
        self.becmg1_gust_label.setObjectName(_fromUtf8("becmg1_gust_label"))
        self.becmg1_layout.addWidget(self.becmg1_gust_label, 1, 6, 1, 1)
        self.becmg1_period_label = QtGui.QLabel(self.becmg1_frame)
        self.becmg1_period_label.setObjectName(_fromUtf8("becmg1_period_label"))
        self.becmg1_layout.addWidget(self.becmg1_period_label, 1, 4, 1, 1)
        self.becmg1_vis_label = QtGui.QLabel(self.becmg1_frame)
        self.becmg1_vis_label.setObjectName(_fromUtf8("becmg1_vis_label"))
        self.becmg1_layout.addWidget(self.becmg1_vis_label, 1, 7, 1, 1)
        self.becmg1_weather2_label = QtGui.QLabel(self.becmg1_frame)
        self.becmg1_weather2_label.setObjectName(_fromUtf8("becmg1_weather2_label"))
        self.becmg1_layout.addWidget(self.becmg1_weather2_label, 1, 9, 1, 1)
        self.becmg1_cloud1 = QtGui.QLineEdit(self.becmg1_frame)
        self.becmg1_cloud1.setObjectName(_fromUtf8("becmg1_cloud1"))
        self.becmg1_layout.addWidget(self.becmg1_cloud1, 3, 10, 1, 1)
        self.becmg1_vis = QtGui.QLineEdit(self.becmg1_frame)
        self.becmg1_vis.setObjectName(_fromUtf8("becmg1_vis"))
        self.becmg1_layout.addWidget(self.becmg1_vis, 3, 7, 1, 1)
        self.becmg1_wind = QtGui.QLineEdit(self.becmg1_frame)
        self.becmg1_wind.setObjectName(_fromUtf8("becmg1_wind"))
        self.becmg1_layout.addWidget(self.becmg1_wind, 3, 5, 1, 1)
        self.becmg1_title = QtGui.QLineEdit(self.becmg1_frame)
        self.becmg1_title.setEnabled(False)
        self.becmg1_title.setObjectName(_fromUtf8("becmg1_title"))
        self.becmg1_layout.addWidget(self.becmg1_title, 3, 3, 1, 1)
        self.becmg1_weather1 = QtGui.QComboBox(self.becmg1_frame)
        self.becmg1_weather1.setObjectName(_fromUtf8("becmg1_weather1"))
        self.becmg1_layout.addWidget(self.becmg1_weather1, 3, 8, 1, 1)
        self.becmg1_line = QtGui.QFrame(self.becmg1_frame)
        self.becmg1_line.setFrameShape(QtGui.QFrame.HLine)
        self.becmg1_line.setFrameShadow(QtGui.QFrame.Sunken)
        self.becmg1_line.setObjectName(_fromUtf8("becmg1_line"))
        self.becmg1_layout.addWidget(self.becmg1_line, 0, 3, 1, 11)
        self.becmg1_weather2 = QtGui.QComboBox(self.becmg1_frame)
        self.becmg1_weather2.setObjectName(_fromUtf8("becmg1_weather2"))
        self.becmg1_layout.addWidget(self.becmg1_weather2, 3, 9, 1, 1)
        self.becmg1_weather1_label = QtGui.QLabel(self.becmg1_frame)
        self.becmg1_weather1_label.setObjectName(_fromUtf8("becmg1_weather1_label"))
        self.becmg1_layout.addWidget(self.becmg1_weather1_label, 1, 8, 1, 1)
        self.becmg1_cb_label = QtGui.QLabel(self.becmg1_frame)
        self.becmg1_cb_label.setObjectName(_fromUtf8("becmg1_cb_label"))
        self.becmg1_layout.addWidget(self.becmg1_cb_label, 1, 13, 1, 1)
        self.becmg1_gust = QtGui.QLineEdit(self.becmg1_frame)
        self.becmg1_gust.setObjectName(_fromUtf8("becmg1_gust"))
        self.becmg1_layout.addWidget(self.becmg1_gust, 3, 6, 1, 1)
        self.becmg1_cloud2 = QtGui.QLineEdit(self.becmg1_frame)
        self.becmg1_cloud2.setObjectName(_fromUtf8("becmg1_cloud2"))
        self.becmg1_layout.addWidget(self.becmg1_cloud2, 3, 11, 1, 1)
        self.becmg1_cloud3 = QtGui.QLineEdit(self.becmg1_frame)
        self.becmg1_cloud3.setObjectName(_fromUtf8("becmg1_cloud3"))
        self.becmg1_layout.addWidget(self.becmg1_cloud3, 3, 12, 1, 1)
        self.becmg1_cloud1_label = QtGui.QLabel(self.becmg1_frame)
        self.becmg1_cloud1_label.setObjectName(_fromUtf8("becmg1_cloud1_label"))
        self.becmg1_layout.addWidget(self.becmg1_cloud1_label, 1, 10, 1, 1)
        self.becmg1_cavok = QtGui.QCheckBox(self.becmg1_frame)
        self.becmg1_cavok.setObjectName(_fromUtf8("becmg1_cavok"))
        self.becmg1_layout.addWidget(self.becmg1_cavok, 4, 7, 1, 1)
        self.becmg1_skc = QtGui.QCheckBox(self.becmg1_frame)
        self.becmg1_skc.setObjectName(_fromUtf8("becmg1_skc"))
        self.becmg1_layout.addWidget(self.becmg1_skc, 4, 10, 1, 1)
        self.becmg1_nsc = QtGui.QCheckBox(self.becmg1_frame)
        self.becmg1_nsc.setObjectName(_fromUtf8("becmg1_nsc"))
        self.becmg1_layout.addWidget(self.becmg1_nsc, 4, 11, 1, 1)
        self.becmg1.addLayout(self.becmg1_layout)
        self.verticalLayout.addWidget(self.becmg1_frame)
        self.becmg2_frame = QtGui.QFrame(TAF)
        self.becmg2_frame.setObjectName(_fromUtf8("becmg2_frame"))
        self.becmg2 = QtGui.QVBoxLayout(self.becmg2_frame)
        self.becmg2.setObjectName(_fromUtf8("becmg2"))
        self.becmg2_layout = QtGui.QGridLayout()
        self.becmg2_layout.setObjectName(_fromUtf8("becmg2_layout"))
        self.becmg2_gust = QtGui.QLineEdit(self.becmg2_frame)
        self.becmg2_gust.setObjectName(_fromUtf8("becmg2_gust"))
        self.becmg2_layout.addWidget(self.becmg2_gust, 3, 6, 1, 1)
        self.becmg2_cb_label = QtGui.QLabel(self.becmg2_frame)
        self.becmg2_cb_label.setObjectName(_fromUtf8("becmg2_cb_label"))
        self.becmg2_layout.addWidget(self.becmg2_cb_label, 1, 13, 1, 1)
        self.becmg2_cloud2 = QtGui.QLineEdit(self.becmg2_frame)
        self.becmg2_cloud2.setObjectName(_fromUtf8("becmg2_cloud2"))
        self.becmg2_layout.addWidget(self.becmg2_cloud2, 3, 11, 1, 1)
        self.becmg2_cloud3 = QtGui.QLineEdit(self.becmg2_frame)
        self.becmg2_cloud3.setObjectName(_fromUtf8("becmg2_cloud3"))
        self.becmg2_layout.addWidget(self.becmg2_cloud3, 3, 12, 1, 1)
        self.becmg2_wind_label = QtGui.QLabel(self.becmg2_frame)
        self.becmg2_wind_label.setObjectName(_fromUtf8("becmg2_wind_label"))
        self.becmg2_layout.addWidget(self.becmg2_wind_label, 1, 5, 1, 1)
        self.becmg2_cloud1_label = QtGui.QLabel(self.becmg2_frame)
        self.becmg2_cloud1_label.setObjectName(_fromUtf8("becmg2_cloud1_label"))
        self.becmg2_layout.addWidget(self.becmg2_cloud1_label, 1, 10, 1, 1)
        self.becmg2_cloud3_label = QtGui.QLabel(self.becmg2_frame)
        self.becmg2_cloud3_label.setObjectName(_fromUtf8("becmg2_cloud3_label"))
        self.becmg2_layout.addWidget(self.becmg2_cloud3_label, 1, 12, 1, 1)
        self.becmg2_cloud2_label = QtGui.QLabel(self.becmg2_frame)
        self.becmg2_cloud2_label.setObjectName(_fromUtf8("becmg2_cloud2_label"))
        self.becmg2_layout.addWidget(self.becmg2_cloud2_label, 1, 11, 1, 1)
        self.becmg2_cb = QtGui.QLineEdit(self.becmg2_frame)
        self.becmg2_cb.setObjectName(_fromUtf8("becmg2_cb"))
        self.becmg2_layout.addWidget(self.becmg2_cb, 3, 13, 1, 1)
        self.becmg2_gust_label = QtGui.QLabel(self.becmg2_frame)
        self.becmg2_gust_label.setObjectName(_fromUtf8("becmg2_gust_label"))
        self.becmg2_layout.addWidget(self.becmg2_gust_label, 1, 6, 1, 1)
        self.becmg2_period_label = QtGui.QLabel(self.becmg2_frame)
        self.becmg2_period_label.setObjectName(_fromUtf8("becmg2_period_label"))
        self.becmg2_layout.addWidget(self.becmg2_period_label, 1, 4, 1, 1)
        self.becmg2_period = QtGui.QLineEdit(self.becmg2_frame)
        self.becmg2_period.setObjectName(_fromUtf8("becmg2_period"))
        self.becmg2_layout.addWidget(self.becmg2_period, 3, 4, 1, 1)
        self.becmg2_vis = QtGui.QLineEdit(self.becmg2_frame)
        self.becmg2_vis.setObjectName(_fromUtf8("becmg2_vis"))
        self.becmg2_layout.addWidget(self.becmg2_vis, 3, 7, 1, 1)
        self.becmg2_wind = QtGui.QLineEdit(self.becmg2_frame)
        self.becmg2_wind.setObjectName(_fromUtf8("becmg2_wind"))
        self.becmg2_layout.addWidget(self.becmg2_wind, 3, 5, 1, 1)
        self.becmg2_cloud1 = QtGui.QLineEdit(self.becmg2_frame)
        self.becmg2_cloud1.setObjectName(_fromUtf8("becmg2_cloud1"))
        self.becmg2_layout.addWidget(self.becmg2_cloud1, 3, 10, 1, 1)
        self.becmg2_vis_label = QtGui.QLabel(self.becmg2_frame)
        self.becmg2_vis_label.setObjectName(_fromUtf8("becmg2_vis_label"))
        self.becmg2_layout.addWidget(self.becmg2_vis_label, 1, 7, 1, 1)
        self.becmg2_weather2_label = QtGui.QLabel(self.becmg2_frame)
        self.becmg2_weather2_label.setObjectName(_fromUtf8("becmg2_weather2_label"))
        self.becmg2_layout.addWidget(self.becmg2_weather2_label, 1, 9, 1, 1)
        self.becmg2_weather1_label = QtGui.QLabel(self.becmg2_frame)
        self.becmg2_weather1_label.setObjectName(_fromUtf8("becmg2_weather1_label"))
        self.becmg2_layout.addWidget(self.becmg2_weather1_label, 1, 8, 1, 1)
        self.becmg2_weather2 = QtGui.QComboBox(self.becmg2_frame)
        self.becmg2_weather2.setObjectName(_fromUtf8("becmg2_weather2"))
        self.becmg2_layout.addWidget(self.becmg2_weather2, 3, 9, 1, 1)
        self.becmg2_line = QtGui.QFrame(self.becmg2_frame)
        self.becmg2_line.setFrameShape(QtGui.QFrame.HLine)
        self.becmg2_line.setFrameShadow(QtGui.QFrame.Sunken)
        self.becmg2_line.setObjectName(_fromUtf8("becmg2_line"))
        self.becmg2_layout.addWidget(self.becmg2_line, 0, 3, 1, 11)
        self.becmg2_title = QtGui.QLineEdit(self.becmg2_frame)
        self.becmg2_title.setEnabled(False)
        self.becmg2_title.setObjectName(_fromUtf8("becmg2_title"))
        self.becmg2_layout.addWidget(self.becmg2_title, 3, 3, 1, 1)
        self.becmg2_weather1 = QtGui.QComboBox(self.becmg2_frame)
        self.becmg2_weather1.setObjectName(_fromUtf8("becmg2_weather1"))
        self.becmg2_layout.addWidget(self.becmg2_weather1, 3, 8, 1, 1)
        self.becmg2_cavok = QtGui.QCheckBox(self.becmg2_frame)
        self.becmg2_cavok.setObjectName(_fromUtf8("becmg2_cavok"))
        self.becmg2_layout.addWidget(self.becmg2_cavok, 4, 7, 1, 1)
        self.becmg2_skc = QtGui.QCheckBox(self.becmg2_frame)
        self.becmg2_skc.setObjectName(_fromUtf8("becmg2_skc"))
        self.becmg2_layout.addWidget(self.becmg2_skc, 4, 10, 1, 1)
        self.becmg2_nsc = QtGui.QCheckBox(self.becmg2_frame)
        self.becmg2_nsc.setObjectName(_fromUtf8("becmg2_nsc"))
        self.becmg2_layout.addWidget(self.becmg2_nsc, 4, 11, 1, 1)
        self.becmg2.addLayout(self.becmg2_layout)
        self.verticalLayout.addWidget(self.becmg2_frame)
        self.becmg3_frame = QtGui.QFrame(TAF)
        self.becmg3_frame.setObjectName(_fromUtf8("becmg3_frame"))
        self.becmg3 = QtGui.QVBoxLayout(self.becmg3_frame)
        self.becmg3.setObjectName(_fromUtf8("becmg3"))
        self.becmg3_layout = QtGui.QGridLayout()
        self.becmg3_layout.setObjectName(_fromUtf8("becmg3_layout"))
        self.becmg3_cb_label = QtGui.QLabel(self.becmg3_frame)
        self.becmg3_cb_label.setObjectName(_fromUtf8("becmg3_cb_label"))
        self.becmg3_layout.addWidget(self.becmg3_cb_label, 1, 13, 1, 1)
        self.becmg3_cloud3 = QtGui.QLineEdit(self.becmg3_frame)
        self.becmg3_cloud3.setObjectName(_fromUtf8("becmg3_cloud3"))
        self.becmg3_layout.addWidget(self.becmg3_cloud3, 3, 12, 1, 1)
        self.becmg3_gust = QtGui.QLineEdit(self.becmg3_frame)
        self.becmg3_gust.setObjectName(_fromUtf8("becmg3_gust"))
        self.becmg3_layout.addWidget(self.becmg3_gust, 3, 6, 1, 1)
        self.becmg3_cloud1_label = QtGui.QLabel(self.becmg3_frame)
        self.becmg3_cloud1_label.setObjectName(_fromUtf8("becmg3_cloud1_label"))
        self.becmg3_layout.addWidget(self.becmg3_cloud1_label, 1, 10, 1, 1)
        self.becmg3_cloud3_label = QtGui.QLabel(self.becmg3_frame)
        self.becmg3_cloud3_label.setObjectName(_fromUtf8("becmg3_cloud3_label"))
        self.becmg3_layout.addWidget(self.becmg3_cloud3_label, 1, 12, 1, 1)
        self.becmg3_cloud2 = QtGui.QLineEdit(self.becmg3_frame)
        self.becmg3_cloud2.setObjectName(_fromUtf8("becmg3_cloud2"))
        self.becmg3_layout.addWidget(self.becmg3_cloud2, 3, 11, 1, 1)
        self.becmg3_wind_label = QtGui.QLabel(self.becmg3_frame)
        self.becmg3_wind_label.setObjectName(_fromUtf8("becmg3_wind_label"))
        self.becmg3_layout.addWidget(self.becmg3_wind_label, 1, 5, 1, 1)
        self.becmg3_cloud2_label = QtGui.QLabel(self.becmg3_frame)
        self.becmg3_cloud2_label.setObjectName(_fromUtf8("becmg3_cloud2_label"))
        self.becmg3_layout.addWidget(self.becmg3_cloud2_label, 1, 11, 1, 1)
        self.becmg3_cb = QtGui.QLineEdit(self.becmg3_frame)
        self.becmg3_cb.setObjectName(_fromUtf8("becmg3_cb"))
        self.becmg3_layout.addWidget(self.becmg3_cb, 3, 13, 1, 1)
        self.becmg3_period = QtGui.QLineEdit(self.becmg3_frame)
        self.becmg3_period.setObjectName(_fromUtf8("becmg3_period"))
        self.becmg3_layout.addWidget(self.becmg3_period, 3, 4, 1, 1)
        self.becmg3_gust_label = QtGui.QLabel(self.becmg3_frame)
        self.becmg3_gust_label.setObjectName(_fromUtf8("becmg3_gust_label"))
        self.becmg3_layout.addWidget(self.becmg3_gust_label, 1, 6, 1, 1)
        self.becmg3_period_label = QtGui.QLabel(self.becmg3_frame)
        self.becmg3_period_label.setObjectName(_fromUtf8("becmg3_period_label"))
        self.becmg3_layout.addWidget(self.becmg3_period_label, 1, 4, 1, 1)
        self.becmg3_vis_label = QtGui.QLabel(self.becmg3_frame)
        self.becmg3_vis_label.setObjectName(_fromUtf8("becmg3_vis_label"))
        self.becmg3_layout.addWidget(self.becmg3_vis_label, 1, 7, 1, 1)
        self.becmg3_weather2_label = QtGui.QLabel(self.becmg3_frame)
        self.becmg3_weather2_label.setObjectName(_fromUtf8("becmg3_weather2_label"))
        self.becmg3_layout.addWidget(self.becmg3_weather2_label, 1, 9, 1, 1)
        self.becmg3_wind = QtGui.QLineEdit(self.becmg3_frame)
        self.becmg3_wind.setObjectName(_fromUtf8("becmg3_wind"))
        self.becmg3_layout.addWidget(self.becmg3_wind, 3, 5, 1, 1)
        self.becmg3_cloud1 = QtGui.QLineEdit(self.becmg3_frame)
        self.becmg3_cloud1.setObjectName(_fromUtf8("becmg3_cloud1"))
        self.becmg3_layout.addWidget(self.becmg3_cloud1, 3, 10, 1, 1)
        self.becmg3_vis = QtGui.QLineEdit(self.becmg3_frame)
        self.becmg3_vis.setObjectName(_fromUtf8("becmg3_vis"))
        self.becmg3_layout.addWidget(self.becmg3_vis, 3, 7, 1, 1)
        self.becmg3_weather1 = QtGui.QComboBox(self.becmg3_frame)
        self.becmg3_weather1.setObjectName(_fromUtf8("becmg3_weather1"))
        self.becmg3_layout.addWidget(self.becmg3_weather1, 3, 8, 1, 1)
        self.becmg3_title = QtGui.QLineEdit(self.becmg3_frame)
        self.becmg3_title.setEnabled(False)
        self.becmg3_title.setObjectName(_fromUtf8("becmg3_title"))
        self.becmg3_layout.addWidget(self.becmg3_title, 3, 3, 1, 1)
        self.becmg3_weather2 = QtGui.QComboBox(self.becmg3_frame)
        self.becmg3_weather2.setObjectName(_fromUtf8("becmg3_weather2"))
        self.becmg3_layout.addWidget(self.becmg3_weather2, 3, 9, 1, 1)
        self.becmg3_line = QtGui.QFrame(self.becmg3_frame)
        self.becmg3_line.setFrameShape(QtGui.QFrame.HLine)
        self.becmg3_line.setFrameShadow(QtGui.QFrame.Sunken)
        self.becmg3_line.setObjectName(_fromUtf8("becmg3_line"))
        self.becmg3_layout.addWidget(self.becmg3_line, 0, 3, 1, 11)
        self.becmg3_weather1_label = QtGui.QLabel(self.becmg3_frame)
        self.becmg3_weather1_label.setObjectName(_fromUtf8("becmg3_weather1_label"))
        self.becmg3_layout.addWidget(self.becmg3_weather1_label, 1, 8, 1, 1)
        self.becmg3_cavok = QtGui.QCheckBox(self.becmg3_frame)
        self.becmg3_cavok.setObjectName(_fromUtf8("becmg3_cavok"))
        self.becmg3_layout.addWidget(self.becmg3_cavok, 4, 7, 1, 1)
        self.becmg3_skc = QtGui.QCheckBox(self.becmg3_frame)
        self.becmg3_skc.setObjectName(_fromUtf8("becmg3_skc"))
        self.becmg3_layout.addWidget(self.becmg3_skc, 4, 10, 1, 1)
        self.becmg3_nsc = QtGui.QCheckBox(self.becmg3_frame)
        self.becmg3_nsc.setObjectName(_fromUtf8("becmg3_nsc"))
        self.becmg3_layout.addWidget(self.becmg3_nsc, 4, 11, 1, 1)
        self.becmg3.addLayout(self.becmg3_layout)
        self.verticalLayout.addWidget(self.becmg3_frame)
        self.tempo1_frame = QtGui.QFrame(TAF)
        self.tempo1_frame.setObjectName(_fromUtf8("tempo1_frame"))
        self.tempo1 = QtGui.QVBoxLayout(self.tempo1_frame)
        self.tempo1.setObjectName(_fromUtf8("tempo1"))
        self.tempo1_layout = QtGui.QGridLayout()
        self.tempo1_layout.setObjectName(_fromUtf8("tempo1_layout"))
        self.tempo1_cloud3_label = QtGui.QLabel(self.tempo1_frame)
        self.tempo1_cloud3_label.setObjectName(_fromUtf8("tempo1_cloud3_label"))
        self.tempo1_layout.addWidget(self.tempo1_cloud3_label, 1, 12, 1, 1)
        self.tempo1_cloud2_label = QtGui.QLabel(self.tempo1_frame)
        self.tempo1_cloud2_label.setObjectName(_fromUtf8("tempo1_cloud2_label"))
        self.tempo1_layout.addWidget(self.tempo1_cloud2_label, 1, 11, 1, 1)
        self.tempo1_wind_label = QtGui.QLabel(self.tempo1_frame)
        self.tempo1_wind_label.setObjectName(_fromUtf8("tempo1_wind_label"))
        self.tempo1_layout.addWidget(self.tempo1_wind_label, 1, 5, 1, 1)
        self.tempo1_cb = QtGui.QLineEdit(self.tempo1_frame)
        self.tempo1_cb.setObjectName(_fromUtf8("tempo1_cb"))
        self.tempo1_layout.addWidget(self.tempo1_cb, 3, 13, 1, 1)
        self.tempo1_period_label = QtGui.QLabel(self.tempo1_frame)
        self.tempo1_period_label.setObjectName(_fromUtf8("tempo1_period_label"))
        self.tempo1_layout.addWidget(self.tempo1_period_label, 1, 4, 1, 1)
        self.tempo1_period = QtGui.QLineEdit(self.tempo1_frame)
        self.tempo1_period.setObjectName(_fromUtf8("tempo1_period"))
        self.tempo1_layout.addWidget(self.tempo1_period, 3, 4, 1, 1)
        self.tempo1_gust_label = QtGui.QLabel(self.tempo1_frame)
        self.tempo1_gust_label.setObjectName(_fromUtf8("tempo1_gust_label"))
        self.tempo1_layout.addWidget(self.tempo1_gust_label, 1, 6, 1, 1)
        self.tempo1_vis_label = QtGui.QLabel(self.tempo1_frame)
        self.tempo1_vis_label.setObjectName(_fromUtf8("tempo1_vis_label"))
        self.tempo1_layout.addWidget(self.tempo1_vis_label, 1, 7, 1, 1)
        self.tempo1_wind = QtGui.QLineEdit(self.tempo1_frame)
        self.tempo1_wind.setObjectName(_fromUtf8("tempo1_wind"))
        self.tempo1_layout.addWidget(self.tempo1_wind, 3, 5, 1, 1)
        self.tempo1_weather2_label = QtGui.QLabel(self.tempo1_frame)
        self.tempo1_weather2_label.setObjectName(_fromUtf8("tempo1_weather2_label"))
        self.tempo1_layout.addWidget(self.tempo1_weather2_label, 1, 9, 1, 1)
        self.tempo1_cloud1 = QtGui.QLineEdit(self.tempo1_frame)
        self.tempo1_cloud1.setObjectName(_fromUtf8("tempo1_cloud1"))
        self.tempo1_layout.addWidget(self.tempo1_cloud1, 3, 10, 1, 1)
        self.tempo1_weather2 = QtGui.QComboBox(self.tempo1_frame)
        self.tempo1_weather2.setObjectName(_fromUtf8("tempo1_weather2"))
        self.tempo1_layout.addWidget(self.tempo1_weather2, 3, 9, 1, 1)
        self.tempo1_vis = QtGui.QLineEdit(self.tempo1_frame)
        self.tempo1_vis.setObjectName(_fromUtf8("tempo1_vis"))
        self.tempo1_layout.addWidget(self.tempo1_vis, 3, 7, 1, 1)
        self.tempo1_weather1 = QtGui.QComboBox(self.tempo1_frame)
        self.tempo1_weather1.setObjectName(_fromUtf8("tempo1_weather1"))
        self.tempo1_layout.addWidget(self.tempo1_weather1, 3, 8, 1, 1)
        self.tempo1_title = QtGui.QLineEdit(self.tempo1_frame)
        self.tempo1_title.setEnabled(False)
        self.tempo1_title.setObjectName(_fromUtf8("tempo1_title"))
        self.tempo1_layout.addWidget(self.tempo1_title, 3, 3, 1, 1)
        self.tempo1_weather1_label = QtGui.QLabel(self.tempo1_frame)
        self.tempo1_weather1_label.setObjectName(_fromUtf8("tempo1_weather1_label"))
        self.tempo1_layout.addWidget(self.tempo1_weather1_label, 1, 8, 1, 1)
        self.tempo1_line = QtGui.QFrame(self.tempo1_frame)
        self.tempo1_line.setFrameShape(QtGui.QFrame.HLine)
        self.tempo1_line.setFrameShadow(QtGui.QFrame.Sunken)
        self.tempo1_line.setObjectName(_fromUtf8("tempo1_line"))
        self.tempo1_layout.addWidget(self.tempo1_line, 0, 3, 1, 11)
        self.tempo1_gust = QtGui.QLineEdit(self.tempo1_frame)
        self.tempo1_gust.setObjectName(_fromUtf8("tempo1_gust"))
        self.tempo1_layout.addWidget(self.tempo1_gust, 3, 6, 1, 1)
        self.tempo1_cloud1_label = QtGui.QLabel(self.tempo1_frame)
        self.tempo1_cloud1_label.setObjectName(_fromUtf8("tempo1_cloud1_label"))
        self.tempo1_layout.addWidget(self.tempo1_cloud1_label, 1, 10, 1, 1)
        self.tempo1_cb_label = QtGui.QLabel(self.tempo1_frame)
        self.tempo1_cb_label.setObjectName(_fromUtf8("tempo1_cb_label"))
        self.tempo1_layout.addWidget(self.tempo1_cb_label, 1, 13, 1, 1)
        self.tempo1_cloud2 = QtGui.QLineEdit(self.tempo1_frame)
        self.tempo1_cloud2.setObjectName(_fromUtf8("tempo1_cloud2"))
        self.tempo1_layout.addWidget(self.tempo1_cloud2, 3, 11, 1, 1)
        self.tempo1_cloud3 = QtGui.QLineEdit(self.tempo1_frame)
        self.tempo1_cloud3.setObjectName(_fromUtf8("tempo1_cloud3"))
        self.tempo1_layout.addWidget(self.tempo1_cloud3, 3, 12, 1, 1)
        self.tempo1_prob30 = QtGui.QCheckBox(self.tempo1_frame)
        self.tempo1_prob30.setObjectName(_fromUtf8("tempo1_prob30"))
        self.tempo1_layout.addWidget(self.tempo1_prob30, 4, 4, 1, 1)
        self.tempo1_prob40 = QtGui.QCheckBox(self.tempo1_frame)
        self.tempo1_prob40.setObjectName(_fromUtf8("tempo1_prob40"))
        self.tempo1_layout.addWidget(self.tempo1_prob40, 4, 5, 1, 1)
        self.tempo1.addLayout(self.tempo1_layout)
        self.verticalLayout.addWidget(self.tempo1_frame)
        self.tempo2_frame = QtGui.QFrame(TAF)
        self.tempo2_frame.setObjectName(_fromUtf8("tempo2_frame"))
        self.tempo2 = QtGui.QVBoxLayout(self.tempo2_frame)
        self.tempo2.setObjectName(_fromUtf8("tempo2"))
        self.tempo2_layout = QtGui.QGridLayout()
        self.tempo2_layout.setObjectName(_fromUtf8("tempo2_layout"))
        self.tempo2_cloud3_label = QtGui.QLabel(self.tempo2_frame)
        self.tempo2_cloud3_label.setObjectName(_fromUtf8("tempo2_cloud3_label"))
        self.tempo2_layout.addWidget(self.tempo2_cloud3_label, 1, 12, 1, 1)
        self.tempo2_cloud2_label = QtGui.QLabel(self.tempo2_frame)
        self.tempo2_cloud2_label.setObjectName(_fromUtf8("tempo2_cloud2_label"))
        self.tempo2_layout.addWidget(self.tempo2_cloud2_label, 1, 11, 1, 1)
        self.tempo2_wind_label = QtGui.QLabel(self.tempo2_frame)
        self.tempo2_wind_label.setObjectName(_fromUtf8("tempo2_wind_label"))
        self.tempo2_layout.addWidget(self.tempo2_wind_label, 1, 5, 1, 1)
        self.tempo2_cb = QtGui.QLineEdit(self.tempo2_frame)
        self.tempo2_cb.setObjectName(_fromUtf8("tempo2_cb"))
        self.tempo2_layout.addWidget(self.tempo2_cb, 3, 13, 1, 1)
        self.tempo2_period_label = QtGui.QLabel(self.tempo2_frame)
        self.tempo2_period_label.setObjectName(_fromUtf8("tempo2_period_label"))
        self.tempo2_layout.addWidget(self.tempo2_period_label, 1, 4, 1, 1)
        self.tempo2_period = QtGui.QLineEdit(self.tempo2_frame)
        self.tempo2_period.setObjectName(_fromUtf8("tempo2_period"))
        self.tempo2_layout.addWidget(self.tempo2_period, 3, 4, 1, 1)
        self.tempo2_gust_label = QtGui.QLabel(self.tempo2_frame)
        self.tempo2_gust_label.setObjectName(_fromUtf8("tempo2_gust_label"))
        self.tempo2_layout.addWidget(self.tempo2_gust_label, 1, 6, 1, 1)
        self.tempo2_vis_label = QtGui.QLabel(self.tempo2_frame)
        self.tempo2_vis_label.setObjectName(_fromUtf8("tempo2_vis_label"))
        self.tempo2_layout.addWidget(self.tempo2_vis_label, 1, 7, 1, 1)
        self.tempo2_wind = QtGui.QLineEdit(self.tempo2_frame)
        self.tempo2_wind.setObjectName(_fromUtf8("tempo2_wind"))
        self.tempo2_layout.addWidget(self.tempo2_wind, 3, 5, 1, 1)
        self.tempo2_weather2_label = QtGui.QLabel(self.tempo2_frame)
        self.tempo2_weather2_label.setObjectName(_fromUtf8("tempo2_weather2_label"))
        self.tempo2_layout.addWidget(self.tempo2_weather2_label, 1, 9, 1, 1)
        self.tempo2_cloud1 = QtGui.QLineEdit(self.tempo2_frame)
        self.tempo2_cloud1.setObjectName(_fromUtf8("tempo2_cloud1"))
        self.tempo2_layout.addWidget(self.tempo2_cloud1, 3, 10, 1, 1)
        self.tempo2_weather2 = QtGui.QComboBox(self.tempo2_frame)
        self.tempo2_weather2.setObjectName(_fromUtf8("tempo2_weather2"))
        self.tempo2_layout.addWidget(self.tempo2_weather2, 3, 9, 1, 1)
        self.tempo2_vis = QtGui.QLineEdit(self.tempo2_frame)
        self.tempo2_vis.setObjectName(_fromUtf8("tempo2_vis"))
        self.tempo2_layout.addWidget(self.tempo2_vis, 3, 7, 1, 1)
        self.tempo2_weather1 = QtGui.QComboBox(self.tempo2_frame)
        self.tempo2_weather1.setObjectName(_fromUtf8("tempo2_weather1"))
        self.tempo2_layout.addWidget(self.tempo2_weather1, 3, 8, 1, 1)
        self.tempo2_title = QtGui.QLineEdit(self.tempo2_frame)
        self.tempo2_title.setEnabled(False)
        self.tempo2_title.setObjectName(_fromUtf8("tempo2_title"))
        self.tempo2_layout.addWidget(self.tempo2_title, 3, 3, 1, 1)
        self.tempo2_weather1_label = QtGui.QLabel(self.tempo2_frame)
        self.tempo2_weather1_label.setObjectName(_fromUtf8("tempo2_weather1_label"))
        self.tempo2_layout.addWidget(self.tempo2_weather1_label, 1, 8, 1, 1)
        self.tempo2_line = QtGui.QFrame(self.tempo2_frame)
        self.tempo2_line.setFrameShape(QtGui.QFrame.HLine)
        self.tempo2_line.setFrameShadow(QtGui.QFrame.Sunken)
        self.tempo2_line.setObjectName(_fromUtf8("tempo2_line"))
        self.tempo2_layout.addWidget(self.tempo2_line, 0, 3, 1, 11)
        self.tempo2_gust = QtGui.QLineEdit(self.tempo2_frame)
        self.tempo2_gust.setObjectName(_fromUtf8("tempo2_gust"))
        self.tempo2_layout.addWidget(self.tempo2_gust, 3, 6, 1, 1)
        self.tempo2_cloud1_label = QtGui.QLabel(self.tempo2_frame)
        self.tempo2_cloud1_label.setObjectName(_fromUtf8("tempo2_cloud1_label"))
        self.tempo2_layout.addWidget(self.tempo2_cloud1_label, 1, 10, 1, 1)
        self.tempo2_cb_label = QtGui.QLabel(self.tempo2_frame)
        self.tempo2_cb_label.setObjectName(_fromUtf8("tempo2_cb_label"))
        self.tempo2_layout.addWidget(self.tempo2_cb_label, 1, 13, 1, 1)
        self.tempo2_cloud2 = QtGui.QLineEdit(self.tempo2_frame)
        self.tempo2_cloud2.setObjectName(_fromUtf8("tempo2_cloud2"))
        self.tempo2_layout.addWidget(self.tempo2_cloud2, 3, 11, 1, 1)
        self.tempo2_cloud3 = QtGui.QLineEdit(self.tempo2_frame)
        self.tempo2_cloud3.setObjectName(_fromUtf8("tempo2_cloud3"))
        self.tempo2_layout.addWidget(self.tempo2_cloud3, 3, 12, 1, 1)
        self.tempo2_prob30 = QtGui.QCheckBox(self.tempo2_frame)
        self.tempo2_prob30.setObjectName(_fromUtf8("tempo2_prob30"))
        self.tempo2_layout.addWidget(self.tempo2_prob30, 4, 4, 1, 1)
        self.tempo2_prob40 = QtGui.QCheckBox(self.tempo2_frame)
        self.tempo2_prob40.setObjectName(_fromUtf8("tempo2_prob40"))
        self.tempo2_layout.addWidget(self.tempo2_prob40, 4, 5, 1, 1)
        self.tempo2.addLayout(self.tempo2_layout)
        self.verticalLayout.addWidget(self.tempo2_frame)
        self.taf_next = QtGui.QPushButton(TAF)
        self.taf_next.setMaximumSize(QtCore.QSize(70, 23))
        self.taf_next.setObjectName(_fromUtf8("taf_next"))
        self.verticalLayout.addWidget(self.taf_next, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)

        self.retranslateUi(TAF)
        QtCore.QMetaObject.connectSlotsByName(TAF)

    def retranslateUi(self, TAF):
        TAF.setWindowTitle(_translate("TAF", "Dialog", None))
        self.tempo1_checkbox.setText(_translate("TAF", "TEMPO1", None))
        self.becmg2_checkbox.setText(_translate("TAF", "BECMG2", None))
        self.taf_cloud1_label.setText(_translate("TAF", "云组1", None))
        self.taf_cloud2_label.setText(_translate("TAF", "云组2", None))
        self.taf_skc.setText(_translate("TAF", "SKC", None))
        self.taf_nsc.setText(_translate("TAF", "NSC", None))
        self.taf_cloud3_label.setText(_translate("TAF", "云组3", None))
        self.cls_cnl.setText(_translate("TAF", "取消报", None))
        self.cls_normal.setText(_translate("TAF", "正常报", None))
        self.taf_temp_min_label.setText(_translate("TAF", "最低温", None))
        self.tempo2_checkbox.setText(_translate("TAF", "TEMPO2", None))
        self.taf_date_label.setText(_translate("TAF", "日期", None))
        self.taf_gust_label.setText(_translate("TAF", "阵风", None))
        self.taf_wind_label.setText(_translate("TAF", "风向风速", None))
        self.period_label.setText(_translate("TAF", "时段", None))
        self.taf_cb_label.setText(_translate("TAF", "积雨云", None))
        self.becmg1_checkbox.setText(_translate("TAF", "BECMG1", None))
        self.type_ft.setText(_translate("TAF", "FT", None))
        self.becmg3_checkbox.setText(_translate("TAF", "BECMG3", None))
        self.cls_amd.setText(_translate("TAF", "修订报", None))
        self.cls_cor.setText(_translate("TAF", "更正报", None))
        self.type_fc.setText(_translate("TAF", "FC", None))
        self.taf_vis_label.setText(_translate("TAF", "能见度", None))
        self.taf_weather1_label.setText(_translate("TAF", "天气现象1", None))
        self.taf_weather2_label.setText(_translate("TAF", "天气现象2", None))
        self.taf_cavok.setText(_translate("TAF", "CAVOK", None))
        self.taf_temp_max_label.setText(_translate("TAF", "最高温", None))
        self.becmg1_cloud2_label.setText(_translate("TAF", "云组2", None))
        self.becmg1_cloud3_label.setText(_translate("TAF", "云组3", None))
        self.becmg1_wind_label.setText(_translate("TAF", "风向风速", None))
        self.becmg1_gust_label.setText(_translate("TAF", "阵风", None))
        self.becmg1_period_label.setText(_translate("TAF", "时段", None))
        self.becmg1_vis_label.setText(_translate("TAF", "能见度", None))
        self.becmg1_weather2_label.setText(_translate("TAF", "天气现象2", None))
        self.becmg1_title.setText(_translate("TAF", "BECMG1", None))
        self.becmg1_weather1_label.setText(_translate("TAF", "天气现象1", None))
        self.becmg1_cb_label.setText(_translate("TAF", "积雨云", None))
        self.becmg1_cloud1_label.setText(_translate("TAF", "云组1", None))
        self.becmg1_cavok.setText(_translate("TAF", "CAVOK", None))
        self.becmg1_skc.setText(_translate("TAF", "SKC", None))
        self.becmg1_nsc.setText(_translate("TAF", "NSC", None))
        self.becmg2_cb_label.setText(_translate("TAF", "积雨云", None))
        self.becmg2_wind_label.setText(_translate("TAF", "风向风速", None))
        self.becmg2_cloud1_label.setText(_translate("TAF", "云组1", None))
        self.becmg2_cloud3_label.setText(_translate("TAF", "云组3", None))
        self.becmg2_cloud2_label.setText(_translate("TAF", "云组2", None))
        self.becmg2_gust_label.setText(_translate("TAF", "阵风", None))
        self.becmg2_period_label.setText(_translate("TAF", "时段", None))
        self.becmg2_vis_label.setText(_translate("TAF", "能见度", None))
        self.becmg2_weather2_label.setText(_translate("TAF", "天气现象2", None))
        self.becmg2_weather1_label.setText(_translate("TAF", "天气现象1", None))
        self.becmg2_title.setText(_translate("TAF", "BECMG2", None))
        self.becmg2_cavok.setText(_translate("TAF", "CAVOK", None))
        self.becmg2_skc.setText(_translate("TAF", "SKC", None))
        self.becmg2_nsc.setText(_translate("TAF", "NSC", None))
        self.becmg3_cb_label.setText(_translate("TAF", "积雨云", None))
        self.becmg3_cloud1_label.setText(_translate("TAF", "云组1", None))
        self.becmg3_cloud3_label.setText(_translate("TAF", "云组3", None))
        self.becmg3_wind_label.setText(_translate("TAF", "风向风速", None))
        self.becmg3_cloud2_label.setText(_translate("TAF", "云组2", None))
        self.becmg3_gust_label.setText(_translate("TAF", "阵风", None))
        self.becmg3_period_label.setText(_translate("TAF", "时段", None))
        self.becmg3_vis_label.setText(_translate("TAF", "能见度", None))
        self.becmg3_weather2_label.setText(_translate("TAF", "天气现象2", None))
        self.becmg3_title.setText(_translate("TAF", "BECMG3", None))
        self.becmg3_weather1_label.setText(_translate("TAF", "天气现象1", None))
        self.becmg3_cavok.setText(_translate("TAF", "CAVOK", None))
        self.becmg3_skc.setText(_translate("TAF", "SKC", None))
        self.becmg3_nsc.setText(_translate("TAF", "NSC", None))
        self.tempo1_cloud3_label.setText(_translate("TAF", "云组3", None))
        self.tempo1_cloud2_label.setText(_translate("TAF", "云组2", None))
        self.tempo1_wind_label.setText(_translate("TAF", "风向风速", None))
        self.tempo1_period_label.setText(_translate("TAF", "时段", None))
        self.tempo1_gust_label.setText(_translate("TAF", "阵风", None))
        self.tempo1_vis_label.setText(_translate("TAF", "能见度", None))
        self.tempo1_weather2_label.setText(_translate("TAF", "天气现象2", None))
        self.tempo1_title.setText(_translate("TAF", "TEMPO1", None))
        self.tempo1_weather1_label.setText(_translate("TAF", "天气现象1", None))
        self.tempo1_cloud1_label.setText(_translate("TAF", "云组1", None))
        self.tempo1_cb_label.setText(_translate("TAF", "积雨云", None))
        self.tempo1_prob30.setText(_translate("TAF", "PROB30", None))
        self.tempo1_prob40.setText(_translate("TAF", "PROB40", None))
        self.tempo2_cloud3_label.setText(_translate("TAF", "云组3", None))
        self.tempo2_cloud2_label.setText(_translate("TAF", "云组2", None))
        self.tempo2_wind_label.setText(_translate("TAF", "风向风速", None))
        self.tempo2_period_label.setText(_translate("TAF", "时段", None))
        self.tempo2_gust_label.setText(_translate("TAF", "阵风", None))
        self.tempo2_vis_label.setText(_translate("TAF", "能见度", None))
        self.tempo2_weather2_label.setText(_translate("TAF", "天气现象2", None))
        self.tempo2_title.setText(_translate("TAF", "TEMPO2", None))
        self.tempo2_weather1_label.setText(_translate("TAF", "天气现象1", None))
        self.tempo2_cloud1_label.setText(_translate("TAF", "云组1", None))
        self.tempo2_cb_label.setText(_translate("TAF", "积雨云", None))
        self.tempo2_prob30.setText(_translate("TAF", "PROB30", None))
        self.tempo2_prob40.setText(_translate("TAF", "PROB40", None))
        self.taf_next.setText(_translate("TAF", "下一步", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    TAF = QtGui.QDialog()
    ui = Ui_TAF()
    ui.setupUi(TAF)
    TAF.show()
    sys.exit(app.exec_())

