# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Work\tafor\tafor\ui\taf_edit.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TAFEdit(object):
    def setupUi(self, TAFEdit):
        TAFEdit.setObjectName("TAFEdit")
        TAFEdit.resize(1024, 720)
        TAFEdit.setMaximumSize(QtCore.QSize(1024, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(TAFEdit)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_frame = QtWidgets.QFrame(TAFEdit)
        self.main_frame.setObjectName("main_frame")
        self.main = QtWidgets.QVBoxLayout(self.main_frame)
        self.main.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.main.setObjectName("main")
        self.main_layout = QtWidgets.QGridLayout()
        self.main_layout.setObjectName("main_layout")
        self.taf_weather1_combobox = QtWidgets.QComboBox(self.main_frame)
        self.taf_weather1_combobox.setObjectName("taf_weather1_combobox")
        self.main_layout.addWidget(self.taf_weather1_combobox, 3, 5, 1, 1)
        self.taf_weather2_combobox = QtWidgets.QComboBox(self.main_frame)
        self.taf_weather2_combobox.setObjectName("taf_weather2_combobox")
        self.main_layout.addWidget(self.taf_weather2_combobox, 3, 6, 1, 1)
        self.taf_temp_min = QtWidgets.QLineEdit(self.main_frame)
        self.taf_temp_min.setObjectName("taf_temp_min")
        self.main_layout.addWidget(self.taf_temp_min, 6, 10, 1, 1)
        self.taf_skc = QtWidgets.QCheckBox(self.main_frame)
        self.taf_skc.setObjectName("taf_skc")
        self.main_layout.addWidget(self.taf_skc, 4, 7, 1, 1)
        self.tempo1_checkbox = QtWidgets.QCheckBox(self.main_frame)
        self.tempo1_checkbox.setObjectName("tempo1_checkbox")
        self.main_layout.addWidget(self.tempo1_checkbox, 5, 1, 1, 1)
        self.taf_cloud3_label = QtWidgets.QLabel(self.main_frame)
        self.taf_cloud3_label.setObjectName("taf_cloud3_label")
        self.main_layout.addWidget(self.taf_cloud3_label, 2, 9, 1, 1)
        self.taf_vis = QtWidgets.QLineEdit(self.main_frame)
        self.taf_vis.setObjectName("taf_vis")
        self.main_layout.addWidget(self.taf_vis, 3, 4, 1, 1)
        self.becmg2_checkbox = QtWidgets.QCheckBox(self.main_frame)
        self.becmg2_checkbox.setObjectName("becmg2_checkbox")
        self.main_layout.addWidget(self.becmg2_checkbox, 6, 0, 1, 1)
        self.taf_cloud1_label = QtWidgets.QLabel(self.main_frame)
        self.taf_cloud1_label.setObjectName("taf_cloud1_label")
        self.main_layout.addWidget(self.taf_cloud1_label, 2, 7, 1, 1)
        self.taf_cloud2 = QtWidgets.QLineEdit(self.main_frame)
        self.taf_cloud2.setObjectName("taf_cloud2")
        self.main_layout.addWidget(self.taf_cloud2, 3, 8, 1, 1)
        self.taf_cloud2_label = QtWidgets.QLabel(self.main_frame)
        self.taf_cloud2_label.setObjectName("taf_cloud2_label")
        self.main_layout.addWidget(self.taf_cloud2_label, 2, 8, 1, 1)
        self.taf_nsc = QtWidgets.QCheckBox(self.main_frame)
        self.taf_nsc.setObjectName("taf_nsc")
        self.main_layout.addWidget(self.taf_nsc, 4, 8, 1, 1)
        self.taf_gust = QtWidgets.QLineEdit(self.main_frame)
        self.taf_gust.setObjectName("taf_gust")
        self.main_layout.addWidget(self.taf_gust, 3, 3, 1, 1)
        self.taf_temp_min_label = QtWidgets.QLabel(self.main_frame)
        self.taf_temp_min_label.setObjectName("taf_temp_min_label")
        self.main_layout.addWidget(self.taf_temp_min_label, 5, 10, 1, 1)
        self.becmg3_checkbox = QtWidgets.QCheckBox(self.main_frame)
        self.becmg3_checkbox.setObjectName("becmg3_checkbox")
        self.main_layout.addWidget(self.becmg3_checkbox, 8, 0, 1, 1)
        self.taf_vis_label = QtWidgets.QLabel(self.main_frame)
        self.taf_vis_label.setObjectName("taf_vis_label")
        self.main_layout.addWidget(self.taf_vis_label, 2, 4, 1, 1)
        self.taf_weather1_label = QtWidgets.QLabel(self.main_frame)
        self.taf_weather1_label.setObjectName("taf_weather1_label")
        self.main_layout.addWidget(self.taf_weather1_label, 2, 5, 1, 1)
        self.taf_gust_label = QtWidgets.QLabel(self.main_frame)
        self.taf_gust_label.setObjectName("taf_gust_label")
        self.main_layout.addWidget(self.taf_gust_label, 2, 3, 1, 1)
        self.taf_date = QtWidgets.QLineEdit(self.main_frame)
        self.taf_date.setObjectName("taf_date")
        self.main_layout.addWidget(self.taf_date, 3, 0, 1, 1)
        self.taf_cavok = QtWidgets.QCheckBox(self.main_frame)
        self.taf_cavok.setObjectName("taf_cavok")
        self.main_layout.addWidget(self.taf_cavok, 4, 4, 1, 1)
        self.taf_cloud1 = QtWidgets.QLineEdit(self.main_frame)
        self.taf_cloud1.setObjectName("taf_cloud1")
        self.main_layout.addWidget(self.taf_cloud1, 3, 7, 1, 1)
        self.becmg1_checkbox = QtWidgets.QCheckBox(self.main_frame)
        self.becmg1_checkbox.setObjectName("becmg1_checkbox")
        self.main_layout.addWidget(self.becmg1_checkbox, 5, 0, 1, 1)
        self.taf_date_label = QtWidgets.QLabel(self.main_frame)
        self.taf_date_label.setObjectName("taf_date_label")
        self.main_layout.addWidget(self.taf_date_label, 2, 0, 1, 1)
        self.taf_period_label = QtWidgets.QLabel(self.main_frame)
        self.taf_period_label.setObjectName("taf_period_label")
        self.main_layout.addWidget(self.taf_period_label, 2, 1, 1, 1)
        self.taf_cb_label = QtWidgets.QLabel(self.main_frame)
        self.taf_cb_label.setObjectName("taf_cb_label")
        self.main_layout.addWidget(self.taf_cb_label, 2, 10, 1, 1)
        self.taf_wind_label = QtWidgets.QLabel(self.main_frame)
        self.taf_wind_label.setObjectName("taf_wind_label")
        self.main_layout.addWidget(self.taf_wind_label, 2, 2, 1, 1)
        self.taf_wind = QtWidgets.QLineEdit(self.main_frame)
        self.taf_wind.setObjectName("taf_wind")
        self.main_layout.addWidget(self.taf_wind, 3, 2, 1, 1)
        self.taf_temp_max_label = QtWidgets.QLabel(self.main_frame)
        self.taf_temp_max_label.setObjectName("taf_temp_max_label")
        self.main_layout.addWidget(self.taf_temp_max_label, 5, 9, 1, 1)
        self.taf_cloud3 = QtWidgets.QLineEdit(self.main_frame)
        self.taf_cloud3.setObjectName("taf_cloud3")
        self.main_layout.addWidget(self.taf_cloud3, 3, 9, 1, 1)
        self.taf_temp_max = QtWidgets.QLineEdit(self.main_frame)
        self.taf_temp_max.setObjectName("taf_temp_max")
        self.main_layout.addWidget(self.taf_temp_max, 6, 9, 1, 1)
        self.taf_weather2_label = QtWidgets.QLabel(self.main_frame)
        self.taf_weather2_label.setObjectName("taf_weather2_label")
        self.main_layout.addWidget(self.taf_weather2_label, 2, 6, 1, 1)
        self.tempo2_checkbox = QtWidgets.QCheckBox(self.main_frame)
        self.tempo2_checkbox.setObjectName("tempo2_checkbox")
        self.main_layout.addWidget(self.tempo2_checkbox, 6, 1, 1, 1)
        self.taf_period = QtWidgets.QLineEdit(self.main_frame)
        self.taf_period.setObjectName("taf_period")
        self.main_layout.addWidget(self.taf_period, 3, 1, 1, 1)
        self.taf_cb = QtWidgets.QLineEdit(self.main_frame)
        self.taf_cb.setObjectName("taf_cb")
        self.main_layout.addWidget(self.taf_cb, 3, 10, 1, 1)
        self.group_type = QtWidgets.QGroupBox(self.main_frame)
        self.group_type.setTitle("")
        self.group_type.setObjectName("group_type")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.group_type)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.type_fc = QtWidgets.QRadioButton(self.group_type)
        self.type_fc.setObjectName("type_fc")
        self.gridLayout_6.addWidget(self.type_fc, 0, 0, 1, 1)
        self.type_ft = QtWidgets.QRadioButton(self.group_type)
        self.type_ft.setObjectName("type_ft")
        self.gridLayout_6.addWidget(self.type_ft, 0, 1, 1, 1)
        self.main_layout.addWidget(self.group_type, 0, 0, 1, 2)
        self.group_cls = QtWidgets.QGroupBox(self.main_frame)
        self.group_cls.setTitle("")
        self.group_cls.setObjectName("group_cls")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.group_cls)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.cls_normal = QtWidgets.QRadioButton(self.group_cls)
        self.cls_normal.setChecked(True)
        self.cls_normal.setObjectName("cls_normal")
        self.gridLayout_5.addWidget(self.cls_normal, 0, 0, 1, 1)
        self.cls_cor = QtWidgets.QRadioButton(self.group_cls)
        self.cls_cor.setObjectName("cls_cor")
        self.gridLayout_5.addWidget(self.cls_cor, 0, 1, 1, 1)
        self.cls_cor_combobox = QtWidgets.QComboBox(self.group_cls)
        self.cls_cor_combobox.setObjectName("cls_cor_combobox")
        self.gridLayout_5.addWidget(self.cls_cor_combobox, 0, 2, 1, 1)
        self.cls_amd = QtWidgets.QRadioButton(self.group_cls)
        self.cls_amd.setObjectName("cls_amd")
        self.gridLayout_5.addWidget(self.cls_amd, 0, 3, 1, 1)
        self.cls_amd_combobox = QtWidgets.QComboBox(self.group_cls)
        self.cls_amd_combobox.setObjectName("cls_amd_combobox")
        self.gridLayout_5.addWidget(self.cls_amd_combobox, 0, 4, 1, 1)
        self.cls_cnl = QtWidgets.QRadioButton(self.group_cls)
        self.cls_cnl.setObjectName("cls_cnl")
        self.gridLayout_5.addWidget(self.cls_cnl, 0, 5, 1, 1)
        self.cls_cnl_combobox = QtWidgets.QComboBox(self.group_cls)
        self.cls_cnl_combobox.setObjectName("cls_cnl_combobox")
        self.gridLayout_5.addWidget(self.cls_cnl_combobox, 0, 6, 1, 1)
        self.main_layout.addWidget(self.group_cls, 0, 4, 1, 7)
        self.main.addLayout(self.main_layout)
        self.verticalLayout.addWidget(self.main_frame)
        self.becmg1_frame = QtWidgets.QFrame(TAFEdit)
        self.becmg1_frame.setObjectName("becmg1_frame")
        self.becmg1 = QtWidgets.QVBoxLayout(self.becmg1_frame)
        self.becmg1.setObjectName("becmg1")
        self.becmg1_layout = QtWidgets.QGridLayout()
        self.becmg1_layout.setObjectName("becmg1_layout")
        self.becmg1_cb = QtWidgets.QLineEdit(self.becmg1_frame)
        self.becmg1_cb.setObjectName("becmg1_cb")
        self.becmg1_layout.addWidget(self.becmg1_cb, 3, 13, 1, 1)
        self.becmg1_cloud2_label = QtWidgets.QLabel(self.becmg1_frame)
        self.becmg1_cloud2_label.setObjectName("becmg1_cloud2_label")
        self.becmg1_layout.addWidget(self.becmg1_cloud2_label, 1, 11, 1, 1)
        self.becmg1_cloud3_label = QtWidgets.QLabel(self.becmg1_frame)
        self.becmg1_cloud3_label.setObjectName("becmg1_cloud3_label")
        self.becmg1_layout.addWidget(self.becmg1_cloud3_label, 1, 12, 1, 1)
        self.becmg1_wind_label = QtWidgets.QLabel(self.becmg1_frame)
        self.becmg1_wind_label.setObjectName("becmg1_wind_label")
        self.becmg1_layout.addWidget(self.becmg1_wind_label, 1, 5, 1, 1)
        self.becmg1_period = QtWidgets.QLineEdit(self.becmg1_frame)
        self.becmg1_period.setObjectName("becmg1_period")
        self.becmg1_layout.addWidget(self.becmg1_period, 3, 4, 1, 1)
        self.becmg1_gust_label = QtWidgets.QLabel(self.becmg1_frame)
        self.becmg1_gust_label.setObjectName("becmg1_gust_label")
        self.becmg1_layout.addWidget(self.becmg1_gust_label, 1, 6, 1, 1)
        self.becmg1_period_label = QtWidgets.QLabel(self.becmg1_frame)
        self.becmg1_period_label.setObjectName("becmg1_period_label")
        self.becmg1_layout.addWidget(self.becmg1_period_label, 1, 4, 1, 1)
        self.becmg1_vis_label = QtWidgets.QLabel(self.becmg1_frame)
        self.becmg1_vis_label.setObjectName("becmg1_vis_label")
        self.becmg1_layout.addWidget(self.becmg1_vis_label, 1, 7, 1, 1)
        self.becmg1_weather2_label = QtWidgets.QLabel(self.becmg1_frame)
        self.becmg1_weather2_label.setObjectName("becmg1_weather2_label")
        self.becmg1_layout.addWidget(self.becmg1_weather2_label, 1, 9, 1, 1)
        self.becmg1_cloud1 = QtWidgets.QLineEdit(self.becmg1_frame)
        self.becmg1_cloud1.setObjectName("becmg1_cloud1")
        self.becmg1_layout.addWidget(self.becmg1_cloud1, 3, 10, 1, 1)
        self.becmg1_vis = QtWidgets.QLineEdit(self.becmg1_frame)
        self.becmg1_vis.setObjectName("becmg1_vis")
        self.becmg1_layout.addWidget(self.becmg1_vis, 3, 7, 1, 1)
        self.becmg1_wind = QtWidgets.QLineEdit(self.becmg1_frame)
        self.becmg1_wind.setObjectName("becmg1_wind")
        self.becmg1_layout.addWidget(self.becmg1_wind, 3, 5, 1, 1)
        self.becmg1_title = QtWidgets.QLineEdit(self.becmg1_frame)
        self.becmg1_title.setEnabled(False)
        self.becmg1_title.setObjectName("becmg1_title")
        self.becmg1_layout.addWidget(self.becmg1_title, 3, 3, 1, 1)
        self.becmg1_weather1 = QtWidgets.QComboBox(self.becmg1_frame)
        self.becmg1_weather1.setObjectName("becmg1_weather1")
        self.becmg1_layout.addWidget(self.becmg1_weather1, 3, 8, 1, 1)
        self.becmg1_line = QtWidgets.QFrame(self.becmg1_frame)
        self.becmg1_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.becmg1_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.becmg1_line.setObjectName("becmg1_line")
        self.becmg1_layout.addWidget(self.becmg1_line, 0, 3, 1, 11)
        self.becmg1_weather2 = QtWidgets.QComboBox(self.becmg1_frame)
        self.becmg1_weather2.setObjectName("becmg1_weather2")
        self.becmg1_layout.addWidget(self.becmg1_weather2, 3, 9, 1, 1)
        self.becmg1_weather1_label = QtWidgets.QLabel(self.becmg1_frame)
        self.becmg1_weather1_label.setObjectName("becmg1_weather1_label")
        self.becmg1_layout.addWidget(self.becmg1_weather1_label, 1, 8, 1, 1)
        self.becmg1_cb_label = QtWidgets.QLabel(self.becmg1_frame)
        self.becmg1_cb_label.setObjectName("becmg1_cb_label")
        self.becmg1_layout.addWidget(self.becmg1_cb_label, 1, 13, 1, 1)
        self.becmg1_gust = QtWidgets.QLineEdit(self.becmg1_frame)
        self.becmg1_gust.setObjectName("becmg1_gust")
        self.becmg1_layout.addWidget(self.becmg1_gust, 3, 6, 1, 1)
        self.becmg1_cloud2 = QtWidgets.QLineEdit(self.becmg1_frame)
        self.becmg1_cloud2.setObjectName("becmg1_cloud2")
        self.becmg1_layout.addWidget(self.becmg1_cloud2, 3, 11, 1, 1)
        self.becmg1_cloud3 = QtWidgets.QLineEdit(self.becmg1_frame)
        self.becmg1_cloud3.setObjectName("becmg1_cloud3")
        self.becmg1_layout.addWidget(self.becmg1_cloud3, 3, 12, 1, 1)
        self.becmg1_cloud1_label = QtWidgets.QLabel(self.becmg1_frame)
        self.becmg1_cloud1_label.setObjectName("becmg1_cloud1_label")
        self.becmg1_layout.addWidget(self.becmg1_cloud1_label, 1, 10, 1, 1)
        self.becmg1_cavok = QtWidgets.QCheckBox(self.becmg1_frame)
        self.becmg1_cavok.setObjectName("becmg1_cavok")
        self.becmg1_layout.addWidget(self.becmg1_cavok, 4, 7, 1, 1)
        self.becmg1_skc = QtWidgets.QCheckBox(self.becmg1_frame)
        self.becmg1_skc.setObjectName("becmg1_skc")
        self.becmg1_layout.addWidget(self.becmg1_skc, 4, 10, 1, 1)
        self.becmg1_nsc = QtWidgets.QCheckBox(self.becmg1_frame)
        self.becmg1_nsc.setObjectName("becmg1_nsc")
        self.becmg1_layout.addWidget(self.becmg1_nsc, 4, 11, 1, 1)
        self.becmg1.addLayout(self.becmg1_layout)
        self.verticalLayout.addWidget(self.becmg1_frame)
        self.becmg2_frame = QtWidgets.QFrame(TAFEdit)
        self.becmg2_frame.setObjectName("becmg2_frame")
        self.becmg2 = QtWidgets.QVBoxLayout(self.becmg2_frame)
        self.becmg2.setObjectName("becmg2")
        self.becmg2_layout = QtWidgets.QGridLayout()
        self.becmg2_layout.setObjectName("becmg2_layout")
        self.becmg2_gust = QtWidgets.QLineEdit(self.becmg2_frame)
        self.becmg2_gust.setObjectName("becmg2_gust")
        self.becmg2_layout.addWidget(self.becmg2_gust, 3, 6, 1, 1)
        self.becmg2_cb_label = QtWidgets.QLabel(self.becmg2_frame)
        self.becmg2_cb_label.setObjectName("becmg2_cb_label")
        self.becmg2_layout.addWidget(self.becmg2_cb_label, 1, 13, 1, 1)
        self.becmg2_cloud2 = QtWidgets.QLineEdit(self.becmg2_frame)
        self.becmg2_cloud2.setObjectName("becmg2_cloud2")
        self.becmg2_layout.addWidget(self.becmg2_cloud2, 3, 11, 1, 1)
        self.becmg2_cloud3 = QtWidgets.QLineEdit(self.becmg2_frame)
        self.becmg2_cloud3.setObjectName("becmg2_cloud3")
        self.becmg2_layout.addWidget(self.becmg2_cloud3, 3, 12, 1, 1)
        self.becmg2_wind_label = QtWidgets.QLabel(self.becmg2_frame)
        self.becmg2_wind_label.setObjectName("becmg2_wind_label")
        self.becmg2_layout.addWidget(self.becmg2_wind_label, 1, 5, 1, 1)
        self.becmg2_cloud1_label = QtWidgets.QLabel(self.becmg2_frame)
        self.becmg2_cloud1_label.setObjectName("becmg2_cloud1_label")
        self.becmg2_layout.addWidget(self.becmg2_cloud1_label, 1, 10, 1, 1)
        self.becmg2_cloud3_label = QtWidgets.QLabel(self.becmg2_frame)
        self.becmg2_cloud3_label.setObjectName("becmg2_cloud3_label")
        self.becmg2_layout.addWidget(self.becmg2_cloud3_label, 1, 12, 1, 1)
        self.becmg2_cloud2_label = QtWidgets.QLabel(self.becmg2_frame)
        self.becmg2_cloud2_label.setObjectName("becmg2_cloud2_label")
        self.becmg2_layout.addWidget(self.becmg2_cloud2_label, 1, 11, 1, 1)
        self.becmg2_cb = QtWidgets.QLineEdit(self.becmg2_frame)
        self.becmg2_cb.setObjectName("becmg2_cb")
        self.becmg2_layout.addWidget(self.becmg2_cb, 3, 13, 1, 1)
        self.becmg2_gust_label = QtWidgets.QLabel(self.becmg2_frame)
        self.becmg2_gust_label.setObjectName("becmg2_gust_label")
        self.becmg2_layout.addWidget(self.becmg2_gust_label, 1, 6, 1, 1)
        self.becmg2_period_label = QtWidgets.QLabel(self.becmg2_frame)
        self.becmg2_period_label.setObjectName("becmg2_period_label")
        self.becmg2_layout.addWidget(self.becmg2_period_label, 1, 4, 1, 1)
        self.becmg2_period = QtWidgets.QLineEdit(self.becmg2_frame)
        self.becmg2_period.setObjectName("becmg2_period")
        self.becmg2_layout.addWidget(self.becmg2_period, 3, 4, 1, 1)
        self.becmg2_vis = QtWidgets.QLineEdit(self.becmg2_frame)
        self.becmg2_vis.setObjectName("becmg2_vis")
        self.becmg2_layout.addWidget(self.becmg2_vis, 3, 7, 1, 1)
        self.becmg2_wind = QtWidgets.QLineEdit(self.becmg2_frame)
        self.becmg2_wind.setObjectName("becmg2_wind")
        self.becmg2_layout.addWidget(self.becmg2_wind, 3, 5, 1, 1)
        self.becmg2_cloud1 = QtWidgets.QLineEdit(self.becmg2_frame)
        self.becmg2_cloud1.setObjectName("becmg2_cloud1")
        self.becmg2_layout.addWidget(self.becmg2_cloud1, 3, 10, 1, 1)
        self.becmg2_vis_label = QtWidgets.QLabel(self.becmg2_frame)
        self.becmg2_vis_label.setObjectName("becmg2_vis_label")
        self.becmg2_layout.addWidget(self.becmg2_vis_label, 1, 7, 1, 1)
        self.becmg2_weather2_label = QtWidgets.QLabel(self.becmg2_frame)
        self.becmg2_weather2_label.setObjectName("becmg2_weather2_label")
        self.becmg2_layout.addWidget(self.becmg2_weather2_label, 1, 9, 1, 1)
        self.becmg2_weather1_label = QtWidgets.QLabel(self.becmg2_frame)
        self.becmg2_weather1_label.setObjectName("becmg2_weather1_label")
        self.becmg2_layout.addWidget(self.becmg2_weather1_label, 1, 8, 1, 1)
        self.becmg2_weather2 = QtWidgets.QComboBox(self.becmg2_frame)
        self.becmg2_weather2.setObjectName("becmg2_weather2")
        self.becmg2_layout.addWidget(self.becmg2_weather2, 3, 9, 1, 1)
        self.becmg2_line = QtWidgets.QFrame(self.becmg2_frame)
        self.becmg2_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.becmg2_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.becmg2_line.setObjectName("becmg2_line")
        self.becmg2_layout.addWidget(self.becmg2_line, 0, 3, 1, 11)
        self.becmg2_title = QtWidgets.QLineEdit(self.becmg2_frame)
        self.becmg2_title.setEnabled(False)
        self.becmg2_title.setObjectName("becmg2_title")
        self.becmg2_layout.addWidget(self.becmg2_title, 3, 3, 1, 1)
        self.becmg2_weather1 = QtWidgets.QComboBox(self.becmg2_frame)
        self.becmg2_weather1.setObjectName("becmg2_weather1")
        self.becmg2_layout.addWidget(self.becmg2_weather1, 3, 8, 1, 1)
        self.becmg2_cavok = QtWidgets.QCheckBox(self.becmg2_frame)
        self.becmg2_cavok.setObjectName("becmg2_cavok")
        self.becmg2_layout.addWidget(self.becmg2_cavok, 4, 7, 1, 1)
        self.becmg2_skc = QtWidgets.QCheckBox(self.becmg2_frame)
        self.becmg2_skc.setObjectName("becmg2_skc")
        self.becmg2_layout.addWidget(self.becmg2_skc, 4, 10, 1, 1)
        self.becmg2_nsc = QtWidgets.QCheckBox(self.becmg2_frame)
        self.becmg2_nsc.setObjectName("becmg2_nsc")
        self.becmg2_layout.addWidget(self.becmg2_nsc, 4, 11, 1, 1)
        self.becmg2.addLayout(self.becmg2_layout)
        self.verticalLayout.addWidget(self.becmg2_frame)
        self.becmg3_frame = QtWidgets.QFrame(TAFEdit)
        self.becmg3_frame.setObjectName("becmg3_frame")
        self.becmg3 = QtWidgets.QVBoxLayout(self.becmg3_frame)
        self.becmg3.setObjectName("becmg3")
        self.becmg3_layout = QtWidgets.QGridLayout()
        self.becmg3_layout.setObjectName("becmg3_layout")
        self.becmg3_cb_label = QtWidgets.QLabel(self.becmg3_frame)
        self.becmg3_cb_label.setObjectName("becmg3_cb_label")
        self.becmg3_layout.addWidget(self.becmg3_cb_label, 1, 13, 1, 1)
        self.becmg3_cloud3 = QtWidgets.QLineEdit(self.becmg3_frame)
        self.becmg3_cloud3.setObjectName("becmg3_cloud3")
        self.becmg3_layout.addWidget(self.becmg3_cloud3, 3, 12, 1, 1)
        self.becmg3_gust = QtWidgets.QLineEdit(self.becmg3_frame)
        self.becmg3_gust.setObjectName("becmg3_gust")
        self.becmg3_layout.addWidget(self.becmg3_gust, 3, 6, 1, 1)
        self.becmg3_cloud1_label = QtWidgets.QLabel(self.becmg3_frame)
        self.becmg3_cloud1_label.setObjectName("becmg3_cloud1_label")
        self.becmg3_layout.addWidget(self.becmg3_cloud1_label, 1, 10, 1, 1)
        self.becmg3_cloud3_label = QtWidgets.QLabel(self.becmg3_frame)
        self.becmg3_cloud3_label.setObjectName("becmg3_cloud3_label")
        self.becmg3_layout.addWidget(self.becmg3_cloud3_label, 1, 12, 1, 1)
        self.becmg3_cloud2 = QtWidgets.QLineEdit(self.becmg3_frame)
        self.becmg3_cloud2.setObjectName("becmg3_cloud2")
        self.becmg3_layout.addWidget(self.becmg3_cloud2, 3, 11, 1, 1)
        self.becmg3_wind_label = QtWidgets.QLabel(self.becmg3_frame)
        self.becmg3_wind_label.setObjectName("becmg3_wind_label")
        self.becmg3_layout.addWidget(self.becmg3_wind_label, 1, 5, 1, 1)
        self.becmg3_cloud2_label = QtWidgets.QLabel(self.becmg3_frame)
        self.becmg3_cloud2_label.setObjectName("becmg3_cloud2_label")
        self.becmg3_layout.addWidget(self.becmg3_cloud2_label, 1, 11, 1, 1)
        self.becmg3_cb = QtWidgets.QLineEdit(self.becmg3_frame)
        self.becmg3_cb.setObjectName("becmg3_cb")
        self.becmg3_layout.addWidget(self.becmg3_cb, 3, 13, 1, 1)
        self.becmg3_period = QtWidgets.QLineEdit(self.becmg3_frame)
        self.becmg3_period.setObjectName("becmg3_period")
        self.becmg3_layout.addWidget(self.becmg3_period, 3, 4, 1, 1)
        self.becmg3_gust_label = QtWidgets.QLabel(self.becmg3_frame)
        self.becmg3_gust_label.setObjectName("becmg3_gust_label")
        self.becmg3_layout.addWidget(self.becmg3_gust_label, 1, 6, 1, 1)
        self.becmg3_period_label = QtWidgets.QLabel(self.becmg3_frame)
        self.becmg3_period_label.setObjectName("becmg3_period_label")
        self.becmg3_layout.addWidget(self.becmg3_period_label, 1, 4, 1, 1)
        self.becmg3_vis_label = QtWidgets.QLabel(self.becmg3_frame)
        self.becmg3_vis_label.setObjectName("becmg3_vis_label")
        self.becmg3_layout.addWidget(self.becmg3_vis_label, 1, 7, 1, 1)
        self.becmg3_weather2_label = QtWidgets.QLabel(self.becmg3_frame)
        self.becmg3_weather2_label.setObjectName("becmg3_weather2_label")
        self.becmg3_layout.addWidget(self.becmg3_weather2_label, 1, 9, 1, 1)
        self.becmg3_wind = QtWidgets.QLineEdit(self.becmg3_frame)
        self.becmg3_wind.setObjectName("becmg3_wind")
        self.becmg3_layout.addWidget(self.becmg3_wind, 3, 5, 1, 1)
        self.becmg3_cloud1 = QtWidgets.QLineEdit(self.becmg3_frame)
        self.becmg3_cloud1.setObjectName("becmg3_cloud1")
        self.becmg3_layout.addWidget(self.becmg3_cloud1, 3, 10, 1, 1)
        self.becmg3_vis = QtWidgets.QLineEdit(self.becmg3_frame)
        self.becmg3_vis.setObjectName("becmg3_vis")
        self.becmg3_layout.addWidget(self.becmg3_vis, 3, 7, 1, 1)
        self.becmg3_weather1 = QtWidgets.QComboBox(self.becmg3_frame)
        self.becmg3_weather1.setObjectName("becmg3_weather1")
        self.becmg3_layout.addWidget(self.becmg3_weather1, 3, 8, 1, 1)
        self.becmg3_title = QtWidgets.QLineEdit(self.becmg3_frame)
        self.becmg3_title.setEnabled(False)
        self.becmg3_title.setObjectName("becmg3_title")
        self.becmg3_layout.addWidget(self.becmg3_title, 3, 3, 1, 1)
        self.becmg3_weather2 = QtWidgets.QComboBox(self.becmg3_frame)
        self.becmg3_weather2.setObjectName("becmg3_weather2")
        self.becmg3_layout.addWidget(self.becmg3_weather2, 3, 9, 1, 1)
        self.becmg3_line = QtWidgets.QFrame(self.becmg3_frame)
        self.becmg3_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.becmg3_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.becmg3_line.setObjectName("becmg3_line")
        self.becmg3_layout.addWidget(self.becmg3_line, 0, 3, 1, 11)
        self.becmg3_weather1_label = QtWidgets.QLabel(self.becmg3_frame)
        self.becmg3_weather1_label.setObjectName("becmg3_weather1_label")
        self.becmg3_layout.addWidget(self.becmg3_weather1_label, 1, 8, 1, 1)
        self.becmg3_cavok = QtWidgets.QCheckBox(self.becmg3_frame)
        self.becmg3_cavok.setObjectName("becmg3_cavok")
        self.becmg3_layout.addWidget(self.becmg3_cavok, 4, 7, 1, 1)
        self.becmg3_skc = QtWidgets.QCheckBox(self.becmg3_frame)
        self.becmg3_skc.setObjectName("becmg3_skc")
        self.becmg3_layout.addWidget(self.becmg3_skc, 4, 10, 1, 1)
        self.becmg3_nsc = QtWidgets.QCheckBox(self.becmg3_frame)
        self.becmg3_nsc.setObjectName("becmg3_nsc")
        self.becmg3_layout.addWidget(self.becmg3_nsc, 4, 11, 1, 1)
        self.becmg3.addLayout(self.becmg3_layout)
        self.verticalLayout.addWidget(self.becmg3_frame)
        self.tempo1_frame = QtWidgets.QFrame(TAFEdit)
        self.tempo1_frame.setObjectName("tempo1_frame")
        self.tempo1 = QtWidgets.QVBoxLayout(self.tempo1_frame)
        self.tempo1.setObjectName("tempo1")
        self.tempo1_layout = QtWidgets.QGridLayout()
        self.tempo1_layout.setObjectName("tempo1_layout")
        self.tempo1_cloud3_label = QtWidgets.QLabel(self.tempo1_frame)
        self.tempo1_cloud3_label.setObjectName("tempo1_cloud3_label")
        self.tempo1_layout.addWidget(self.tempo1_cloud3_label, 1, 12, 1, 1)
        self.tempo1_cloud2_label = QtWidgets.QLabel(self.tempo1_frame)
        self.tempo1_cloud2_label.setObjectName("tempo1_cloud2_label")
        self.tempo1_layout.addWidget(self.tempo1_cloud2_label, 1, 11, 1, 1)
        self.tempo1_wind_label = QtWidgets.QLabel(self.tempo1_frame)
        self.tempo1_wind_label.setObjectName("tempo1_wind_label")
        self.tempo1_layout.addWidget(self.tempo1_wind_label, 1, 5, 1, 1)
        self.tempo1_cb = QtWidgets.QLineEdit(self.tempo1_frame)
        self.tempo1_cb.setObjectName("tempo1_cb")
        self.tempo1_layout.addWidget(self.tempo1_cb, 3, 13, 1, 1)
        self.tempo1_period_label = QtWidgets.QLabel(self.tempo1_frame)
        self.tempo1_period_label.setObjectName("tempo1_period_label")
        self.tempo1_layout.addWidget(self.tempo1_period_label, 1, 4, 1, 1)
        self.tempo1_period = QtWidgets.QLineEdit(self.tempo1_frame)
        self.tempo1_period.setObjectName("tempo1_period")
        self.tempo1_layout.addWidget(self.tempo1_period, 3, 4, 1, 1)
        self.tempo1_gust_label = QtWidgets.QLabel(self.tempo1_frame)
        self.tempo1_gust_label.setObjectName("tempo1_gust_label")
        self.tempo1_layout.addWidget(self.tempo1_gust_label, 1, 6, 1, 1)
        self.tempo1_vis_label = QtWidgets.QLabel(self.tempo1_frame)
        self.tempo1_vis_label.setObjectName("tempo1_vis_label")
        self.tempo1_layout.addWidget(self.tempo1_vis_label, 1, 7, 1, 1)
        self.tempo1_wind = QtWidgets.QLineEdit(self.tempo1_frame)
        self.tempo1_wind.setObjectName("tempo1_wind")
        self.tempo1_layout.addWidget(self.tempo1_wind, 3, 5, 1, 1)
        self.tempo1_weather2_label = QtWidgets.QLabel(self.tempo1_frame)
        self.tempo1_weather2_label.setObjectName("tempo1_weather2_label")
        self.tempo1_layout.addWidget(self.tempo1_weather2_label, 1, 9, 1, 1)
        self.tempo1_cloud1 = QtWidgets.QLineEdit(self.tempo1_frame)
        self.tempo1_cloud1.setObjectName("tempo1_cloud1")
        self.tempo1_layout.addWidget(self.tempo1_cloud1, 3, 10, 1, 1)
        self.tempo1_weather2 = QtWidgets.QComboBox(self.tempo1_frame)
        self.tempo1_weather2.setObjectName("tempo1_weather2")
        self.tempo1_layout.addWidget(self.tempo1_weather2, 3, 9, 1, 1)
        self.tempo1_vis = QtWidgets.QLineEdit(self.tempo1_frame)
        self.tempo1_vis.setObjectName("tempo1_vis")
        self.tempo1_layout.addWidget(self.tempo1_vis, 3, 7, 1, 1)
        self.tempo1_weather1 = QtWidgets.QComboBox(self.tempo1_frame)
        self.tempo1_weather1.setObjectName("tempo1_weather1")
        self.tempo1_layout.addWidget(self.tempo1_weather1, 3, 8, 1, 1)
        self.tempo1_title = QtWidgets.QLineEdit(self.tempo1_frame)
        self.tempo1_title.setEnabled(False)
        self.tempo1_title.setObjectName("tempo1_title")
        self.tempo1_layout.addWidget(self.tempo1_title, 3, 3, 1, 1)
        self.tempo1_weather1_label = QtWidgets.QLabel(self.tempo1_frame)
        self.tempo1_weather1_label.setObjectName("tempo1_weather1_label")
        self.tempo1_layout.addWidget(self.tempo1_weather1_label, 1, 8, 1, 1)
        self.tempo1_line = QtWidgets.QFrame(self.tempo1_frame)
        self.tempo1_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.tempo1_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tempo1_line.setObjectName("tempo1_line")
        self.tempo1_layout.addWidget(self.tempo1_line, 0, 3, 1, 11)
        self.tempo1_gust = QtWidgets.QLineEdit(self.tempo1_frame)
        self.tempo1_gust.setObjectName("tempo1_gust")
        self.tempo1_layout.addWidget(self.tempo1_gust, 3, 6, 1, 1)
        self.tempo1_cloud1_label = QtWidgets.QLabel(self.tempo1_frame)
        self.tempo1_cloud1_label.setObjectName("tempo1_cloud1_label")
        self.tempo1_layout.addWidget(self.tempo1_cloud1_label, 1, 10, 1, 1)
        self.tempo1_cb_label = QtWidgets.QLabel(self.tempo1_frame)
        self.tempo1_cb_label.setObjectName("tempo1_cb_label")
        self.tempo1_layout.addWidget(self.tempo1_cb_label, 1, 13, 1, 1)
        self.tempo1_cloud2 = QtWidgets.QLineEdit(self.tempo1_frame)
        self.tempo1_cloud2.setObjectName("tempo1_cloud2")
        self.tempo1_layout.addWidget(self.tempo1_cloud2, 3, 11, 1, 1)
        self.tempo1_cloud3 = QtWidgets.QLineEdit(self.tempo1_frame)
        self.tempo1_cloud3.setObjectName("tempo1_cloud3")
        self.tempo1_layout.addWidget(self.tempo1_cloud3, 3, 12, 1, 1)
        self.tempo1_prob30 = QtWidgets.QCheckBox(self.tempo1_frame)
        self.tempo1_prob30.setObjectName("tempo1_prob30")
        self.tempo1_layout.addWidget(self.tempo1_prob30, 4, 4, 1, 1)
        self.tempo1_prob40 = QtWidgets.QCheckBox(self.tempo1_frame)
        self.tempo1_prob40.setObjectName("tempo1_prob40")
        self.tempo1_layout.addWidget(self.tempo1_prob40, 4, 5, 1, 1)
        self.tempo1.addLayout(self.tempo1_layout)
        self.verticalLayout.addWidget(self.tempo1_frame)
        self.tempo2_frame = QtWidgets.QFrame(TAFEdit)
        self.tempo2_frame.setObjectName("tempo2_frame")
        self.tempo2 = QtWidgets.QVBoxLayout(self.tempo2_frame)
        self.tempo2.setObjectName("tempo2")
        self.tempo2_layout = QtWidgets.QGridLayout()
        self.tempo2_layout.setObjectName("tempo2_layout")
        self.tempo2_cloud3_label = QtWidgets.QLabel(self.tempo2_frame)
        self.tempo2_cloud3_label.setObjectName("tempo2_cloud3_label")
        self.tempo2_layout.addWidget(self.tempo2_cloud3_label, 1, 12, 1, 1)
        self.tempo2_cloud2_label = QtWidgets.QLabel(self.tempo2_frame)
        self.tempo2_cloud2_label.setObjectName("tempo2_cloud2_label")
        self.tempo2_layout.addWidget(self.tempo2_cloud2_label, 1, 11, 1, 1)
        self.tempo2_wind_label = QtWidgets.QLabel(self.tempo2_frame)
        self.tempo2_wind_label.setObjectName("tempo2_wind_label")
        self.tempo2_layout.addWidget(self.tempo2_wind_label, 1, 5, 1, 1)
        self.tempo2_cb = QtWidgets.QLineEdit(self.tempo2_frame)
        self.tempo2_cb.setObjectName("tempo2_cb")
        self.tempo2_layout.addWidget(self.tempo2_cb, 3, 13, 1, 1)
        self.tempo2_period_label = QtWidgets.QLabel(self.tempo2_frame)
        self.tempo2_period_label.setObjectName("tempo2_period_label")
        self.tempo2_layout.addWidget(self.tempo2_period_label, 1, 4, 1, 1)
        self.tempo2_period = QtWidgets.QLineEdit(self.tempo2_frame)
        self.tempo2_period.setObjectName("tempo2_period")
        self.tempo2_layout.addWidget(self.tempo2_period, 3, 4, 1, 1)
        self.tempo2_gust_label = QtWidgets.QLabel(self.tempo2_frame)
        self.tempo2_gust_label.setObjectName("tempo2_gust_label")
        self.tempo2_layout.addWidget(self.tempo2_gust_label, 1, 6, 1, 1)
        self.tempo2_vis_label = QtWidgets.QLabel(self.tempo2_frame)
        self.tempo2_vis_label.setObjectName("tempo2_vis_label")
        self.tempo2_layout.addWidget(self.tempo2_vis_label, 1, 7, 1, 1)
        self.tempo2_wind = QtWidgets.QLineEdit(self.tempo2_frame)
        self.tempo2_wind.setObjectName("tempo2_wind")
        self.tempo2_layout.addWidget(self.tempo2_wind, 3, 5, 1, 1)
        self.tempo2_weather2_label = QtWidgets.QLabel(self.tempo2_frame)
        self.tempo2_weather2_label.setObjectName("tempo2_weather2_label")
        self.tempo2_layout.addWidget(self.tempo2_weather2_label, 1, 9, 1, 1)
        self.tempo2_cloud1 = QtWidgets.QLineEdit(self.tempo2_frame)
        self.tempo2_cloud1.setObjectName("tempo2_cloud1")
        self.tempo2_layout.addWidget(self.tempo2_cloud1, 3, 10, 1, 1)
        self.tempo2_weather2 = QtWidgets.QComboBox(self.tempo2_frame)
        self.tempo2_weather2.setObjectName("tempo2_weather2")
        self.tempo2_layout.addWidget(self.tempo2_weather2, 3, 9, 1, 1)
        self.tempo2_vis = QtWidgets.QLineEdit(self.tempo2_frame)
        self.tempo2_vis.setObjectName("tempo2_vis")
        self.tempo2_layout.addWidget(self.tempo2_vis, 3, 7, 1, 1)
        self.tempo2_weather1 = QtWidgets.QComboBox(self.tempo2_frame)
        self.tempo2_weather1.setObjectName("tempo2_weather1")
        self.tempo2_layout.addWidget(self.tempo2_weather1, 3, 8, 1, 1)
        self.tempo2_title = QtWidgets.QLineEdit(self.tempo2_frame)
        self.tempo2_title.setEnabled(False)
        self.tempo2_title.setObjectName("tempo2_title")
        self.tempo2_layout.addWidget(self.tempo2_title, 3, 3, 1, 1)
        self.tempo2_weather1_label = QtWidgets.QLabel(self.tempo2_frame)
        self.tempo2_weather1_label.setObjectName("tempo2_weather1_label")
        self.tempo2_layout.addWidget(self.tempo2_weather1_label, 1, 8, 1, 1)
        self.tempo2_line = QtWidgets.QFrame(self.tempo2_frame)
        self.tempo2_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.tempo2_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tempo2_line.setObjectName("tempo2_line")
        self.tempo2_layout.addWidget(self.tempo2_line, 0, 3, 1, 11)
        self.tempo2_gust = QtWidgets.QLineEdit(self.tempo2_frame)
        self.tempo2_gust.setObjectName("tempo2_gust")
        self.tempo2_layout.addWidget(self.tempo2_gust, 3, 6, 1, 1)
        self.tempo2_cloud1_label = QtWidgets.QLabel(self.tempo2_frame)
        self.tempo2_cloud1_label.setObjectName("tempo2_cloud1_label")
        self.tempo2_layout.addWidget(self.tempo2_cloud1_label, 1, 10, 1, 1)
        self.tempo2_cb_label = QtWidgets.QLabel(self.tempo2_frame)
        self.tempo2_cb_label.setObjectName("tempo2_cb_label")
        self.tempo2_layout.addWidget(self.tempo2_cb_label, 1, 13, 1, 1)
        self.tempo2_cloud2 = QtWidgets.QLineEdit(self.tempo2_frame)
        self.tempo2_cloud2.setObjectName("tempo2_cloud2")
        self.tempo2_layout.addWidget(self.tempo2_cloud2, 3, 11, 1, 1)
        self.tempo2_cloud3 = QtWidgets.QLineEdit(self.tempo2_frame)
        self.tempo2_cloud3.setObjectName("tempo2_cloud3")
        self.tempo2_layout.addWidget(self.tempo2_cloud3, 3, 12, 1, 1)
        self.tempo2_prob30 = QtWidgets.QCheckBox(self.tempo2_frame)
        self.tempo2_prob30.setObjectName("tempo2_prob30")
        self.tempo2_layout.addWidget(self.tempo2_prob30, 4, 4, 1, 1)
        self.tempo2_prob40 = QtWidgets.QCheckBox(self.tempo2_frame)
        self.tempo2_prob40.setObjectName("tempo2_prob40")
        self.tempo2_layout.addWidget(self.tempo2_prob40, 4, 5, 1, 1)
        self.tempo2.addLayout(self.tempo2_layout)
        self.verticalLayout.addWidget(self.tempo2_frame)
        self.taf_next = QtWidgets.QPushButton(TAFEdit)
        self.taf_next.setMaximumSize(QtCore.QSize(70, 23))
        self.taf_next.setObjectName("taf_next")
        self.verticalLayout.addWidget(self.taf_next, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.taf_cloud3_label.setBuddy(self.taf_cloud3)
        self.taf_cloud1_label.setBuddy(self.taf_cloud1)
        self.taf_cloud2_label.setBuddy(self.taf_cloud2)
        self.taf_temp_min_label.setBuddy(self.taf_temp_min)
        self.taf_vis_label.setBuddy(self.taf_vis)
        self.taf_weather1_label.setBuddy(self.taf_weather1_combobox)
        self.taf_gust_label.setBuddy(self.taf_gust)
        self.taf_date_label.setBuddy(self.taf_date)
        self.taf_period_label.setBuddy(self.taf_period)
        self.taf_cb_label.setBuddy(self.taf_cb)
        self.taf_wind_label.setBuddy(self.taf_wind)
        self.taf_temp_max_label.setBuddy(self.taf_temp_max)
        self.taf_weather2_label.setBuddy(self.taf_weather2_combobox)
        self.becmg1_cloud2_label.setBuddy(self.becmg1_cloud2)
        self.becmg1_cloud3_label.setBuddy(self.becmg1_cloud3)
        self.becmg1_wind_label.setBuddy(self.becmg1_wind)
        self.becmg1_gust_label.setBuddy(self.becmg1_gust)
        self.becmg1_period_label.setBuddy(self.becmg1_period)
        self.becmg1_vis_label.setBuddy(self.becmg1_vis)
        self.becmg1_weather2_label.setBuddy(self.becmg1_weather2)
        self.becmg1_weather1_label.setBuddy(self.becmg1_weather1)
        self.becmg1_cb_label.setBuddy(self.becmg1_cb)
        self.becmg1_cloud1_label.setBuddy(self.becmg1_cloud1)
        self.becmg2_cb_label.setBuddy(self.becmg2_cb)
        self.becmg2_wind_label.setBuddy(self.becmg2_wind)
        self.becmg2_cloud1_label.setBuddy(self.becmg2_cloud1)
        self.becmg2_cloud3_label.setBuddy(self.becmg2_cloud3)
        self.becmg2_cloud2_label.setBuddy(self.becmg2_cloud2)
        self.becmg2_gust_label.setBuddy(self.becmg2_gust)
        self.becmg2_period_label.setBuddy(self.becmg2_period)
        self.becmg2_vis_label.setBuddy(self.becmg2_vis)
        self.becmg2_weather2_label.setBuddy(self.becmg2_weather2)
        self.becmg2_weather1_label.setBuddy(self.becmg2_weather1)
        self.becmg3_cb_label.setBuddy(self.becmg3_cb)
        self.becmg3_cloud1_label.setBuddy(self.becmg3_cloud1)
        self.becmg3_cloud3_label.setBuddy(self.becmg3_cloud3)
        self.becmg3_wind_label.setBuddy(self.becmg3_wind)
        self.becmg3_cloud2_label.setBuddy(self.becmg3_cloud2)
        self.becmg3_gust_label.setBuddy(self.becmg3_gust)
        self.becmg3_period_label.setBuddy(self.becmg3_period)
        self.becmg3_vis_label.setBuddy(self.becmg3_vis)
        self.becmg3_weather2_label.setBuddy(self.becmg3_weather2)
        self.becmg3_weather1_label.setBuddy(self.becmg3_weather1)
        self.tempo1_cloud3_label.setBuddy(self.tempo1_cloud3)
        self.tempo1_cloud2_label.setBuddy(self.tempo1_cloud2)
        self.tempo1_wind_label.setBuddy(self.tempo1_wind)
        self.tempo1_period_label.setBuddy(self.tempo1_period)
        self.tempo1_gust_label.setBuddy(self.tempo1_gust)
        self.tempo1_vis_label.setBuddy(self.tempo1_vis)
        self.tempo1_weather2_label.setBuddy(self.tempo1_weather2)
        self.tempo1_weather1_label.setBuddy(self.tempo1_weather1)
        self.tempo1_cloud1_label.setBuddy(self.tempo1_cloud1)
        self.tempo1_cb_label.setBuddy(self.tempo1_cb)
        self.tempo2_cloud3_label.setBuddy(self.tempo2_cloud3)
        self.tempo2_cloud2_label.setBuddy(self.tempo2_cloud2)
        self.tempo2_wind_label.setBuddy(self.tempo2_wind)
        self.tempo2_period_label.setBuddy(self.tempo2_period)
        self.tempo2_gust_label.setBuddy(self.tempo2_gust)
        self.tempo2_vis_label.setBuddy(self.tempo2_vis)
        self.tempo2_weather2_label.setBuddy(self.tempo2_weather2)
        self.tempo2_weather1_label.setBuddy(self.tempo2_weather1)
        self.tempo2_cloud1_label.setBuddy(self.tempo2_cloud1)
        self.tempo2_cb_label.setBuddy(self.tempo2_cb)

        self.retranslateUi(TAFEdit)
        QtCore.QMetaObject.connectSlotsByName(TAFEdit)
        TAFEdit.setTabOrder(self.taf_date, self.taf_period)
        TAFEdit.setTabOrder(self.taf_period, self.taf_wind)
        TAFEdit.setTabOrder(self.taf_wind, self.taf_gust)
        TAFEdit.setTabOrder(self.taf_gust, self.taf_vis)
        TAFEdit.setTabOrder(self.taf_vis, self.taf_weather1_combobox)
        TAFEdit.setTabOrder(self.taf_weather1_combobox, self.taf_weather2_combobox)
        TAFEdit.setTabOrder(self.taf_weather2_combobox, self.taf_cloud1)
        TAFEdit.setTabOrder(self.taf_cloud1, self.taf_cloud2)
        TAFEdit.setTabOrder(self.taf_cloud2, self.taf_cloud3)
        TAFEdit.setTabOrder(self.taf_cloud3, self.taf_cb)
        TAFEdit.setTabOrder(self.taf_cb, self.taf_cavok)
        TAFEdit.setTabOrder(self.taf_cavok, self.taf_skc)
        TAFEdit.setTabOrder(self.taf_skc, self.taf_nsc)
        TAFEdit.setTabOrder(self.taf_nsc, self.taf_temp_max)
        TAFEdit.setTabOrder(self.taf_temp_max, self.taf_temp_min)
        TAFEdit.setTabOrder(self.taf_temp_min, self.becmg1_checkbox)
        TAFEdit.setTabOrder(self.becmg1_checkbox, self.becmg2_checkbox)
        TAFEdit.setTabOrder(self.becmg2_checkbox, self.becmg3_checkbox)
        TAFEdit.setTabOrder(self.becmg3_checkbox, self.tempo1_checkbox)
        TAFEdit.setTabOrder(self.tempo1_checkbox, self.tempo2_checkbox)
        TAFEdit.setTabOrder(self.tempo2_checkbox, self.becmg1_title)
        TAFEdit.setTabOrder(self.becmg1_title, self.becmg1_period)
        TAFEdit.setTabOrder(self.becmg1_period, self.becmg1_wind)
        TAFEdit.setTabOrder(self.becmg1_wind, self.becmg1_gust)
        TAFEdit.setTabOrder(self.becmg1_gust, self.becmg1_vis)
        TAFEdit.setTabOrder(self.becmg1_vis, self.becmg1_weather1)
        TAFEdit.setTabOrder(self.becmg1_weather1, self.becmg1_weather2)
        TAFEdit.setTabOrder(self.becmg1_weather2, self.becmg1_cloud1)
        TAFEdit.setTabOrder(self.becmg1_cloud1, self.becmg1_cloud2)
        TAFEdit.setTabOrder(self.becmg1_cloud2, self.becmg1_cloud3)
        TAFEdit.setTabOrder(self.becmg1_cloud3, self.becmg1_cb)
        TAFEdit.setTabOrder(self.becmg1_cb, self.becmg1_cavok)
        TAFEdit.setTabOrder(self.becmg1_cavok, self.becmg1_skc)
        TAFEdit.setTabOrder(self.becmg1_skc, self.becmg1_nsc)
        TAFEdit.setTabOrder(self.becmg1_nsc, self.becmg2_title)
        TAFEdit.setTabOrder(self.becmg2_title, self.becmg2_period)
        TAFEdit.setTabOrder(self.becmg2_period, self.becmg2_wind)
        TAFEdit.setTabOrder(self.becmg2_wind, self.becmg2_gust)
        TAFEdit.setTabOrder(self.becmg2_gust, self.becmg2_vis)
        TAFEdit.setTabOrder(self.becmg2_vis, self.becmg2_weather1)
        TAFEdit.setTabOrder(self.becmg2_weather1, self.becmg2_weather2)
        TAFEdit.setTabOrder(self.becmg2_weather2, self.becmg2_cloud1)
        TAFEdit.setTabOrder(self.becmg2_cloud1, self.becmg2_cloud2)
        TAFEdit.setTabOrder(self.becmg2_cloud2, self.becmg2_cloud3)
        TAFEdit.setTabOrder(self.becmg2_cloud3, self.becmg2_cb)
        TAFEdit.setTabOrder(self.becmg2_cb, self.becmg2_cavok)
        TAFEdit.setTabOrder(self.becmg2_cavok, self.becmg2_skc)
        TAFEdit.setTabOrder(self.becmg2_skc, self.becmg2_nsc)
        TAFEdit.setTabOrder(self.becmg2_nsc, self.becmg3_title)
        TAFEdit.setTabOrder(self.becmg3_title, self.becmg3_period)
        TAFEdit.setTabOrder(self.becmg3_period, self.becmg3_wind)
        TAFEdit.setTabOrder(self.becmg3_wind, self.becmg3_gust)
        TAFEdit.setTabOrder(self.becmg3_gust, self.becmg3_vis)
        TAFEdit.setTabOrder(self.becmg3_vis, self.becmg3_weather1)
        TAFEdit.setTabOrder(self.becmg3_weather1, self.becmg3_weather2)
        TAFEdit.setTabOrder(self.becmg3_weather2, self.becmg3_cloud1)
        TAFEdit.setTabOrder(self.becmg3_cloud1, self.becmg3_cloud2)
        TAFEdit.setTabOrder(self.becmg3_cloud2, self.becmg3_cloud3)
        TAFEdit.setTabOrder(self.becmg3_cloud3, self.becmg3_cb)
        TAFEdit.setTabOrder(self.becmg3_cb, self.becmg3_cavok)
        TAFEdit.setTabOrder(self.becmg3_cavok, self.becmg3_skc)
        TAFEdit.setTabOrder(self.becmg3_skc, self.becmg3_nsc)
        TAFEdit.setTabOrder(self.becmg3_nsc, self.tempo1_title)
        TAFEdit.setTabOrder(self.tempo1_title, self.tempo1_prob30)
        TAFEdit.setTabOrder(self.tempo1_prob30, self.tempo1_prob40)
        TAFEdit.setTabOrder(self.tempo1_prob40, self.tempo1_period)
        TAFEdit.setTabOrder(self.tempo1_period, self.tempo1_wind)
        TAFEdit.setTabOrder(self.tempo1_wind, self.tempo1_gust)
        TAFEdit.setTabOrder(self.tempo1_gust, self.tempo1_vis)
        TAFEdit.setTabOrder(self.tempo1_vis, self.tempo1_weather1)
        TAFEdit.setTabOrder(self.tempo1_weather1, self.tempo1_weather2)
        TAFEdit.setTabOrder(self.tempo1_weather2, self.tempo1_cloud1)
        TAFEdit.setTabOrder(self.tempo1_cloud1, self.tempo1_cloud2)
        TAFEdit.setTabOrder(self.tempo1_cloud2, self.tempo1_cloud3)
        TAFEdit.setTabOrder(self.tempo1_cloud3, self.tempo1_cb)
        TAFEdit.setTabOrder(self.tempo1_cb, self.tempo2_title)
        TAFEdit.setTabOrder(self.tempo2_title, self.tempo2_prob30)
        TAFEdit.setTabOrder(self.tempo2_prob30, self.tempo2_prob40)
        TAFEdit.setTabOrder(self.tempo2_prob40, self.tempo2_period)
        TAFEdit.setTabOrder(self.tempo2_period, self.tempo2_wind)
        TAFEdit.setTabOrder(self.tempo2_wind, self.tempo2_gust)
        TAFEdit.setTabOrder(self.tempo2_gust, self.tempo2_vis)
        TAFEdit.setTabOrder(self.tempo2_vis, self.tempo2_weather1)
        TAFEdit.setTabOrder(self.tempo2_weather1, self.tempo2_weather2)
        TAFEdit.setTabOrder(self.tempo2_weather2, self.tempo2_cloud1)
        TAFEdit.setTabOrder(self.tempo2_cloud1, self.tempo2_cloud2)
        TAFEdit.setTabOrder(self.tempo2_cloud2, self.tempo2_cloud3)
        TAFEdit.setTabOrder(self.tempo2_cloud3, self.tempo2_cb)
        TAFEdit.setTabOrder(self.tempo2_cb, self.taf_next)

    def retranslateUi(self, TAFEdit):
        _translate = QtCore.QCoreApplication.translate
        TAFEdit.setWindowTitle(_translate("TAFEdit", "TAF"))
        self.taf_skc.setText(_translate("TAFEdit", "SKC"))
        self.tempo1_checkbox.setText(_translate("TAFEdit", "TEMPO1"))
        self.taf_cloud3_label.setText(_translate("TAFEdit", "云组3"))
        self.becmg2_checkbox.setText(_translate("TAFEdit", "BECMG2"))
        self.taf_cloud1_label.setText(_translate("TAFEdit", "云组1"))
        self.taf_cloud2_label.setText(_translate("TAFEdit", "云组2"))
        self.taf_nsc.setText(_translate("TAFEdit", "NSC"))
        self.taf_temp_min_label.setText(_translate("TAFEdit", "最低温"))
        self.becmg3_checkbox.setText(_translate("TAFEdit", "BECMG3"))
        self.taf_vis_label.setText(_translate("TAFEdit", "能见度"))
        self.taf_weather1_label.setText(_translate("TAFEdit", "天气现象1"))
        self.taf_gust_label.setText(_translate("TAFEdit", "阵风"))
        self.taf_cavok.setText(_translate("TAFEdit", "CAVOK"))
        self.becmg1_checkbox.setText(_translate("TAFEdit", "BECMG1"))
        self.taf_date_label.setText(_translate("TAFEdit", "日期"))
        self.taf_period_label.setText(_translate("TAFEdit", "时段"))
        self.taf_cb_label.setText(_translate("TAFEdit", "积雨云"))
        self.taf_wind_label.setText(_translate("TAFEdit", "风向风速"))
        self.taf_temp_max_label.setText(_translate("TAFEdit", "最高温"))
        self.taf_weather2_label.setText(_translate("TAFEdit", "天气现象2"))
        self.tempo2_checkbox.setText(_translate("TAFEdit", "TEMPO2"))
        self.type_fc.setText(_translate("TAFEdit", "FC"))
        self.type_ft.setText(_translate("TAFEdit", "FT"))
        self.cls_normal.setText(_translate("TAFEdit", "正常报"))
        self.cls_cor.setText(_translate("TAFEdit", "更正报"))
        self.cls_amd.setText(_translate("TAFEdit", "修订报"))
        self.cls_cnl.setText(_translate("TAFEdit", "取消报"))
        self.becmg1_cloud2_label.setText(_translate("TAFEdit", "云组2"))
        self.becmg1_cloud3_label.setText(_translate("TAFEdit", "云组3"))
        self.becmg1_wind_label.setText(_translate("TAFEdit", "风向风速"))
        self.becmg1_gust_label.setText(_translate("TAFEdit", "阵风"))
        self.becmg1_period_label.setText(_translate("TAFEdit", "时段"))
        self.becmg1_vis_label.setText(_translate("TAFEdit", "能见度"))
        self.becmg1_weather2_label.setText(_translate("TAFEdit", "天气现象2"))
        self.becmg1_title.setText(_translate("TAFEdit", "BECMG1"))
        self.becmg1_weather1_label.setText(_translate("TAFEdit", "天气现象1"))
        self.becmg1_cb_label.setText(_translate("TAFEdit", "积雨云"))
        self.becmg1_cloud1_label.setText(_translate("TAFEdit", "云组1"))
        self.becmg1_cavok.setText(_translate("TAFEdit", "CAVOK"))
        self.becmg1_skc.setText(_translate("TAFEdit", "SKC"))
        self.becmg1_nsc.setText(_translate("TAFEdit", "NSC"))
        self.becmg2_cb_label.setText(_translate("TAFEdit", "积雨云"))
        self.becmg2_wind_label.setText(_translate("TAFEdit", "风向风速"))
        self.becmg2_cloud1_label.setText(_translate("TAFEdit", "云组1"))
        self.becmg2_cloud3_label.setText(_translate("TAFEdit", "云组3"))
        self.becmg2_cloud2_label.setText(_translate("TAFEdit", "云组2"))
        self.becmg2_gust_label.setText(_translate("TAFEdit", "阵风"))
        self.becmg2_period_label.setText(_translate("TAFEdit", "时段"))
        self.becmg2_vis_label.setText(_translate("TAFEdit", "能见度"))
        self.becmg2_weather2_label.setText(_translate("TAFEdit", "天气现象2"))
        self.becmg2_weather1_label.setText(_translate("TAFEdit", "天气现象1"))
        self.becmg2_title.setText(_translate("TAFEdit", "BECMG2"))
        self.becmg2_cavok.setText(_translate("TAFEdit", "CAVOK"))
        self.becmg2_skc.setText(_translate("TAFEdit", "SKC"))
        self.becmg2_nsc.setText(_translate("TAFEdit", "NSC"))
        self.becmg3_cb_label.setText(_translate("TAFEdit", "积雨云"))
        self.becmg3_cloud1_label.setText(_translate("TAFEdit", "云组1"))
        self.becmg3_cloud3_label.setText(_translate("TAFEdit", "云组3"))
        self.becmg3_wind_label.setText(_translate("TAFEdit", "风向风速"))
        self.becmg3_cloud2_label.setText(_translate("TAFEdit", "云组2"))
        self.becmg3_gust_label.setText(_translate("TAFEdit", "阵风"))
        self.becmg3_period_label.setText(_translate("TAFEdit", "时段"))
        self.becmg3_vis_label.setText(_translate("TAFEdit", "能见度"))
        self.becmg3_weather2_label.setText(_translate("TAFEdit", "天气现象2"))
        self.becmg3_title.setText(_translate("TAFEdit", "BECMG3"))
        self.becmg3_weather1_label.setText(_translate("TAFEdit", "天气现象1"))
        self.becmg3_cavok.setText(_translate("TAFEdit", "CAVOK"))
        self.becmg3_skc.setText(_translate("TAFEdit", "SKC"))
        self.becmg3_nsc.setText(_translate("TAFEdit", "NSC"))
        self.tempo1_cloud3_label.setText(_translate("TAFEdit", "云组3"))
        self.tempo1_cloud2_label.setText(_translate("TAFEdit", "云组2"))
        self.tempo1_wind_label.setText(_translate("TAFEdit", "风向风速"))
        self.tempo1_period_label.setText(_translate("TAFEdit", "时段"))
        self.tempo1_gust_label.setText(_translate("TAFEdit", "阵风"))
        self.tempo1_vis_label.setText(_translate("TAFEdit", "能见度"))
        self.tempo1_weather2_label.setText(_translate("TAFEdit", "天气现象2"))
        self.tempo1_title.setText(_translate("TAFEdit", "TEMPO1"))
        self.tempo1_weather1_label.setText(_translate("TAFEdit", "天气现象1"))
        self.tempo1_cloud1_label.setText(_translate("TAFEdit", "云组1"))
        self.tempo1_cb_label.setText(_translate("TAFEdit", "积雨云"))
        self.tempo1_prob30.setText(_translate("TAFEdit", "PROB30"))
        self.tempo1_prob40.setText(_translate("TAFEdit", "PROB40"))
        self.tempo2_cloud3_label.setText(_translate("TAFEdit", "云组3"))
        self.tempo2_cloud2_label.setText(_translate("TAFEdit", "云组2"))
        self.tempo2_wind_label.setText(_translate("TAFEdit", "风向风速"))
        self.tempo2_period_label.setText(_translate("TAFEdit", "时段"))
        self.tempo2_gust_label.setText(_translate("TAFEdit", "阵风"))
        self.tempo2_vis_label.setText(_translate("TAFEdit", "能见度"))
        self.tempo2_weather2_label.setText(_translate("TAFEdit", "天气现象2"))
        self.tempo2_title.setText(_translate("TAFEdit", "TEMPO2"))
        self.tempo2_weather1_label.setText(_translate("TAFEdit", "天气现象1"))
        self.tempo2_cloud1_label.setText(_translate("TAFEdit", "云组1"))
        self.tempo2_cb_label.setText(_translate("TAFEdit", "积雨云"))
        self.tempo2_prob30.setText(_translate("TAFEdit", "PROB30"))
        self.tempo2_prob40.setText(_translate("TAFEdit", "PROB40"))
        self.taf_next.setText(_translate("TAFEdit", "下一步"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TAFEdit = QtWidgets.QDialog()
    ui = Ui_TAFEdit()
    ui.setupUi(TAFEdit)
    TAFEdit.show()
    sys.exit(app.exec_())

