# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Work\tafor\tafor\ui\taf.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TAFEdit(object):
    def setupUi(self, TAFEdit):
        TAFEdit.setObjectName("TAFEdit")
        TAFEdit.resize(1024, 720)
        TAFEdit.setMaximumSize(QtCore.QSize(1024, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(TAFEdit)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_frame = QtWidgets.QFrame(TAFEdit)
        self.main_frame.setObjectName("main_frame")
        self.main = QtWidgets.QVBoxLayout(self.main_frame)
        self.main.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.main.setObjectName("main")
        self.verticalLayout.addWidget(self.main_frame)
        self.becmg1_frame = QtWidgets.QFrame(TAFEdit)
        self.becmg1_frame.setObjectName("becmg1_frame")
        self.becmg1 = QtWidgets.QVBoxLayout(self.becmg1_frame)
        self.becmg1.setObjectName("becmg1")
        self.verticalLayout.addWidget(self.becmg1_frame)
        self.becmg2_frame = QtWidgets.QFrame(TAFEdit)
        self.becmg2_frame.setObjectName("becmg2_frame")
        self.becmg2 = QtWidgets.QVBoxLayout(self.becmg2_frame)
        self.becmg2.setObjectName("becmg2")
        self.verticalLayout.addWidget(self.becmg2_frame)
        self.becmg3_frame = QtWidgets.QFrame(TAFEdit)
        self.becmg3_frame.setObjectName("becmg3_frame")
        self.becmg3 = QtWidgets.QVBoxLayout(self.becmg3_frame)
        self.becmg3.setObjectName("becmg3")
        self.verticalLayout.addWidget(self.becmg3_frame)
        self.tempo1_frame = QtWidgets.QFrame(TAFEdit)
        self.tempo1_frame.setObjectName("tempo1_frame")
        self.tempo1 = QtWidgets.QVBoxLayout(self.tempo1_frame)
        self.tempo1.setObjectName("tempo1")
        self.verticalLayout.addWidget(self.tempo1_frame)
        self.tempo2_frame = QtWidgets.QFrame(TAFEdit)
        self.tempo2_frame.setObjectName("tempo2_frame")
        self.tempo2 = QtWidgets.QVBoxLayout(self.tempo2_frame)
        self.tempo2.setObjectName("tempo2")
        self.tempo2_layout = QtWidgets.QGridLayout()
        self.tempo2_layout.setObjectName("tempo2_layout")
        self.tempo2_cloud3_label = QtWidgets.QLabel(self.tempo2_frame)
        self.tempo2_cloud3_label.setObjectName("tempo2_cloud3_label")
        self.tempo2_layout.addWidget(self.tempo2_cloud3_label, 1, 12, 1, 1)
        self.tempo2_wind_label = QtWidgets.QLabel(self.tempo2_frame)
        self.tempo2_wind_label.setObjectName("tempo2_wind_label")
        self.tempo2_layout.addWidget(self.tempo2_wind_label, 1, 5, 1, 1)
        self.tempo2_period_label = QtWidgets.QLabel(self.tempo2_frame)
        self.tempo2_period_label.setObjectName("tempo2_period_label")
        self.tempo2_layout.addWidget(self.tempo2_period_label, 1, 4, 1, 1)
        self.tempo2_gust_label = QtWidgets.QLabel(self.tempo2_frame)
        self.tempo2_gust_label.setObjectName("tempo2_gust_label")
        self.tempo2_layout.addWidget(self.tempo2_gust_label, 1, 6, 1, 1)
        self.tempo2_cloud2_label = QtWidgets.QLabel(self.tempo2_frame)
        self.tempo2_cloud2_label.setObjectName("tempo2_cloud2_label")
        self.tempo2_layout.addWidget(self.tempo2_cloud2_label, 1, 11, 1, 1)
        self.tempo2_weather2_label = QtWidgets.QLabel(self.tempo2_frame)
        self.tempo2_weather2_label.setObjectName("tempo2_weather2_label")
        self.tempo2_layout.addWidget(self.tempo2_weather2_label, 1, 9, 1, 1)
        self.tempo2_cloud1_label = QtWidgets.QLabel(self.tempo2_frame)
        self.tempo2_cloud1_label.setObjectName("tempo2_cloud1_label")
        self.tempo2_layout.addWidget(self.tempo2_cloud1_label, 1, 10, 1, 1)
        self.tempo2_vis_label = QtWidgets.QLabel(self.tempo2_frame)
        self.tempo2_vis_label.setObjectName("tempo2_vis_label")
        self.tempo2_layout.addWidget(self.tempo2_vis_label, 1, 7, 1, 1)
        self.tempo2_line = QtWidgets.QFrame(self.tempo2_frame)
        self.tempo2_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.tempo2_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tempo2_line.setObjectName("tempo2_line")
        self.tempo2_layout.addWidget(self.tempo2_line, 0, 3, 1, 11)
        self.tempo2_weather1_label = QtWidgets.QLabel(self.tempo2_frame)
        self.tempo2_weather1_label.setObjectName("tempo2_weather1_label")
        self.tempo2_layout.addWidget(self.tempo2_weather1_label, 1, 8, 1, 1)
        self.tempo2_cb_label = QtWidgets.QLabel(self.tempo2_frame)
        self.tempo2_cb_label.setObjectName("tempo2_cb_label")
        self.tempo2_layout.addWidget(self.tempo2_cb_label, 1, 13, 1, 1)
        self.tempo2.addLayout(self.tempo2_layout)
        self.verticalLayout.addWidget(self.tempo2_frame)
        self.taf_next = QtWidgets.QPushButton(TAFEdit)
        self.taf_next.setMaximumSize(QtCore.QSize(70, 23))
        self.taf_next.setObjectName("taf_next")
        self.verticalLayout.addWidget(self.taf_next, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)

        self.retranslateUi(TAFEdit)
        QtCore.QMetaObject.connectSlotsByName(TAFEdit)

    def retranslateUi(self, TAFEdit):
        _translate = QtCore.QCoreApplication.translate
        TAFEdit.setWindowTitle(_translate("TAFEdit", "TAF"))
        self.tempo2_cloud3_label.setText(_translate("TAFEdit", "云组3"))
        self.tempo2_wind_label.setText(_translate("TAFEdit", "风向风速"))
        self.tempo2_period_label.setText(_translate("TAFEdit", "时段"))
        self.tempo2_gust_label.setText(_translate("TAFEdit", "阵风"))
        self.tempo2_cloud2_label.setText(_translate("TAFEdit", "云组2"))
        self.tempo2_weather2_label.setText(_translate("TAFEdit", "天气现象2"))
        self.tempo2_cloud1_label.setText(_translate("TAFEdit", "云组1"))
        self.tempo2_vis_label.setText(_translate("TAFEdit", "能见度"))
        self.tempo2_weather1_label.setText(_translate("TAFEdit", "天气现象1"))
        self.tempo2_cb_label.setText(_translate("TAFEdit", "积雨云"))
        self.taf_next.setText(_translate("TAFEdit", "下一步"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TAFEdit = QtWidgets.QDialog()
    ui = Ui_TAFEdit()
    ui.setupUi(TAFEdit)
    TAFEdit.show()
    sys.exit(app.exec_())

