# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Work\tafor\tafor\ui\widgets_primary.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 196)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_layout = QtWidgets.QGridLayout()
        self.main_layout.setObjectName("main_layout")
        self.taf_weather1_combobox = QtWidgets.QComboBox(Form)
        self.taf_weather1_combobox.setObjectName("taf_weather1_combobox")
        self.main_layout.addWidget(self.taf_weather1_combobox, 3, 5, 1, 1)
        self.taf_weather2_combobox = QtWidgets.QComboBox(Form)
        self.taf_weather2_combobox.setObjectName("taf_weather2_combobox")
        self.main_layout.addWidget(self.taf_weather2_combobox, 3, 6, 1, 1)
        self.taf_temp_min = QtWidgets.QLineEdit(Form)
        self.taf_temp_min.setObjectName("taf_temp_min")
        self.main_layout.addWidget(self.taf_temp_min, 6, 10, 1, 1)
        self.taf_skc = QtWidgets.QCheckBox(Form)
        self.taf_skc.setObjectName("taf_skc")
        self.main_layout.addWidget(self.taf_skc, 4, 7, 1, 1)
        self.tempo1_checkbox = QtWidgets.QCheckBox(Form)
        self.tempo1_checkbox.setObjectName("tempo1_checkbox")
        self.main_layout.addWidget(self.tempo1_checkbox, 5, 1, 1, 1)
        self.taf_cloud3_label = QtWidgets.QLabel(Form)
        self.taf_cloud3_label.setObjectName("taf_cloud3_label")
        self.main_layout.addWidget(self.taf_cloud3_label, 2, 9, 1, 1)
        self.taf_vis = QtWidgets.QLineEdit(Form)
        self.taf_vis.setObjectName("taf_vis")
        self.main_layout.addWidget(self.taf_vis, 3, 4, 1, 1)
        self.becmg2_checkbox = QtWidgets.QCheckBox(Form)
        self.becmg2_checkbox.setObjectName("becmg2_checkbox")
        self.main_layout.addWidget(self.becmg2_checkbox, 6, 0, 1, 1)
        self.taf_cloud1_label = QtWidgets.QLabel(Form)
        self.taf_cloud1_label.setObjectName("taf_cloud1_label")
        self.main_layout.addWidget(self.taf_cloud1_label, 2, 7, 1, 1)
        self.taf_cloud2 = QtWidgets.QLineEdit(Form)
        self.taf_cloud2.setObjectName("taf_cloud2")
        self.main_layout.addWidget(self.taf_cloud2, 3, 8, 1, 1)
        self.taf_cloud2_label = QtWidgets.QLabel(Form)
        self.taf_cloud2_label.setObjectName("taf_cloud2_label")
        self.main_layout.addWidget(self.taf_cloud2_label, 2, 8, 1, 1)
        self.taf_nsc = QtWidgets.QCheckBox(Form)
        self.taf_nsc.setObjectName("taf_nsc")
        self.main_layout.addWidget(self.taf_nsc, 4, 8, 1, 1)
        self.taf_gust = QtWidgets.QLineEdit(Form)
        self.taf_gust.setObjectName("taf_gust")
        self.main_layout.addWidget(self.taf_gust, 3, 3, 1, 1)
        self.taf_temp_min_label = QtWidgets.QLabel(Form)
        self.taf_temp_min_label.setObjectName("taf_temp_min_label")
        self.main_layout.addWidget(self.taf_temp_min_label, 5, 10, 1, 1)
        self.becmg3_checkbox = QtWidgets.QCheckBox(Form)
        self.becmg3_checkbox.setObjectName("becmg3_checkbox")
        self.main_layout.addWidget(self.becmg3_checkbox, 8, 0, 1, 1)
        self.taf_vis_label = QtWidgets.QLabel(Form)
        self.taf_vis_label.setObjectName("taf_vis_label")
        self.main_layout.addWidget(self.taf_vis_label, 2, 4, 1, 1)
        self.taf_weather1_label = QtWidgets.QLabel(Form)
        self.taf_weather1_label.setObjectName("taf_weather1_label")
        self.main_layout.addWidget(self.taf_weather1_label, 2, 5, 1, 1)
        self.taf_gust_label = QtWidgets.QLabel(Form)
        self.taf_gust_label.setObjectName("taf_gust_label")
        self.main_layout.addWidget(self.taf_gust_label, 2, 3, 1, 1)
        self.taf_date = QtWidgets.QLineEdit(Form)
        self.taf_date.setObjectName("taf_date")
        self.main_layout.addWidget(self.taf_date, 3, 0, 1, 1)
        self.taf_cavok = QtWidgets.QCheckBox(Form)
        self.taf_cavok.setObjectName("taf_cavok")
        self.main_layout.addWidget(self.taf_cavok, 4, 4, 1, 1)
        self.taf_cloud1 = QtWidgets.QLineEdit(Form)
        self.taf_cloud1.setObjectName("taf_cloud1")
        self.main_layout.addWidget(self.taf_cloud1, 3, 7, 1, 1)
        self.becmg1_checkbox = QtWidgets.QCheckBox(Form)
        self.becmg1_checkbox.setObjectName("becmg1_checkbox")
        self.main_layout.addWidget(self.becmg1_checkbox, 5, 0, 1, 1)
        self.taf_date_label = QtWidgets.QLabel(Form)
        self.taf_date_label.setObjectName("taf_date_label")
        self.main_layout.addWidget(self.taf_date_label, 2, 0, 1, 1)
        self.taf_period_label = QtWidgets.QLabel(Form)
        self.taf_period_label.setObjectName("taf_period_label")
        self.main_layout.addWidget(self.taf_period_label, 2, 1, 1, 1)
        self.taf_cb_label = QtWidgets.QLabel(Form)
        self.taf_cb_label.setObjectName("taf_cb_label")
        self.main_layout.addWidget(self.taf_cb_label, 2, 10, 1, 1)
        self.taf_wind_label = QtWidgets.QLabel(Form)
        self.taf_wind_label.setObjectName("taf_wind_label")
        self.main_layout.addWidget(self.taf_wind_label, 2, 2, 1, 1)
        self.taf_wind = QtWidgets.QLineEdit(Form)
        self.taf_wind.setObjectName("taf_wind")
        self.main_layout.addWidget(self.taf_wind, 3, 2, 1, 1)
        self.taf_temp_max_label = QtWidgets.QLabel(Form)
        self.taf_temp_max_label.setObjectName("taf_temp_max_label")
        self.main_layout.addWidget(self.taf_temp_max_label, 5, 9, 1, 1)
        self.taf_cloud3 = QtWidgets.QLineEdit(Form)
        self.taf_cloud3.setObjectName("taf_cloud3")
        self.main_layout.addWidget(self.taf_cloud3, 3, 9, 1, 1)
        self.taf_temp_max = QtWidgets.QLineEdit(Form)
        self.taf_temp_max.setObjectName("taf_temp_max")
        self.main_layout.addWidget(self.taf_temp_max, 6, 9, 1, 1)
        self.taf_weather2_label = QtWidgets.QLabel(Form)
        self.taf_weather2_label.setObjectName("taf_weather2_label")
        self.main_layout.addWidget(self.taf_weather2_label, 2, 6, 1, 1)
        self.tempo2_checkbox = QtWidgets.QCheckBox(Form)
        self.tempo2_checkbox.setObjectName("tempo2_checkbox")
        self.main_layout.addWidget(self.tempo2_checkbox, 6, 1, 1, 1)
        self.taf_period = QtWidgets.QLineEdit(Form)
        self.taf_period.setObjectName("taf_period")
        self.main_layout.addWidget(self.taf_period, 3, 1, 1, 1)
        self.taf_cb = QtWidgets.QLineEdit(Form)
        self.taf_cb.setObjectName("taf_cb")
        self.main_layout.addWidget(self.taf_cb, 3, 10, 1, 1)
        self.group_type = QtWidgets.QGroupBox(Form)
        self.group_type.setTitle("")
        self.group_type.setObjectName("group_type")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.group_type)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.type_fc = QtWidgets.QRadioButton(self.group_type)
        self.type_fc.setObjectName("type_fc")
        self.gridLayout_6.addWidget(self.type_fc, 0, 0, 1, 1)
        self.type_ft = QtWidgets.QRadioButton(self.group_type)
        self.type_ft.setObjectName("type_ft")
        self.gridLayout_6.addWidget(self.type_ft, 0, 1, 1, 1)
        self.main_layout.addWidget(self.group_type, 0, 0, 1, 2)
        self.group_cls = QtWidgets.QGroupBox(Form)
        self.group_cls.setTitle("")
        self.group_cls.setObjectName("group_cls")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.group_cls)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.cls_normal = QtWidgets.QRadioButton(self.group_cls)
        self.cls_normal.setChecked(True)
        self.cls_normal.setObjectName("cls_normal")
        self.gridLayout_5.addWidget(self.cls_normal, 0, 0, 1, 1)
        self.cls_cor = QtWidgets.QRadioButton(self.group_cls)
        self.cls_cor.setObjectName("cls_cor")
        self.gridLayout_5.addWidget(self.cls_cor, 0, 1, 1, 1)
        self.cls_cor_combobox = QtWidgets.QComboBox(self.group_cls)
        self.cls_cor_combobox.setObjectName("cls_cor_combobox")
        self.gridLayout_5.addWidget(self.cls_cor_combobox, 0, 2, 1, 1)
        self.cls_amd = QtWidgets.QRadioButton(self.group_cls)
        self.cls_amd.setObjectName("cls_amd")
        self.gridLayout_5.addWidget(self.cls_amd, 0, 3, 1, 1)
        self.cls_amd_combobox = QtWidgets.QComboBox(self.group_cls)
        self.cls_amd_combobox.setObjectName("cls_amd_combobox")
        self.gridLayout_5.addWidget(self.cls_amd_combobox, 0, 4, 1, 1)
        self.cls_cnl = QtWidgets.QRadioButton(self.group_cls)
        self.cls_cnl.setObjectName("cls_cnl")
        self.gridLayout_5.addWidget(self.cls_cnl, 0, 5, 1, 1)
        self.cls_cnl_combobox = QtWidgets.QComboBox(self.group_cls)
        self.cls_cnl_combobox.setObjectName("cls_cnl_combobox")
        self.gridLayout_5.addWidget(self.cls_cnl_combobox, 0, 6, 1, 1)
        self.main_layout.addWidget(self.group_cls, 0, 4, 1, 7)
        self.verticalLayout.addLayout(self.main_layout)
        self.taf_cloud3_label.setBuddy(self.taf_cloud3)
        self.taf_cloud1_label.setBuddy(self.taf_cloud1)
        self.taf_cloud2_label.setBuddy(self.taf_cloud2)
        self.taf_temp_min_label.setBuddy(self.taf_temp_min)
        self.taf_vis_label.setBuddy(self.taf_vis)
        self.taf_weather1_label.setBuddy(self.taf_weather1_combobox)
        self.taf_gust_label.setBuddy(self.taf_gust)
        self.taf_date_label.setBuddy(self.taf_date)
        self.taf_period_label.setBuddy(self.taf_period)
        self.taf_cb_label.setBuddy(self.taf_cb)
        self.taf_wind_label.setBuddy(self.taf_wind)
        self.taf_temp_max_label.setBuddy(self.taf_temp_max)
        self.taf_weather2_label.setBuddy(self.taf_weather2_combobox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.type_fc, self.type_ft)
        Form.setTabOrder(self.type_ft, self.cls_normal)
        Form.setTabOrder(self.cls_normal, self.cls_cor)
        Form.setTabOrder(self.cls_cor, self.cls_cor_combobox)
        Form.setTabOrder(self.cls_cor_combobox, self.cls_amd)
        Form.setTabOrder(self.cls_amd, self.cls_amd_combobox)
        Form.setTabOrder(self.cls_amd_combobox, self.cls_cnl)
        Form.setTabOrder(self.cls_cnl, self.cls_cnl_combobox)
        Form.setTabOrder(self.cls_cnl_combobox, self.taf_date)
        Form.setTabOrder(self.taf_date, self.taf_period)
        Form.setTabOrder(self.taf_period, self.taf_wind)
        Form.setTabOrder(self.taf_wind, self.taf_gust)
        Form.setTabOrder(self.taf_gust, self.taf_vis)
        Form.setTabOrder(self.taf_vis, self.taf_weather1_combobox)
        Form.setTabOrder(self.taf_weather1_combobox, self.taf_weather2_combobox)
        Form.setTabOrder(self.taf_weather2_combobox, self.taf_cloud1)
        Form.setTabOrder(self.taf_cloud1, self.taf_cloud2)
        Form.setTabOrder(self.taf_cloud2, self.taf_cloud3)
        Form.setTabOrder(self.taf_cloud3, self.taf_cb)
        Form.setTabOrder(self.taf_cb, self.taf_cavok)
        Form.setTabOrder(self.taf_cavok, self.taf_skc)
        Form.setTabOrder(self.taf_skc, self.taf_nsc)
        Form.setTabOrder(self.taf_nsc, self.taf_temp_max)
        Form.setTabOrder(self.taf_temp_max, self.taf_temp_min)
        Form.setTabOrder(self.taf_temp_min, self.becmg1_checkbox)
        Form.setTabOrder(self.becmg1_checkbox, self.becmg2_checkbox)
        Form.setTabOrder(self.becmg2_checkbox, self.becmg3_checkbox)
        Form.setTabOrder(self.becmg3_checkbox, self.tempo1_checkbox)
        Form.setTabOrder(self.tempo1_checkbox, self.tempo2_checkbox)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.taf_skc.setText(_translate("Form", "SKC"))
        self.tempo1_checkbox.setText(_translate("Form", "TEMPO1"))
        self.taf_cloud3_label.setText(_translate("Form", "云组3"))
        self.becmg2_checkbox.setText(_translate("Form", "BECMG2"))
        self.taf_cloud1_label.setText(_translate("Form", "云组1"))
        self.taf_cloud2_label.setText(_translate("Form", "云组2"))
        self.taf_nsc.setText(_translate("Form", "NSC"))
        self.taf_temp_min_label.setText(_translate("Form", "最低温"))
        self.becmg3_checkbox.setText(_translate("Form", "BECMG3"))
        self.taf_vis_label.setText(_translate("Form", "能见度"))
        self.taf_weather1_label.setText(_translate("Form", "天气现象1"))
        self.taf_gust_label.setText(_translate("Form", "阵风"))
        self.taf_cavok.setText(_translate("Form", "CAVOK"))
        self.becmg1_checkbox.setText(_translate("Form", "BECMG1"))
        self.taf_date_label.setText(_translate("Form", "日期"))
        self.taf_period_label.setText(_translate("Form", "时段"))
        self.taf_cb_label.setText(_translate("Form", "积雨云"))
        self.taf_wind_label.setText(_translate("Form", "风向风速"))
        self.taf_temp_max_label.setText(_translate("Form", "最高温"))
        self.taf_weather2_label.setText(_translate("Form", "天气现象2"))
        self.tempo2_checkbox.setText(_translate("Form", "TEMPO2"))
        self.type_fc.setText(_translate("Form", "FC"))
        self.type_ft.setText(_translate("Form", "FT"))
        self.cls_normal.setText(_translate("Form", "正常报"))
        self.cls_cor.setText(_translate("Form", "更正报"))
        self.cls_amd.setText(_translate("Form", "修订报"))
        self.cls_cnl.setText(_translate("Form", "取消报"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

