# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Work\tafor\tafor\ui\widgets_tempo.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 80)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tempo_layout = QtWidgets.QGridLayout()
        self.tempo_layout.setObjectName("tempo_layout")
        self.tempo_wind_label = QtWidgets.QLabel(Form)
        self.tempo_wind_label.setObjectName("tempo_wind_label")
        self.tempo_layout.addWidget(self.tempo_wind_label, 0, 5, 1, 1)
        self.tempo_cloud3_label = QtWidgets.QLabel(Form)
        self.tempo_cloud3_label.setObjectName("tempo_cloud3_label")
        self.tempo_layout.addWidget(self.tempo_cloud3_label, 0, 12, 1, 1)
        self.tempo_period_label = QtWidgets.QLabel(Form)
        self.tempo_period_label.setObjectName("tempo_period_label")
        self.tempo_layout.addWidget(self.tempo_period_label, 0, 4, 1, 1)
        self.tempo_period = QtWidgets.QLineEdit(Form)
        self.tempo_period.setObjectName("tempo_period")
        self.tempo_layout.addWidget(self.tempo_period, 2, 4, 1, 1)
        self.tempo_gust_label = QtWidgets.QLabel(Form)
        self.tempo_gust_label.setObjectName("tempo_gust_label")
        self.tempo_layout.addWidget(self.tempo_gust_label, 0, 6, 1, 1)
        self.tempo_cloud1 = QtWidgets.QLineEdit(Form)
        self.tempo_cloud1.setObjectName("tempo_cloud1")
        self.tempo_layout.addWidget(self.tempo_cloud1, 2, 10, 1, 1)
        self.tempo_weather2 = QtWidgets.QComboBox(Form)
        self.tempo_weather2.setObjectName("tempo_weather2")
        self.tempo_layout.addWidget(self.tempo_weather2, 2, 9, 1, 1)
        self.tempo_vis = QtWidgets.QLineEdit(Form)
        self.tempo_vis.setObjectName("tempo_vis")
        self.tempo_layout.addWidget(self.tempo_vis, 2, 7, 1, 1)
        self.tempo_cb = QtWidgets.QLineEdit(Form)
        self.tempo_cb.setObjectName("tempo_cb")
        self.tempo_layout.addWidget(self.tempo_cb, 2, 13, 1, 1)
        self.tempo_cloud2_label = QtWidgets.QLabel(Form)
        self.tempo_cloud2_label.setObjectName("tempo_cloud2_label")
        self.tempo_layout.addWidget(self.tempo_cloud2_label, 0, 11, 1, 1)
        self.tempo_vis_label = QtWidgets.QLabel(Form)
        self.tempo_vis_label.setObjectName("tempo_vis_label")
        self.tempo_layout.addWidget(self.tempo_vis_label, 0, 7, 1, 1)
        self.tempo_wind = QtWidgets.QLineEdit(Form)
        self.tempo_wind.setObjectName("tempo_wind")
        self.tempo_layout.addWidget(self.tempo_wind, 2, 5, 1, 1)
        self.tempo_weather2_label = QtWidgets.QLabel(Form)
        self.tempo_weather2_label.setObjectName("tempo_weather2_label")
        self.tempo_layout.addWidget(self.tempo_weather2_label, 0, 9, 1, 1)
        self.tempo_cloud2 = QtWidgets.QLineEdit(Form)
        self.tempo_cloud2.setObjectName("tempo_cloud2")
        self.tempo_layout.addWidget(self.tempo_cloud2, 2, 11, 1, 1)
        self.tempo_prob40 = QtWidgets.QCheckBox(Form)
        self.tempo_prob40.setObjectName("tempo_prob40")
        self.tempo_layout.addWidget(self.tempo_prob40, 3, 5, 1, 1)
        self.tempo_gust = QtWidgets.QLineEdit(Form)
        self.tempo_gust.setObjectName("tempo_gust")
        self.tempo_layout.addWidget(self.tempo_gust, 2, 6, 1, 1)
        self.tempo_cloud1_label = QtWidgets.QLabel(Form)
        self.tempo_cloud1_label.setObjectName("tempo_cloud1_label")
        self.tempo_layout.addWidget(self.tempo_cloud1_label, 0, 10, 1, 1)
        self.tempo_cloud3 = QtWidgets.QLineEdit(Form)
        self.tempo_cloud3.setObjectName("tempo_cloud3")
        self.tempo_layout.addWidget(self.tempo_cloud3, 2, 12, 1, 1)
        self.tempo_prob30 = QtWidgets.QCheckBox(Form)
        self.tempo_prob30.setObjectName("tempo_prob30")
        self.tempo_layout.addWidget(self.tempo_prob30, 3, 4, 1, 1)
        self.tempo_weather1 = QtWidgets.QComboBox(Form)
        self.tempo_weather1.setObjectName("tempo_weather1")
        self.tempo_layout.addWidget(self.tempo_weather1, 2, 8, 1, 1)
        self.tempo_cb_label = QtWidgets.QLabel(Form)
        self.tempo_cb_label.setObjectName("tempo_cb_label")
        self.tempo_layout.addWidget(self.tempo_cb_label, 0, 13, 1, 1)
        self.tempo_weather1_label = QtWidgets.QLabel(Form)
        self.tempo_weather1_label.setObjectName("tempo_weather1_label")
        self.tempo_layout.addWidget(self.tempo_weather1_label, 0, 8, 1, 1)
        self.tempo_title = QtWidgets.QLabel(Form)
        self.tempo_title.setMinimumSize(QtCore.QSize(90, 0))
        self.tempo_title.setStyleSheet("color: rgb(120, 120, 120);")
        self.tempo_title.setObjectName("tempo_title")
        self.tempo_layout.addWidget(self.tempo_title, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.tempo_layout)
        self.tempo_wind_label.setBuddy(self.tempo_wind)
        self.tempo_cloud3_label.setBuddy(self.tempo_cloud3)
        self.tempo_period_label.setBuddy(self.tempo_period)
        self.tempo_gust_label.setBuddy(self.tempo_gust)
        self.tempo_cloud2_label.setBuddy(self.tempo_cloud2)
        self.tempo_vis_label.setBuddy(self.tempo_vis)
        self.tempo_weather2_label.setBuddy(self.tempo_weather2)
        self.tempo_cloud1_label.setBuddy(self.tempo_cloud1)
        self.tempo_cb_label.setBuddy(self.tempo_cb)
        self.tempo_weather1_label.setBuddy(self.tempo_weather1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.tempo_period, self.tempo_wind)
        Form.setTabOrder(self.tempo_wind, self.tempo_gust)
        Form.setTabOrder(self.tempo_gust, self.tempo_vis)
        Form.setTabOrder(self.tempo_vis, self.tempo_weather1)
        Form.setTabOrder(self.tempo_weather1, self.tempo_weather2)
        Form.setTabOrder(self.tempo_weather2, self.tempo_cloud1)
        Form.setTabOrder(self.tempo_cloud1, self.tempo_cloud2)
        Form.setTabOrder(self.tempo_cloud2, self.tempo_cloud3)
        Form.setTabOrder(self.tempo_cloud3, self.tempo_cb)
        Form.setTabOrder(self.tempo_cb, self.tempo_prob30)
        Form.setTabOrder(self.tempo_prob30, self.tempo_prob40)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tempo_wind_label.setText(_translate("Form", "风向风速"))
        self.tempo_cloud3_label.setText(_translate("Form", "云组3"))
        self.tempo_period_label.setText(_translate("Form", "时段"))
        self.tempo_gust_label.setText(_translate("Form", "阵风"))
        self.tempo_cloud2_label.setText(_translate("Form", "云组2"))
        self.tempo_vis_label.setText(_translate("Form", "能见度"))
        self.tempo_weather2_label.setText(_translate("Form", "天气现象2"))
        self.tempo_prob40.setText(_translate("Form", "PROB40"))
        self.tempo_cloud1_label.setText(_translate("Form", "云组1"))
        self.tempo_prob30.setText(_translate("Form", "PROB30"))
        self.tempo_cb_label.setText(_translate("Form", "积雨云"))
        self.tempo_weather1_label.setText(_translate("Form", "天气现象1"))
        self.tempo_title.setText(_translate("Form", "TEMPO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

